### ISSUE TITLE
controls_if: Mutation actions do not undo correctly

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2037] opened 2018-08-30 22:43 UTC
### Problem statement

Undo does not work correctly when `controls_if` mutator edit actions are interleaved with normal actions.

### Expected Behavior

One undo step should undo to the previous step, maintaining connections unaffected by the edit.

### Actual Behavior

A block connected to an if block where an undo reverts a mutation may also disconnect the child, even when the connected input is not (supposed to be) affected by the mutation.

### Steps to Reproduce

1. Open the playground and create the following structure:
<img width="379" alt="screen shot 2018-08-30 at 2 16 52 pm" src="https://user-images.githubusercontent.com/9916202/44880155-7be14980-ac60-11e8-8b1a-48dfac7b2ed9.png">
2. Next, make the following edits:
  a. Add an "else if" in the mutator.
  b. Connect the loop block to the newly created second statement connection
  c. Add an "else" to the end, within the mutator.

The results should look like this:
<img width="328" alt="screen shot 2018-08-30 at 2 27 54 pm" src="https://user-images.githubusercontent.com/9916202/44880340-06c24400-ac61-11e8-82bc-3b71737d5ce0.png">

3. Undo one step, removing the last connection.
<img width="317" alt="screen shot 2018-08-30 at 2 29 23 pm" src="https://user-images.githubusercontent.com/9916202/44880397-2e191100-ac61-11e8-891d-b3cfc488de4c.png">

Note that making what was supposed to be a single step, editing the last connection via the mutator workspace, it has also disconnected the loop block.

**Comment by AnmAtAnm** [comment] 2018-08-30 22:58
Comparable behavior appears to work correctly with `text_join` (aka, "create text") and `lists_create_with`. Thus, I'm assuming the bug it specific to the `controls_if` block, and I've rewritten and retitled the issue to reflect this.

That said, something is bothering me. How is the undo/redo event stream not capturing the necessary changes when capturing the before and after `<mutation>` changes? What assumption is the `controls_if` mutator breaking, and why is that an assumption at all?

**Comment by cpcallen** [comment] 2024-07-04 23:24
This issue exists in again in `develop` (noted at a6361fb).

This issue was originally fixed in #2167 by introducing the method `Blockly.Constants.Logic.CONTROLS_IF_MUTATOR_MIXIN.rebuildShape_`, which calls `this.updateShape_()` and then reconnects any blocks that were disconnected, and then having `.domToMutation` call `this.rebuildShape_()` instead of `this.updateShape_()`.

Using `git bisect` suggests that the issue was reintroduced in PR #5378.  The proximate cause appears to be the change to `Blockly.Events.BlockChange.prototype.run` to prefer using `.loadExtraState` rather than `.domToMutation` when replaying `BlockChange` events.  The reason this makes a difference is that the implementation of `Blockly.Constants.Logic.CONTROLS_IF_MUTATOR_MIXIN.loadExtraState` introduced in PR #5329 calls `this.updateShape_()` rather than `this.rebuildShape_()`.

**Comment by cpcallen** [comment] 2024-07-05 00:53
The root cause of this issue appears to be the same as issue #8225: [`BlockMove` events being filtered out due to events being fired in the wrong order](https://github.com/google/blockly/issues/8225#issuecomment-2195751783):

In the reproduction steps given above, at the point the else clause block is added to the stack in the mutator flyout, the following events are fired (in the given order) (edited for readability):

```JS
BlockMove {
  blockId: "%RcdpdplAuHZK~LiL}9+",
  newCoordinate: undefined,
  newInputName: "DO1",
  newParentId: "RM=6@108I~w2-=F!NzF[",
  oldCoordinate: undefined,
  oldInputName: "DO1",
  oldParentId: "RM=6@108I~w2-=F!NzF[",
  recordUndo: true,
}
BlockMove {
  blockId: "%RcdpdplAuHZK~LiL}9+",
  newCoordinate: undefined,
  newInputName: "DO1",
  newParentId: "RM=6@108I~w2-=F!NzF[",
  oldCoordinate: Coordinate {x: 200.29159545898438, y: 189.7638931274414},
  oldInputName: undefined,
  oldParentId: undefined,
  recordUndo: true,
}
BlockChange {
  blockId: "RM=6@108I~w2-=F!NzF[",
  element: "mutation",
  name: null,
  newValue: "{\"elseIfCount\":1,\"hasElse\":true}",
  oldValue: "{\"elseIfCount\":1}",
  recordUndo: true,
}
```
There is one small wrinkle: unlike the similar event queue reported in the root cause analysis for #8225, the first `BlockMove` here does not appear to be a disconnect event.  Nevertheless, neither `BlockMove` event survives filtering, with only the `BlockChange` event actually being effected (and, it seems, therefore available to be undone).

**Comment by cpcallen** [comment] 2024-07-10 15:29
In the process of investigating #7950 I have realised that the events listed in [my previous comment](https://github.com/google/blockly/issues/2037#issuecomment-2209696351) may be wrong because although they were logged at the time that they were `fire()`ed, I was using console inspector _after_ they had been subject to having been modified by `filter()` between when they were initially logged and when I inspected their values.

**Closed** 2024-08-29 16:41 UTC
Labels: issue: bug, component: events

**Comment by cpcallen** [comment] 2024-08-30 19:09
This has been adequately patched for the time being by the (new, higher quality) bandaid in #8539, but the [underlying root cause remains](https://github.com/google/blockly/issues/1036#issuecomment-2322174773) and is tracked in #1036.
