### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by ashwani-anzo** [google/blockly#7881] opened 2024-02-22 04:32 UTC
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

while importin any of function or class from modules getting error
 Failed to parse source map from '/home/ashwani/Desktop/reactblockly/node_modules/blockly/src/com/google/javascript/jscomp/js/util/polyfill.js' file: Error: ENOENT: no such file or directory, open '/home/ashwani/Desktop/reactblockly/node_modules/blockly/src/com/google/javascript/jscomp/js/util/polyfill.js'

WARNING in ./node_modules/blockly/blockly_compressed.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/ashwani/Desktop/reactblockly/node_modules/blockly/src/com/google/javascript/jscomp/js/util/shouldpolyfill.js' file: Error: ENOENT: no such file or directory, open '/home/ashwani/Desktop/reactblockly/node_modules/blockly/src/com/google/javascript/jscomp/js/util/shouldpolyfill.js

### Reproduction steps

1. 
2. 
3.

**Comment by maribethb** [comment] 2024-03-06 21:36
Hi, thanks for filing. We are aware of this but unfortunately do not control the tool that is emitting the bad sourcemaps. You can probably disable these warnings in whatever build system you're using. [Here's](https://github.com/google/blockly/issues/7124#issuecomment-1568760333) a bit more info.

Duplicate of #7124

**Closed by maribethb** 2024-03-06 21:36 UTC
Labels: issue: bug, issue: triage
