### ISSUE TITLE
Standardize how we set display for svg elements

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4874] opened 2021-06-05 00:41 UTC
**Describe the bug**
We seem to use `setAttribute('display', '...')` and 'style.display = ''` interchangeably in core.

`setAttribute('display', '...')` - Sets the display attribute on the svg element. 
'style.display = ''` - Is an inline CSS style.

We should look into this to see if there is a reason we are using one over the other and if possible move them over to use the same method. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by gonfunko** [comment] 2023-02-14 23:53
Duplicate of #6547

**Closed by gonfunko** 2023-02-14 23:53 UTC
Labels: issue: bug
