### ISSUE TITLE
Shortcut Register e.preventDefault() not working in Firefox for Ctrl+B?

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#7697] opened 2023-12-06 19:12 UTC
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Adding keyboard shortcut does not work fully in firefox?
Blockly.ShortcutRegistry.registry.createSerializedKey(
      Blockly.utils.KeyCodes.B,
      [Blockly.utils.KeyCodes.CTRL],
    )
That shortcut opens bookmark in the firefox browser. Chrome is not affected.

### Reproduction steps

1. 
2. 
3.

**Comment by maribethb** [comment] 2024-01-03 21:47
@NeilFraser would you be able to take a look at this one?

**Comment by NeilFraser** [comment] 2024-03-14 22:52
I've tested on Mac, on Windows 11 via Parallels, with different keyboard layouts, different computers, several browsers, and different modifier keys.  In every case the bookmark tab stays closed when Blockly intercepts the keystroke.  I'm afraid I cannot recreate.

Can anyone else recreate this?

**Comment by NeilFraser** [comment] 2024-03-14 22:57
For reference, the best way I know to test this is to edit shortcut_items.ts and change the three keycodes listed under

```Keyboard shortcut to copy a block on ctrl+c, cmd+c, or alt+c.```

from 'C' to 'B'.  Then copy a block using modifier-B, observe whether the bookmark tab appears, then verify the action by pasting the block.  Note that modifier-B on a blank workspace does open the bookmark tab, which is expected since Blockly didn't intercept the keystroke in that case.

**Comment by BeksOmega** [comment] 2024-03-14 23:14
> For reference, the best way I know to test this is to edit shortcut_items.ts and change the three keycodes listed under
> 
> `Keyboard shortcut to copy a block on ctrl+c, cmd+c, or alt+c.`
> 
> from 'C' to 'B'. Then copy a block using modifier-B, observe whether the bookmark tab appears, then verify the action by pasting the block. Note that modifier-B on a blank workspace does open the bookmark tab, which is expected since Blockly didn't intercept the keystroke in that case.

I don't think that having an empty workspace means that we don't intercept the keyboard event. We should still call any callbacks (e.g. if ctrl + b meant "add a bunch of random blocks").

That being said, i think the issue here is that the original reporter wasn't calling `e.preventDefault` on the passed event.

**Comment by maribethb** [comment] 2024-03-14 23:18
> That being said, i think the issue here is that the original reporter wasn't calling e.preventDefault on the passed event.

That was our initial thought, but the title of the issue implies otherwise.

But if we aren't able to reproduce this, I'm happy to close it.

@mrkprdo can you provide more detailed reproduction steps including sharing the shortcut callback you're registering? Otherwise we'll have to close this as we're unable to reproduce. Thanks!

**Comment by mrkprdo** [comment] 2024-03-14 23:49
just in time lurking around blockly :)
I'm using `blockly: v10.2.2` and `firefox: 123.0.1`
Here's my sample code:
```javascript
  registerShortcut() {
    const shortcut = Blockly.ShortcutRegistry.registry.createSerializedKey(
      Blockly.utils.KeyCodes.B,
      [Blockly.utils.KeyCodes.CTRL],
    )
    if (!Blockly.ShortcutRegistry.registry.shortcuts.get('TOOLBOXSEARCH_SHORTCUT')) {
      // the if-block avoids re-registering when hot-reloading
      Blockly.ShortcutRegistry.registry.register({
        name: 'TOOLBOXSEARCH_SHORTCUT',
        callback: () => {
          if (this.parentToolbox_.getSelectedItem() !== this) {
            this.parentToolbox_.selectItemByPosition(this.getPosition())
          }
        },
        keyCodes: [shortcut],
      })
    }
  }
```
Basically, this code is just to open Toolbox Search we made as one of the Toolbox Category. When "ctrl+B" it should open the toolbox flyout. It is working in Chrome, but Firefox will open bookmark instead.

**Comment by maribethb** [comment] 2024-03-15 00:47
Thanks Mark.

It looks like Beka is correct then. The shortcut callback takes 3 arguments (workspace, event, and the shortcut itself). If you modify your callback to accept those arguments (or at least the first 2), and then call `preventDefault()` on the second argument, can you still reproduce this?

**Comment by mrkprdo** [comment] 2024-03-15 03:34
@maribethb, my bad, I actually have those in my original code before, i removed them since they were not working (right after that, I posted this issue).
So testing again with event.preventDefault() and I even had event.stopPropagation() & event.stopImmediatePropagation(), it still shows the bookmark sidebar.
```javascript
        callback: (workspace, event) => {
          event.preventDefault()
          // event.stopPropagation()
          console.log('callback is called...')
          if (this.parentToolbox_.getSelectedItem() !== this) {
            this.parentToolbox_.selectItemByPosition(this.getPosition())
          }
        },
```
One thing I noticed tho, it only gets triggered (bookmark) after the second or more attempt, it looks like it kinda detaches from from the registry after first press (shortcut is disabled??). But when I close the toolbox flyout by clicking elsewhere, it "resets" the behaviour.
When I commented out the if statement inside the callback and the bookmark does not show up!
I think something is breaking in that code.

**Comment by maribethb** [comment] 2024-03-20 22:18
I think this is likely due to a specific interaction in your application rather than a bug in blockly, so I'm going to close this issue. We aren't set up to help with application-specific debugging on GitHub Issues, your issue will likely get lost. Instead, if you still need help, could you please post on the forum?

We definitely do not remove your shortcut from the registry when it has been disabled. I would turn on event logging in the developer console and see which elements are receiving the keypress. If you have a custom element that is receiving focus then perhaps the workspace is not receiving the keydown event handler in the first place in order to activate the shortcut. The actual keydown event handlers are registered on the workspace, so they need to hear that keydown event in order to call the shortcut.

**Closed by maribethb** 2024-03-20 22:18 UTC
Labels: issue: bug, help wanted, issue: triage
