### ISSUE TITLE
Feature request: Don't scale toolbox buttons and labels

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1820] opened 2018-04-23 20:28 UTC
### Problem statement

Like the blocks in the toolbox, the buttons and labels in the toolbox also scale with the workspace zoom level.  This can make the buttons and labels unreadable or excessively large.

### Expected Behavior

Open question.
It seems reasonable to expect the buttons and labels to maintain their scale so they are always readable and authors can have expectations of appropriate line length when writing copy for the button title and label. Compare to the category labels.  That said, such a solution adds significant complications to the toolbox.

### Actual Behavior

Zoomed out:
![screen shot 2018-04-23 at 12 07 57 pm](https://user-images.githubusercontent.com/9916202/39147826-8cedfd4e-46ef-11e8-9144-ce73fe9deafc.png)

Zoomed in:
![screen shot 2018-04-23 at 12 08 15 pm](https://user-images.githubusercontent.com/9916202/39147844-971d952c-46ef-11e8-942a-f8e28bcfaa2f.png)

### Steps to Reproduce

1. In the playground with the normal categorical toolbox, zoom in the workspace. The more extreme the better.
2. Open the Variables category and notice the font size of the "Create variable..." button.

3. Zoom out the workspace.
4. Open the Variables category and again notice the font size of the "Create variable..." button.

Note that the user cannot adjust the zoom while the toolbox is open. Pressing a zoom button or scrolling the mouse wheel over the workspace will close the toolbox. Scrolling the mouse wheel over the flyout will scroll the list.

**Comment by trodi** [comment] 2019-10-29 18:42
Along this line of thought, it would be nice to (optionally) not scale blocks in the toolbox at all and only scale them once added to the workspace. Just as you mention that buttons/labels can become unreadable, so can the blocks themselves.

**Comment by 4n70w4** [comment] 2021-05-24 11:39
The same issue!

**Comment by maribethb** [comment] 2023-03-08 22:27
This is a duplicate of #4038.

Also we added the ability to override the flyout scale in #4647

**Closed by maribethb** 2023-03-08 22:27 UTC
Labels: type: question, component: toolbox/flyout, low priority, issue: feature request
