### ISSUE TITLE
Workspace jumps a bit when dragged if blocks do not fit the screen initially.

### ISSUE THREAD

**Issue by svbatalov** [google/blockly#426] opened 2016-06-11 08:02 UTC
Commit: 04d6d119c076

When blocks do not fit the screen initially (after creating Blockly and filling workspace) if I start to drag the workspace it suddenly shifts by some amount. If I zoom the workspace the effect disappears.

**Comment by NeilFraser** [comment] 2016-06-11 09:02
I believe this is a duplicate of #420 which has already been resolved.

**Closed by NeilFraser** 2016-06-11 09:02 UTC
