### ISSUE TITLE
Text width measuring does not respect CSS.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#5871] opened 2022-01-12 07:57 UTC
FieldLabels have an optional class parameter (which interestingly is not mentioned in [the docs](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/label), but is listed in [the reference](https://developers.google.com/blockly/reference/js/Blockly.FieldLabel)).  This allows one to change the font/size/colour and other attributes of the text.

However, changes made by a class to the label does not affect the computed width.  [Blockly.utils.dom.getTextWidth](https://github.com/google/blockly/blob/master/core/utils/dom.js#L282) does a perfectly good job, but it has largely been replaced by [Blockly.utils.dom.getFastTextWidth](https://github.com/google/blockly/blob/master/core/utils/dom.js#L323).  Whereas the former measures the actual onscreen text using the built-in `getComputedTextLength` function, the latter draws the text onto a canvas and measures the result.  Nothing drawn on a canvas is affected by CSS class rules.

The result is that (for example) if one adds some monotype text to a block, the text spills off the edge of the block:
<img width="365" alt="Screen Shot 2022-01-11 at 23 45 07" src="https://user-images.githubusercontent.com/250480/149086280-c98cb542-c965-4946-aeb5-90db4f37e17e.png">

Changing text colour is about the only safe action one can perform using a CSS class.

This bug surfaced as a result of PR #5868, but it's been lurking in the shadows for years ever since `getFastTextWidth` was created.

**Comment by BeksOmega** [comment] 2022-01-12 12:36
> which interestingly is not mentioned in the docs

Technically is mentioned in the docs :P "The label field takes in an optional value, and an optional css class string." But yeeee you're right, it should probably be in the example code, as well as in the description.

Also I think this is a dupe of #2694 ? Not sure which is better to close though.

**Comment by NeilFraser** [comment] 2022-01-13 08:52
I think #2694 is a superset of this issue, not a duplicate.  Its problem is mainly a complete lack of height info, whereas this issue only deals with incorrect width info.

Obtaining height info is nearly impossible, whereas correcting the width info appears to be feasible.  Thus I expect we can quickly resolve this issue, while leaving #2694 open.

**Comment by sahilrastogi94** [comment] 2024-07-10 10:12
Is this still being looked at?

**Comment by gonfunko** [comment] 2024-09-13 18:59
This seems to have been fixed by https://github.com/google/blockly/pull/8572.

**Closed by gonfunko** 2024-09-13 18:59 UTC
Labels: issue: bug, component: rendering
