### ISSUE TITLE
broken when rename arguments of function

### ISSUE THREAD

**Issue by duzc2** [google/blockly#2110] opened 2018-11-07 19:34 UTC
### Problem statement

when rename and delete all litters of a argument name in function with Input Method, blockly broken.

![_20181108032648](https://user-images.githubusercontent.com/564778/48155577-3b5c1700-e306-11e8-8c53-f34edceb2716.png)
![_20181108033038](https://user-images.githubusercontent.com/564778/48155781-bd4c4000-e306-11e8-81a4-7f48268fdbfa.png)

### Expected Behavior
no error

### Actual Behavior

![_20181108032140](https://user-images.githubusercontent.com/564778/48155575-3ac38080-e306-11e8-8f32-1aac41b656f3.png)

### Steps to Reproduce

1. Start by create a function with arguments
2. Next, rename a argument name to empty

### Stack Traces

```
Uncaught TypeError: Cannot read property 'name' of null
    at Blockly.BlockSvg.mutationToDom (blocks_compressed.js:92)
    at Blockly.Mutator.workspaceChanged_ (blockly_compressed.js:1321)
    at Blockly.WorkspaceSvg.Blockly.Workspace.fireChangeListener (blockly_compressed.js:953)
    at Blockly.Events.fireNow_ (blockly_compressed.js:901)
```

### Operating System and Browser

 Desktop Chrome

**Comment by RoboErikG** [comment] 2018-11-07 20:47
Thanks for filing! This is a duplicate of #1958

**Closed by RoboErikG** 2018-11-07 20:47 UTC
