### ISSUE TITLE
Block with maxInstances 'x' already disabled in toolbox when block 'x-1' is dragged on workspace

### ISSUE THREAD

**Issue by kvanthienen** [google/blockly#5374] opened 2021-08-16 12:55 UTC
**Describe the bug**

When the maxInstances option is set for a block (for example to 5), the corresponding block in the toolbox gets the 'blocklyDisabled' class after all the instances have been used in the workspace as expected. 
The strange thing, however, is that this block already temporarily gets the 'blocklyDisabled' status while dragging around the second-last block on the workspace (for example block number 4). When the block is released, the status is flipped again...

**To Reproduce**

- Set the maxInstances option on one of the blocks in the toolbox, for example to 5
- Then drag around the 4th block around on the workspace

**Expected behavior**

The block in the toolbox should not temporarily receive the 'blocklyDisabled' status while dragging around the second-last block around on the workspace.

**Desktop (please complete the following information):**

 - OS: iOS
 - Browser: chrome
 - Version: 91.0.4472.114

**Comment by BeksOmega** [comment] 2021-08-16 13:43
Hi @kvanthienen ! Thank you for reporting this :D For core team: this is probably another insertion markers problem.

**Comment by alschmiedt** [comment] 2021-08-16 23:50
Confirmed that this is an insertion marker problem.

If anyone is interested in working on this issue, I believe the problem is coming from [getBlocksByType](https://github.com/google/blockly/blob/f94b1db85018b5a7261fa01f7d04cd5c8367fe2c/core/workspace.js#L257) inside of [remainingCapacityOfType](https://github.com/google/blockly/blob/f94b1db85018b5a7261fa01f7d04cd5c8367fe2c/core/workspace.js#L529). When we have a block picked up `getBlocksByType` is returning the number of blocks + insertion markers.

Beka outlined a long term fix for this in #5375, however a short term fix would be to filter out the insertion markers in `getBlocksByType`. This would be a breaking change since it changes a public API.

**Comment by Apoorvgarg-creator** [comment] 2021-08-25 08:09
@BeksOmega If it's okay can I work on this issue as well?

**Comment by BeksOmega** [comment] 2021-08-25 13:51
Sure thing @Apoorvgarg-creator ! Do you want me to unassign you from the other one?

**Comment by Apoorvgarg-creator** [comment] 2021-08-25 14:44
> Sure thing @Apoorvgarg-creator ! Do you want me to unassign you from the other one?

I am experimenting things on that issue, trying to figure out the cause, have found some problematic things, working on that as well.
So if possible, I would like to work on both.

**Comment by Apoorvgarg-creator** [comment] 2021-08-28 04:05
@BeksOmega Thank you for helping me out.

**Comment by Apoorvgarg-creator** [comment] 2021-09-06 02:55
The below Image shows whenever we drag a element `this.typedBlocksDB_[type].slice(0);` --> `Arrays(value)`, This value is 
one greater than actual value. I think to solve the issue this should happened only on the case when we know this can be last block to place. In this case, It is 3.

Screenshot of console :
<img width="445" alt="Screenshot 2021-09-06 at 8 09 12 AM" src="https://user-images.githubusercontent.com/57873504/132152917-0a85bd1c-e22a-4797-b67c-4de95508bd8b.png">

**Comment by Apoorvgarg-creator** [comment] 2021-09-06 03:27
**Expected behaviour achieved -**

https://user-images.githubusercontent.com/57873504/132156519-8a06f96c-7e8f-49dd-a840-3e1e2fd6173e.mov

**Closed** 2021-09-27 15:42 UTC
Labels: type: bug, help wanted

**Comment by kvanthienen** [comment] 2021-09-30 14:52
Thank you all!
