### ISSUE TITLE
Blockly background is always black in latest Edge (41) when there is a non-zero number of blocks present

### ISSUE THREAD

**Issue by timdawborn** [google/blockly#1484] opened 2017-11-26 22:36 UTC
E.g. visit the Blockly homepage in latest Edge (41.16299.15.0):

![screen shot 2017-11-27 at 09 14 49](https://user-images.githubusercontent.com/812019/33244902-b12b7afc-d353-11e7-863b-2bffd3dee6eb.png)

This happens on the Google developers Blockly homepage as well as our (Grok Learning) Blockly instance.

This appears to be caused by the `fill: url(#blocklyGridPattern<number>)` on `blocklyMainBackground`:

![screen shot 2017-11-27 at 09 23 52](https://user-images.githubusercontent.com/812019/33245037-2d263e42-d356-11e7-809f-123fb6d2122b.png)

Overwriting this pattern fill and replacing it with `fill: white` causes the black to go away:

![screen shot 2017-11-27 at 09 24 03](https://user-images.githubusercontent.com/812019/33245044-4ad69f40-d356-11e7-90fe-e0fab050b5e5.png)

As for what is wrong with the existing pattern fill, I have no idea :) Quite possibly an Edge bug given this doesn't affect earlier versions of Edge? I did a brief bit of searching online for such a documented Edge bug and I couldn't find anything though. I don't believe this has been caused by a recent change to Blockly as our Blockly fork is a couple of months behind `develop` and is also affected by this issue in latest Edge, which reaffirms my theory it's possibly an Edge bug.

#865 is possibly related to this.

**Comment by rachel-fenichel** [comment] 2017-11-29 19:58
@microsoftsam any tips for tracking down whether this is a new Edge bug?

**Comment by microsoftsam** [comment] 2017-12-05 00:51
Yeah looks like an Edge 16 bug. Only repro's when the grid is not set or the grid spacing / length is 0. so appears as if Edge 16 does not handle an empty grid pattern as transparent, and rather as black. 

This be fixed by adding a line inside of the grid definition but set no stroke when a grid is empty, ie: 
in grid.js: 
```
if (gridOptions['length'] > 0 && gridOptions['spacing'] > 0) {
    Blockly.utils.createSvgElement('line',
        {'stroke': gridOptions['colour']}, gridPattern);
    if (gridOptions['length'] > 1) {
      Blockly.utils.createSvgElement('line',
          {'stroke': gridOptions['colour']}, gridPattern);
    }
    // x1, y1, x1, x2 properties will be set later in update.
  } else {
    // Edge 16 doesn't handle empty patterns
    Blockly.utils.createSvgElement('line', {}, gridPattern);
  }
```

**Comment by microsoftsam** [comment] 2017-12-05 01:10
(I filed an Edge bug for this)

**Comment by Bohdan-Tereta** [comment] 2017-12-15 20:56
See my comment in similar issue, maybe that can help:  https://github.com/google/blockly/issues/865#issuecomment-352108057.

The problem is probably in how Edge processes svg style urls. 
Also, read this topic for more info.

**Comment by timdawborn** [comment] 2018-03-26 07:15
FYI: this now happens for all Blockly instances, not just ones a non-zero number of blocks.

**Comment by rachel-fenichel** [comment] 2018-03-27 23:26
Sorry, this slipped through the cracks.  Here's a [PR](https://github.com/google/blockly/pull/1738) with Sam's fix.  Tim, can you verify it on Edge?

**Comment by timdawborn** [comment] 2018-03-27 23:58
Confirmed

**Closed** 2018-03-28 17:39 UTC
Labels: affects: browser, type: bug
