### ISSUE TITLE
Demos / Blockly Factory fails to import library

### ISSUE THREAD

**Issue by cshotton** [google/blockly#629] opened 2016-09-19 18:29 UTC
Importing a previously saved library fails in the Blockly Factory app. The code fails with an exception:

`TypeError: Cannot read property 'selectNodes' of undefined`

in line 184 of [app_controller.js](https://github.com/google/blockly/blob/master/demos/blocklyfactory/app_controller.js#L184)

Regression: load the Blockly Factory app, create a single block, save the block, download block library, attempt to re-import block library file.

This was using latest Google Chrome with  --allow-file-access-from-files specified and the index.html file loaded from the file system.

**Comment by rachel-fenichel** [comment] 2016-09-19 19:50
@quachtina96 @evd2014

**Comment by picklesrus** [comment] 2016-09-19 19:55
Do you have the repo checked out and run it off of file://?

I *think* the issue might be that you don't have closure, but I haven't deleted mine to check if I have the same issue yet.  We probably should be showing a message and pointing you to this page like we do when the playground detects you don't have closure: https://developers.google.com/blockly/guides/modify/web/closure

Or do you already have closure?

**Comment by picklesrus** [comment] 2016-09-20 00:55
I confirmed I run into errors if I remove my local copy of closure because blocklyfactory references a closure file here: https://github.com/google/blockly/blob/develop/demos/blocklyfactory/index.html#L20

I'll look into building the deps into the demo, but in the meantime you can get a copy of closure as described here: https://developers.google.com/blockly/guides/modify/web/closure or try using the demo we have hosted here: https://developers.google.com/blockly/guides/modify/web/closure

**Comment by cshotton** [comment] 2016-09-21 18:58
I'll give it a shot and report back. Thanks for the quick response!

**Comment by picklesrus** [comment] 2016-09-26 15:01
I'm going to keep it open. We should either package the library functions up properly, avoid using them, or at least show a message that points you to how to work around it when you're working off of the file: url.  I'll close it once we do one of those things :)

**Comment by picklesrus** [comment] 2016-10-04 23:28
I submitted #669 to develop to warn about the missing dependency and filed #668 to track removing the closure dependency so closing this one.

**Closed by picklesrus** 2016-10-04 23:28 UTC
Labels: blocklyfactory

**Comment by bhar937** [comment] 2019-05-14 23:57
Hello Guys,

I am receiving "Error: Closure not found.  Read this:https://developers.google.com/blockly/hacking/closure", when I try to run the "Build.py" file. Kindly advise on how to fix this.

**Comment by RoboErikG** [comment] 2019-05-15 16:14
Please go to the link and read it.

**Comment by bhar937** [comment] 2019-05-15 18:38
I have followed up the instructions mentioned on the site but it still gives me the same error.

I would appreciate any advice on how to get this working.

**Comment by RoboErikG** [comment] 2019-05-15 19:18
Could you please make a post on [the forum](https://groups.google.com/forum/?pli=1#!forum/blockly) with details about what OS you're on and a screenshot of your development directory (showing Blockly and the closure library)? It's probably a naming issue or the folder's at the wrong level, but it'll be easier to discuss and debug on the forums.
