### ISSUE TITLE
Keyboard Shortcut Documentation

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#6163] opened 2022-05-13 17:42 UTC
**Where**
In the "Configure Blockly" section of the [developers page](https://developers.google.com/blockly).

**What**
Probably something similar to the shortcut [documentation in the keyboard navigation codelab](https://blocklycodelabs.dev/codelabs/keyboard-navigation/index.html?index=..%2F..index#7).

- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

**Suggested content**

**Additional context**
I added brief documentation for shortcuts in the keyboard navigation codelab, but we should probably expand on it in the developer guides page.

**Comment by gonfunko** [comment] 2024-11-15 22:11
Duplicate of #4994

**Closed by gonfunko** 2024-11-15 22:11 UTC
Labels: issue: docs
