### ISSUE TITLE
Make a single field uneditable without making the whole block uneditable

### ISSUE THREAD

**Issue by Tereshka** [google/blockly#2763] opened 2019-08-01 08:52 UTC
**Is your feature request related to a problem? Please describe.**

Need an opportunity to make a single field uneditable without making the whole block uneditable

**Describe the solution you'd like**
There was a topic in Blockly developers group with solution:
[https://groups.google.com/d/msg/blockly/OiUL3gzGATQ/WUadyexeBwAJ](https://groups.google.com/d/msg/blockly/OiUL3gzGATQ/WUadyexeBwAJ)

**Additional context**

It will be great to have an implementation of above solution in blockly core itself.

**Comment by BeksOmega** [comment] 2021-07-06 14:30
Closing as a dupe of #4932 as that one has more detail.

**Closed by BeksOmega** 2021-07-06 14:30 UTC
Labels: component: fields, type: feature request
