### ISSUE TITLE
FieldAngle calls angleValidator function, actual function is named classValidator

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#486] opened 2016-07-20 16:50 UTC
FieldAngle is broken (at least in block Factory) - with this error:

Uncaught TypeError: Blockly.FieldAngle.angleValidator is not a function

In field_angle.js, line 208 should have the function call changed from 

Blockly.FieldAngle.angleValidator  (which is not defined)

to

Blockly.FieldAngle.classValidator  (which is defined).  Making this change seems to make the FieldAngle work fine for me again.

**Comment by RoboErikG** [comment] 2016-07-20 17:01
The current code has "this.callValidator" at 208. It looks like the compressed version being used by the Block Factory is out of date.

**Comment by picklesrus** [comment] 2016-07-20 21:58
Yeah, the blockly_compressed does seem out of date or there's a dependency problem. I tried building, though that doesn't seem to fix it.  I will figure out why, but as a temporary workaround @yoderjen, you can change the file included at the top of index.html to blockly_uncompressed.js instead of blockly_compressed.js

**Comment by picklesrus** [comment] 2016-07-20 22:26
Looks like there might be two things broken here. I need to fix #485 first so I can then make the FieldAngle change.  That workaround I mentioned is probably kind of useless. Sorry about that.

**Comment by picklesrus** [comment] 2016-07-20 23:01
I submitted #487 to the develop branch and recompiled. Now I can't reproduce the FieldAngle error in block factory anymore. Can you?

**Comment by picklesrus** [comment] 2016-07-21 23:18
I think this is fixed on both master and develop - blockly_compressed.js has been regenerated.

**Closed by picklesrus** 2016-07-21 23:18 UTC
