### ISSUE TITLE
Shadow block dropdown gets color of parent category

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#7416] opened 2023-08-20 11:11 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If a shadow block has a dropdown, it gets the color of the parent category, instead of the color of the block own category.

### Reproduction steps

1. Run `npm run start` and click the `Advanced playground` link to go to the advanced playground..
1. Load the following JSON into the playground:
```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_whileUntil",
        "inputs": {
          "BOOL": {
            "shadow": {
              "type": "logic_boolean"
            }
          }
        }
      }
    ]
  }
}
```
3. Click on the dropdown block.
4. Observe how the dropdown has the color of the parent.

### Screenshots

Tested on https://www.supercodingball.com/code/offline/do-nothing:

https://github.com/google/blockly/assets/7261426/6300537c-7df8-453a-89aa-c71378838339

### Browsers

Chrome desktop

## To Fix

1) Run the reproduction steps to make sure you can reproduce the problem.
2) Modify the `showEditor_` method in the `FieldDropdown` to always show the current block color (instead of showing the parent colour when the block is a shadow).
3) Rerun the reproduction steps and make sure you can't reproduce the problem..

**Comment by BeksOmega** [comment] 2023-08-21 15:39
Related to https://github.com/google/blockly-samples/issues/252

**Comment by laurensvalk** [comment] 2023-08-23 18:10
Just adding a note that some builds may depend on the current behavior, at least in part.

It would be awesome if there was a config option (or renderer constant) to say whether shadow blocks should inherit the parent category styles or not. (Including dropdowns, fixing this issue in the process)

For example, it is not uncommon for blocks in different categories to have a `text` shadow block on various inputs. If I understand correctly, the way to do it currently is make multiple `text` block types, each with its own color. A custom renderer works for the most part, but still requires monkey-patching the borderrect of input fields.

I'll see if I can prepare a pull request to add a `SHADOW_BLOCKS_USE_PARENT_STYLE = false` option, if you think this makes sense.

**Comment by laurensvalk** [comment] 2023-08-23 18:27
The current behavior was added here https://github.com/google/blockly/commit/b038c1cef573c57882547c07cdec02acec08c3b4#diff-8bc430f306f183ee3e55aa995c55063f906fe1ac043571db11d15b67566c3012, and seems like it might be intentional.

**Comment by maribethb** [comment] 2023-08-23 20:46
@laurensvalk Thanks for reporting! Adding that option to the ConstantProvider class seems reasonable and we would take a PR adding it and updating the dropdown field to respect it. Thanks!

**Comment by clementcontet** [comment] 2023-08-24 08:10
Hi,

From what I understand, shadow blocks current implemention gets the color from parent block, because we though that shadow blocks were often math blocks, and did not have a strong "meaning", justifying their own color.

On the other hand, in my example, the shadow block has a strong meaning (position in the football field) and having a consistent color for position blocks is important for users.

So it would be great indeed to tell Blockly if we want blocks to inherit their parent color or not.

But I think this distinction should not be done based on the status of the block (regular vs shadow).
If we simply set all shadow blocks to inherit their parent color:
- shadow math blocks will get the parent color, but regular math blocks won't
- this would not allow apps to deal at the same time with "strong meaning" shadow blocks and "weak meaning" shadow blocks

So another idea: could we attach this option (```BLOCKS_USE_PARENT_STYLE```) to the category of the block instead?
This way we could set the "math" category as inheritable (for both shadow and regular blocks), but not my "positions" category.

**Comment by laurensvalk** [comment] 2023-08-24 08:18
Can you elaborate on strong/weak shadow blocks? I'm not sure I'm familiar with that distinction.

Would it work in your case to make the positions block not a shadow block, but non-movable and non-deletable instead? By nature of having a different color, maybe it doesn't need the darker shade to distinguish?

To keep things small, I think I'll start with the option at the constant provider level (and fix the original reported issue).

**Comment by laurensvalk** [comment] 2023-08-24 09:15
> @laurensvalk Thanks for reporting! Adding that option to the ConstantProvider class seems reasonable and we would take a PR adding it and updating the dropdown field to respect it. Thanks!

I started on this, with e.g. the dropdown fix below. It's not so bad for this one, but this is going to touch quite a bit of code if doing it like this everywhere (`borderRect` stroke, `PathObject` fill, etc.). Happy to keep going but I can imagine this is not great.

Would it make sense to add the shadow check to `BlockSvg.getColourSecondary` (and friends) instead, and in the fields call these instead of accessing `this.style.colourSecondary` directly? (Although maybe the block isn't available everywhere, like in `PathObject.updateShadow_`, so maybe also not the solution.) Or maybe a getter for the `style` object that takes the shadow state into account.

```diff
diff --git a/core/field_dropdown.ts b/core/field_dropdown.ts
index 0390a1031..9bb0cd837 100644
--- a/core/field_dropdown.ts
+++ b/core/field_dropdown.ts
@@ -279,13 +279,13 @@ export class FieldDropdown extends Field<string> {
     dom.addClass(menuElement, 'blocklyDropdownMenu');
 
     if (this.getConstants()!.FIELD_DROPDOWN_COLOURED_DIV) {
-      const primaryColour = block.isShadow()
-        ? block.getParent()!.getColour()
-        : block.getColour();
-      const borderColour = block.isShadow()
-        ? (block.getParent() as BlockSvg).style.colourTertiary
-        : (this.sourceBlock_ as BlockSvg).style.colourTertiary;
-      dropDownDiv.setColour(primaryColour, borderColour);
+      // On shadow blocks, optionally use parent style for dropdown.
+      const colorSource =
+        block.isShadow() && this.getConstants()!.SHADOW_BLOCKS_USE_PARENT_STYLE
+          ? block.getParent()
+          : block;
+      const style = (colorSource as BlockSvg).style;
+      dropDownDiv.setColour(style.colourPrimary, style.colourTertiary);
     }
```
![image](https://github.com/google/blockly/assets/12326241/2d4a5e5e-1577-4e30-89e4-a1f250a8f9de)

**Comment by clementcontet** [comment] 2023-08-24 09:32
Hi,

> Can you elaborate on strong/weak shadow blocks? I'm not sure I'm familiar with that distinction.

By "strong" blocks, I meant blocks that represent a real concept in the app: in my game, a position on the football field.
And it is important to my audience (10+ kids) that all positions are represented by the same color (pink).

On the contrary, a "weak" block (which I don't use in the game), would be a technical category that does not represent an actual concept (like the number 10 in a "repeat 10 times" block).

With this distinction, strong blocks should have their own color whereas weak blocks should inherit from their parent (if any).
And I think we can't distinguish strong/weak blocks based on their status (regular vs shadow) but more based on their category  (math/position/etc.)

> Would it work in your case to make the positions block not a shadow block, but non-movable and non-deletable instead? By nature of having a different color, maybe it doesn't need the darker shade to distinguish?

Hi, indeed I don't use the darker shades for shadows.

I just want my "default" blocks to be:
- not deletable => so that users always see what kind of block is needed, based on their color
- replacable, obviously

And I think only shadow blocks are at the same time replacable and not deletable?

Maybe it's easier to try directly: https://www.supercodingball.com/code/offline/1player-only

**Comment by laurensvalk** [comment] 2023-08-24 09:44
Thanks for clarifying! For what it's worth, the Zelos number shadow block does not show any base color, so this case might not be the biggest hurdle here.

If I understand correctly, the proposed approach would work for your app then by setting `BLOCKS_USE_PARENT_STYLE` to `false` (the default).

**Comment by Aradhya04** [comment] 2023-09-22 17:23
Can you assign this to me

**Comment by laurensvalk** [comment] 2023-09-22 17:28
For what it’s worth, a fix for the issue is already posted above, but this is awaiting some feedback on how to best add the config option.

**Comment by rachel-fenichel** [comment] 2023-10-18 21:01
@BeksOmega can you take a look at the proposal above and give feedback on it?

**Comment by BeksOmega** [comment] 2023-10-18 23:59
> Just adding a note that some builds may depend on the current behavior, at least in part.

I'm not sure that I agree with this. Dropdown shadow blocks always have a display color, even when they're a "full block field". So I don't see why it would be desirable for them to match the color of their parent.

```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_whileUntil",
        "fields": {
          "MODE": "WHILE"
        },
        "inputs": {
          "BOOL": {
            "shadow": {
              "type": "logic_boolean",
              "fields": {
                "BOOL": "TRUE"
              }
            }
          }
        }
      }
    ]
  }
}
```
![image](https://github.com/google/blockly/assets/25440652/6b9654da-ac71-49f5-9063-9a104267a09d)

![image](https://github.com/google/blockly/assets/25440652/8109af40-43c0-43ed-bc8b-17742423c123)

I think it makes sense for the dropdown to just display the color of the block, and not look at the parent (even if it's a shadow). Do you know of a usecase where it's important for the dropdown to mirror the parent @laurensvalk ?

**Comment by laurensvalk** [comment] 2023-10-19 06:33
Thanks for your response!

> Do you know of a usecase where it's important for the dropdown to mirror the parent @laurensvalk ?

A generic use case is perhaps where applications rely on shadow blocks for most inputs, as opposed to fields.

For example, say there is a "Port" parameter that is used across several block categories, like "motors" and "sensors":

![image](https://github.com/google/blockly/assets/12326241/05bdb2c1-832f-45c5-a6ec-0ede8c6c091c)

I originally made two separate Port blocks just to get these styles, but have since extended and partially monkeypatched parts of the renderer to achieve this result with a single block definition.

----------

This is also appears to be used in various Scratch derivatives. The following is from the official Scratch page, for example:

![image](https://github.com/google/blockly/assets/12326241/40cac216-bd34-42fc-9ea7-b2ac1910e742)

(Not sure how this one is implemented under the hood, but shadow blocks with inherited parent color could achieve a similar look).

--------------

An example closer to Blockly is any shadow text field. I suppose it is debatable which color the text input should have. I'm going with the parent block :smile: 

![image](https://github.com/google/blockly/assets/12326241/2fa682d7-a773-48cd-a7b1-b3adcc2db07d)

**Comment by BeksOmega** [comment] 2023-10-19 15:02
Hmm ok this is interesting! You're not just changing the color of the shadow block's dropdown, you're also changing the color of the shadow block itself. Right now in core we're just changing the dropdown div.

So if you're already changing the color of the shadow block to match the parent, making the dropdown div match the shadow block itself instead of the parent should maintain the same behavior for you.

Does that sound correct @laurensvalk ?

**Comment by BeksOmega** [comment] 2023-10-23 17:14
Ok I added fix instructions to this issue so that dropdowns will always match the color of the given block.

And I separated out the shadow blocks matching parents question into a separate issue: https://github.com/google/blockly/issues/7607

TL:DR, I don't really like the idea of adding another constant, because I think it breaks separation of responsibility and isn't super sustainable. I think we should see if we can migrate to using CSS for themes if possible, but I still need to dig into this.

**Comment by Apoorvgarg-creator** [comment] 2023-10-31 10:59
Hey, @BeksOmega Can I take this issue ?

**Comment by BeksOmega** [comment] 2023-10-31 15:30
Go for it @Apoorvgarg-creator =)

**Comment by Apoorvgarg-creator** [comment] 2023-11-01 17:44
@BeksOmega How to load code in advanced Playground ?

**Comment by BeksOmega** [comment] 2023-11-01 18:04
> @BeksOmega How to load code in advanced Playground ?

You can open the advanced playground using this link in the playground:

![image](https://github.com/google/blockly/assets/25440652/3979804c-7e83-4dbe-8564-97e09229c209)

Then you can paste the JSON into the JSON tab of the right side panel, right click and select "Import from JSON"

**Comment by Apoorvgarg-creator** [comment] 2023-11-01 18:12
Hey, Thanks a lot ! @BeksOmega, One more question, I read the conversation, and I believe if I do this, this will solve the issue 
**Modify the showEditor_ method in the FieldDropdown to always show the current block color (instead of showing the parent colour when the block is a shadow).**

**Comment by Apoorvgarg-creator** [comment] 2023-11-01 18:32
https://github.com/google/blockly/assets/57873504/d09c7f64-78db-4e2c-94f8-7534298553cd

**Comment by Apoorvgarg-creator** [comment] 2023-11-01 18:32
@BeksOmega I don't see the issue in this ?

**Comment by Apoorvgarg-creator** [comment] 2023-11-02 03:43
Thank you ! @BeksOmega

**Closed** 2023-11-02 15:31 UTC
Labels: issue: bug, good first issue
