### ISSUE TITLE
[Blockly Playground][RTL] When flyout is zoomed in at its maximum then it gets difficult to zoom out and the playground does not show up

### ISSUE THREAD

**Issue by PreethiBh** [google/blockly#4716] opened 2021-03-18 14:41 UTC
When flyout is zoomed in at its maximum then it gets difficult to zoom out and the playground does not show up

*Steps to reproduce the behavior:*

1. Go to 'http://google.github.io/blockly/tests/playground.html?dir=rtl&toolbox=simple'
2. Create blocks as in below screenshot in RTL
https://screenshot.googleplex.com/cAvO0mnFueP.png
3. Zoom in the flyout to its maximum

*Expected behavior*
After zooming the flyout to its maximum, user should be able to zoom out and also the playground should be visible even though the flyout is zoomed to its maximum.

*Screenshots*

![Screenshot 2021-03-18 8 11 11 PM](https://user-images.githubusercontent.com/72138408/111644721-1b1dba80-8826-11eb-8350-66a2372a192a.png)

Device : Chromebook
Browser : Chrome
Chrome Version : 88.0.4324.208

**Comment by alschmiedt** [comment] 2021-03-23 00:10
Closing as a dupe of #4715 since they have the same underlining problem.

**Closed by alschmiedt** 2021-03-23 00:10 UTC
Labels: triage, type: bug
