### ISSUE TITLE
Save XML and Save JSON not giving same response when code loaded by clicking Airstrike 

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5541] opened 2021-09-27 11:36 UTC
**Describe the bug**

Save XML and Save JSON not giving same response when code loaded by clicking Airstrike 

**To Reproduce**

1. Go to 'https://google.github.io/blockly/tests/playground.html'
2. Click on 'Airstrike' for 3 or 4 times and verify the workspace
3. Click on Save JSON and refresh the page
4. Click on Load . Verify that the workspace renders same blocks
5. Click on Save XML and repeat the steps
6. Click on Load and verify that blocks are hidden one below the other

**Expected behavior**

Save JSON and Save XML should render the original blocks

**Screenshots**

https://screencast.googleplex.com/cast/NjQ5NjE2MTQ4NzY1MDgxNnw1M2Q3OTRhMC1jNA

**Desktop (please complete the following information):**
 OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by BeksOmega** [comment] 2021-09-27 16:16
Thanks for finding this Divya :D I was able to reproduce this, and I think it might actually be a bug with the XML system, or at least an unintended behavior? The XML system uses `getTopBlocks(true)` which orders blocks from top to bottom, left to right (generally) while the JSON system uses `getTopBlocks(false)` which orders blocks based on the order in which they were added to the workspace.

Since the XML system is being iceboxed, and the JSON system specifically states that top-blocks are loaded in an arbitrary order, I don't know that it's worth changing this. But if you peoples do want the systems to be consistent, it's any easy fix =) Just flip the parameter of one system or the other.

**Comment by alschmiedt** [comment] 2021-09-28 16:35
I think the JSON system makes more sense than the XML system in this case, so I think we should leave it for now. I believe this only makes a noticeable difference when blocks are overlapping a lot and I don't think this is the case for the majority of projects. 

Closing this as WAI for now.

**Closed by alschmiedt** 2021-09-28 16:35 UTC
Labels: type: bug, triage
