### ISSUE TITLE
Typeahead Support for Blockly

### ISSUE THREAD

**Issue by Kashdog** [google/blockly#1583] opened 2018-02-01 20:19 UTC
### Problem statement

If you are using a drop down with many options it becomes cumbersome to scroll through all the options. For 50 items this would make it difficult for the user to select the right item.

### Proposed Solution

A way to solve this is to create a custom field. The text input field has an input field created by the goog.dom. You can configure the custom field to add onto the text input field by rendering a datalist tag with option tags under it. Add the following code to the text input field showInlineEditor function. Be sure to also add an option for array in the constructor and setting this.menuGenerator = to the array option.

```
  var datalist = goog.dom.createDom(goog.dom.TagName.DATALIST);
  for (var i=0; i < this.menuGenerator.length; i++) {
    var option = goog.dom.createDom(goog.dom.TagName.OPTION);
    option.setAttribute('value', this.menuGenerator[i][0])
    datalist.appendChild(option);
  }
  datalist.setAttribute('id', 'datalist');
  htmlInput.setAttribute('list', 'datalist');

  Blockly.FieldDatalist.htmlInput_ = htmlInput;
  div.appendChild(datalist);
  div.appendChild(htmlInput);

```

**Comment by SoranKhezri** [comment] 2019-10-24 14:00
Hi. Can you show me a complete demo? I don't understand very well.
Thanks

**Comment by mattbishop** [comment] 2019-10-24 15:03
👍

**Comment by RoboErikG** [comment] 2019-10-24 16:05
It would look very much like this feature in Google Sheets.

![typeToFilter](https://user-images.githubusercontent.com/11066279/67503983-75b8e400-f63d-11e9-9b1e-5d222d695977.gif)

**Comment by SoranKhezri** [comment] 2019-10-24 16:28
I know what is look like. But I want to see codes for that. Do you have a complete Demo with codes to see?

**Comment by RoboErikG** [comment] 2019-10-24 16:33
We haven't built it yet. This is the feature request to build it.

**Comment by SoranKhezri** [comment] 2019-10-24 17:16
Thanks for your reply. I think codes above this topic, shows completed feature.

**Comment by VitokoHK** [comment] 2020-03-31 10:43
Hey! Can you give an example on where to put the code and how to include this feature in a field in a block from Blockly? I'm trying to implement this and this seems the most promising thing out there! Thanks

**Comment by rachel-fenichel** [comment] 2020-04-01 21:56
Take a look at the [guide to extending an existing field](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/extending).

**Comment by ArbazSheikh** [comment] 2020-11-26 04:08
The solution works on some level but styling the datalist is not possible. Is there any other solution in which we can style the dropdown?

**Comment by BeksOmega** [comment] 2021-07-31 01:16
Dupe of https://github.com/google/blockly-samples/issues/199

**Closed by BeksOmega** 2021-07-31 01:16 UTC
Labels: component: library blocks, type: feature request
