### ISSUE TITLE
The Import Block Library is not working on Blockly Developer tools

### ISSUE THREAD

**Issue by PlabanP1** [google/blockly#7198] opened 2023-06-23 05:23 UTC
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

As per expectation, when the user clicks the Import Block library button,  the user can select a saved block library to import and the blocks to be displayed. 

In this case, the blocks don't get loaded on the screen.

https://screencast.googleplex.com/cast/NDY1NjQ2OTA1MzAxNDAxNnxmMTM0ZTEyZC1jMQ

### Reproduction steps

1. 
2. 
3.

### Browsers

Chrome desktop

**Comment by cpcallen** [comment] 2023-06-23 19:33
Hi Plaban.  Is this test case 1.4.9?  I had a quick check and after clicking "Download Block Library" to download `library.xml` I was able to click Clear Library then Import Block Library and successfully imported `library.xml` again.

I know there are some issues with importing JSON block definitions on the Workspace Factory tab using the Import Custom Blocks button—see #697, #5570, #6043 (which I think are all the same issue)—but if this issue is different then we need a bit more information about how to reproduce it.

Assigning this back to you for now; please assign to me once you've responded.

**Comment by PlabanP** [comment] 2023-06-28 04:40
Hi Christopher,

I am following the same process as you have mentioned above. But the imported library doesn't load the associated blocks.

Screencast to explain the issue: https://screencast.googleplex.com/cast/NTM4NzMwNDUxMzMwNjYyNHwzMTAxYTJmMS1iZA

**Comment by cpcallen** [comment] 2023-06-28 15:57
Hi @PlabanP,

Have you watched either of the screencasts you posted?  They seem to be incomplete, because I do not see you downloading or importing anything, nor do I see any errors.  I see only that you create a block, and then point at some buttons (I guess you clicked them, but that is not shown, and I do not see any dialog boxes), then show that the block you created is still visible in the block library menu.  Everything appears to be working as expected.

**Comment by cpcallen** [comment] 2023-07-26 13:27
Hi @PlabanP,

I tried the steps you gave.

After the last step,

> 5. After i click on Ok in the dialog box, the imported block library doesn't get loaded.

I was able to access the block I'd created earlier by clicking on the "Block Library" button and selecting the block I'd made ("july26_blocktest") from the drop-down menu and then clicking "OK" after being warned about unsaved changes.

Are you not able to do that , or is it just that the instructions for this test are incomplete?

I'm going to close this as unreproducible for the moment, but please reopen if you can still reproduce.

**Comment by cpcallen** [comment] 2023-07-26 13:27
Unable to reproduce.

**Closed by cpcallen** 2023-07-26 13:27 UTC
Labels: issue: bug, component: devtools
