### ISSUE TITLE
After the block drag is completed, the mouse event is not released

### ISSUE THREAD

**Issue by tracer1023** [google/blockly#7877] opened 2024-02-21 02:03 UTC
Uploading bbb.mp4…

### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

On the pad side, when dragging a building block with one or two fingers, the problem of finger following the building block occasionally occurs.
It has been verified that the finger following problem will occur in both v10.3.1 and V10.4.1 versions.

https://github.com/google/blockly/assets/33512446/a32125b2-f0c6-40e6-95a0-d8b872e19a78

### Reproduction steps

1. Drag out blocks
2. Drag blocks with one or two fingers in a circular motion
3.Occasional finger following problem

### Stack trace
The console did not report an error when the finger following problem occurred
```shell

```

### Browsers
mobile pad

**Comment by tracer1023** [comment] 2024-02-21 02:09
This demo is a demo written using the new version of blockly, which is basically the same as the demo on the official website.

https://github.com/google/blockly/assets/33512446/4e9854b8-e457-4aa7-92f6-dca95297889c

**Comment by maribethb** [comment] 2024-02-21 18:10
Hello @tracer1023 it looks like you opened a similar bug previously: https://github.com/google/blockly/issues/7807 but we had to close it without getting more information.

Unfortunately we are still not able to reproduce this on our touch devices. Can you provide any additional information, such as minimum reproducible example, browser info, etc?

**Comment by tracer1023** [comment] 2024-02-22 03:42
Here is the minimal example code link，develop branch
https://github.com/tracer1023/blocklyDemo.git

You can use webview to open this code on the pad and drag it with one or two fingers in a circular motion, which may occasionally cause finger following problems.
![截图_20240222114143](https://github.com/google/blockly/assets/33512446/9820aacd-e6cd-40ae-b6ed-3179005ed7c3)

**Comment by tracer1023** [comment] 2024-02-22 05:59
When this problem occurs in version v10.4.2, a console error appears
![i飞图片_1708581439265](https://github.com/google/blockly/assets/33512446/00309851-e8c1-44ce-bfce-78b46c61b658)

**Comment by tracer1023** [comment] 2024-02-22 06:00
How to reproduce the problem

https://github.com/google/blockly/assets/33512446/e0033bdc-1e21-485e-b871-f8fd794198f7

**Comment by tracer1023** [comment] 2024-02-22 07:42
This problem is also reproduced on this website
https://blockly-demo.appspot.com/static/demos/code/index.html

https://github.com/google/blockly/assets/33512446/e8f47d19-c3b3-47c6-8b55-10bc1691c4a0

**Comment by tracer1023** [comment] 2024-02-26 01:56
> Hello @tracer1023 it looks like you opened a similar bug previously: #7807 but we had to close it without getting more information.
> 
> Unfortunately we are still not able to reproduce this on our touch devices. Can you provide any additional information, such as minimum reproducible example, browser info, etc?


Waiting for your reply!

**Comment by maribethb** [comment] 2024-03-06 21:49
Can you tell us what tablet you are using, and what version of which web browser you are using? Unfortunately we are still not able to reproduce this on our end but we will look into it.

Do you know if this only happens in Blockly v10.3 and above? Or can you try it with an older version of Blockly and let us know if this was a more recent regression? [Here's the code demo](https://3-1-dot-blockly-demo.appspot.com/static/demos/code/index.html) on version 9.3.1 of Blockly for example, if you could try that and let us know if you have the same behavior, that would be great! A stack trace from that version would also be useful if the problem does occur.

@BeksOmega does the error in the stack trace above look familiar / possible this was introduced by recent dragging changes?

**Comment by maribethb** [comment] 2024-03-27 20:35
Hi @tracer1023 have you had a chance to look at my last message? Unfortunately without your help I don't think our team will be able to solve this on our own since we can't reproduce it.

**Comment by maribethb** [comment] 2024-04-19 16:36
Hi @tracer1023 feel free to reopen this issue if you can provide the additional info requested above. Thanks!

**Closed by maribethb** 2024-04-19 16:36 UTC
Labels: issue: bug, issue: triage, needs more info
