### ISSUE TITLE
custom block support inline/external for each value input not as global settings

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7744] opened 2024-01-04 01:17 UTC
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Request
similar question:https://groups.google.com/g/blockly/c/os1ICD473wA
https://groups.google.com/g/blockly/c/Jvnq5A0zg3w
currently if we make a custom block,only could choose inline or external,I want to each value input could set it's input way(external or inline)
![Snipaste_2024-01-04_09-14-51](https://github.com/google/blockly/assets/42778/2ae96d4e-267c-4fe7-b144-e1073d6003c4)

**Comment by maribethb** [comment] 2024-01-04 20:11
Thanks for filing the issue. This is a duplicate of #216 . While we acknowledge this is a long-standing feature request, it's not something we plan to implement in the near future. You can follow that issue for any future updates.

**Closed by maribethb** 2024-01-04 20:11 UTC
Labels: issue: feature request, issue: triage
