### ISSUE TITLE
Make Generator.provideFunction_() @protected (and many others)

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1985] opened 2018-07-23 17:50 UTC
### Problem statement

Generator.provideFunction_() is currently marked `@private`, despite being use by non-core code. As such it is not documented in our reference. It is also useful for many generator authors and should become a standard `@protected` method.

### Expected Behavior

Generator authors should be able to find documentation on `provideFunction_()` and be expected to make use of it in their own code.

Looking further, `@protected` is not used anywhere in `generator.js`. There are probably several other methods that should be marked as such.

**Comment by BeksOmega** [comment] 2023-11-21 23:46
I'm going to say this is a dupe of #7326

**Closed by BeksOmega** 2023-11-21 23:46 UTC
Labels: type: cleanup, component: generators
