### ISSUE TITLE
ctrl+click does not open context menu in firefox on mac

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7979] opened 2024-03-29 23:20 UTC
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

The context menu should open when you either right-click the ws or when you hold ctrl and click on the workspace.

In firefox on mac, the former is working but not the latter

I'm wondering if this is a bug in firefox. I opened the inspector and set a breakpoint on the `pointerdown` event listener (through firefox's developer tools, not a specific line of blockly code). If you right click on the workspace, you hit this breakpoint. If you are holding ctrl, you do not. That points to it never being fired by the browser which is not something we can fix on our end. I found this bug was opened 6 years ago and is still open: https://bugzilla.mozilla.org/show_bug.cgi?id=1504210 but I find it curious nobody has reported this before.  [Edit: we do have a proposed fix; see comments below.]

Mark of App Inventor originally reported it and says it's only happening on specific versions of firefox

### Reproduction steps

1. Open https://blockly-demo.appspot.com/static/tests/playground.html in firefox on mac
2. Hold Ctrl key
3. Click on workspace

### Browsers

Firefox desktop

**Comment by maribethb** [comment] 2024-03-29 23:25
confirmed with this fiddle i found on the internet: https://jsfiddle.net/y8ot42pa/

ctrl+click in chrome yields pointerdown, ctrl+click in firefox does not (it does give a mousedown though)

**Comment by mark-friedman** [comment] 2024-04-02 21:49
Note that while  ctrl+click in firefox on Mac doesn't generate a "pointerdown" event it **does** generate a "contextmenu" browser event (as does on Chrome).  Consequently, I wonder if maybe Blockly  should consider using the "contextmenu" browser event  for context menu triggering rather than the "pointerdown" event. I think that that might also simplify Blockly's browser event handling a bit.

I am amazed that no one in the last 6 years or so has noticed this while using Blockly with Firefox on a Mac laptop!

**Comment by maribethb** [comment] 2024-04-03 20:54
This probably wasn't happening until we switched to pointer events, so not a full 6 years. But 2.

We'd be happy to accept a PR for that idea, Mark, but are unlikely to be able to prioritize a fix for this ourselves in the near future. As long as @BeksOmega says this is not going to collide with her current gesture work.

**Comment by BeksOmega** [comment] 2024-04-03 20:56
I think this might be a blocker for App Inventor @mark-friedman does any of the info Maribeth found change prioritization?

**Comment by mark-friedman** [comment] 2024-04-04 17:52
> I think this might be a blocker for App Inventor @mark-friedman does any of the info Maribeth found change prioritization?

@ewpatton Is doing some information gathering about this.

**Comment by mark-friedman** [comment] 2024-04-04 21:56
From @ewpatton: "I say it's probably not a show stopper but it is annoying that the current Blockly version we use in production doesn't have the problem.  So it is a regression in that sense."

**Comment by maribethb** [comment] 2024-04-26 17:11
Note that the linked PR doesn't work on Mac / Firefox still. Blake was testing on browserstack, but they do shenanigans with the meta/command/control key so testing isn't accurate. Reassigning to Neil since he has a native Mac to test with

**Comment by BeksOmega** [comment] 2024-07-15 20:36
Mmm I thought the issue was that we're listening for `pointerdown` events, which aren't being fired. It looks like their fix just fixes the inheritance chain without actually firing a `pointerdown` event? or am I reading it wrong?

**Comment by johnnesky** [comment] 2024-07-16 00:15
I've tried out Firefox Nightly now, and confirmed that the issue is fixed. I don't know exactly how they implemented it, but the pointerdown event seems to be firing as expected when control-clicking on things.

**Comment by BeksOmega** [comment] 2024-07-16 15:37
Sweetness, then I think you're right and we can close this :D Yay for other people fixing bugs!

**Closed by BeksOmega** 2024-07-16 15:37 UTC
Labels: issue: bug, help wanted
