### ISSUE TITLE
Apostrophe in tooltip in Blockly Factory 

### ISSUE THREAD

**Issue by JakubRuzicka** [google/blockly#1045] opened 2017-04-17 14:05 UTC
Hello, I found some issue with Blocky Factory. Webpage doesnt work after insert ' to Tooltip. After that can't export blocks and toolbox.
This issue can be solved with adding \ before every '.
Hope i help, have a nice day

**Comment by rachel-fenichel** [comment] 2017-05-05 00:59
Root cause: unescaped user input here: https://github.com/google/blockly/blob/master/demos/blockfactory/factory_utils.js#L355

**Comment by rachel-fenichel** [comment] 2017-05-20 00:07
Fixed by #1111

**Closed by rachel-fenichel** 2017-05-20 00:07 UTC
Labels: affects: develop, affects: master, component: devtools, help wanted, type: bug
