### ISSUE TITLE
Flyout buttons not right-aligned in RTL.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1424] opened 2017-11-03 23:53 UTC
<img width="331" alt="screen shot 2017-11-03 at 16 51 58" src="https://user-images.githubusercontent.com/250480/32399918-713ccb66-c0b7-11e7-9974-763c0ef3dd69.png">

**Comment by microsoftsam** [comment] 2017-11-03 23:58
Dupe of https://github.com/google/blockly/issues/1208

**Comment by rachel-fenichel** [comment] 2017-11-06 20:53
Closed as dupe.

**Closed by rachel-fenichel** 2017-11-06 20:53 UTC
Labels: affects: develop, affects: master
