### ISSUE TITLE
Blockly Developer Tools Test URL not loading with "Uncaught Range error:Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5538] opened 2021-09-27 05:01 UTC
**Describe the bug**

Blockly Developer Tools Test URL not loading with "Uncaught Range error:Maximum call stack size exceeded"

**To Reproduce**

1. Go to 'http://google.github.io/blockly/demos/blockfactory/index.html'
2. Check the console error

**Expected behavior**

Page should be loaded successfully

**Screenshots**
![Screenshot 2021-09-27 10 25 13 AM](https://user-images.githubusercontent.com/56336353/134847605-df4af4d5-0ec5-4fdc-b019-2eca50b0d4d1.png)

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [chrome]
 - Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by MNSDivya** [comment] 2021-09-27 16:20
![image](https://user-images.githubusercontent.com/56336353/134947218-1a0a67af-2d2e-43fb-a7e8-f838aefe481e.png)
Same issue observed in "https://google.github.io/blockly/demos/code/index.html"

**Comment by alschmiedt** [comment] 2021-09-27 21:39
This has been fixed in #5549 and all the testing sites have been updated.

**Closed by alschmiedt** 2021-09-27 21:39 UTC
Labels: type: bug

**Comment by MNSDivya** [comment] 2021-09-28 01:18
Verified that Blockly developer tools and Demo URL is loading successfully

**Comment by cpcallen** [comment] 2021-09-28 19:55
To follow up on this: the problem is being caused by the compiler conflating the `DIV` local variable with `exports.DIV`, because of the initialisation `exports.DIV = DIV`.  The result is that calling `getDiv` ends up (incorrectly) invoking the get accessor for `exports.DIV`, which in turn calls `getDiv`.

This appears to be a compiler bug; I have filed google/closure-compiler#3873—though I would not recommend one's breath for a fix…
