### ISSUE TITLE
Comment text disappears when the text exceeds the space in the bubble

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1690] opened 2018-03-06 21:30 UTC
### Problem statement

When the text contents of a comment exceeds the available area of the comment bubble, the text content will no longer render.

<img width="225" alt="screen shot 2018-03-06 at 1 23 33 pm" src="https://user-images.githubusercontent.com/9916202/37059216-b84301a2-2141-11e8-881d-6972569c6006.png">

Used this workspace XML:

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables></variables>
  <block type="math_arithmetic" x="238" y="313">
    <field name="OP">ADD</field>
    <comment pinned="true" h="58" w="157">words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words words</comment>
    <value name="A">
      <shadow type="math_number">
        <field name="NUM">1</field>
      </shadow>
    </value>
    <value name="B">
      <shadow type="math_number">
        <field name="NUM">1</field>
      </shadow>
    </value>
  </block>
</xml>
```

### Expected Behavior

The text contents should be always be visible, possibly scrolling.

### Actual Behavior

Text contents disappears. Sometimes the comment's yellow background becomes white; other times the text area disappears entirely, leaving the comment's purple bubble.

### Steps to Reproduce

1. Create a block.
2. Create a comment on the block. Open the comment.
3. Type a long comment into the block. Either longer than the bubble is, or shrink the bubble (with the resize handle) to a size that is too small.

### Operating System and Browser

 * Desktop Chrome
 * Desktop Firefox

**Comment by NeilFraser** [comment] 2018-03-07 00:59
Duplicate of issue #39 and issue #1382

**Closed by NeilFraser** 2018-03-07 00:59 UTC
Labels: affects: master, component: comments, type: bug

**Comment by NeilFraser** [comment] 2018-03-07 01:00
Also, I'm not able to recreate this issue on Firefox as stated here.  Chrome is definitely broken though.

**Comment by rachel-fenichel** [comment] 2018-03-07 16:31
@AnmAtAnm and @NeilFraser, which versions of Firefox and Chrome are you using?

**Comment by AnmAtAnm** [comment] 2018-03-07 19:16
Chrome 64.0.3282.186 on Mac
