### ISSUE TITLE
Blockly Developer Tools preview unavailable

### ISSUE THREAD

**Issue by PaulMing** [google/blockly#4768] opened 2021-04-09 14:22 UTC
![image](https://user-images.githubusercontent.com/40627394/114194234-da771400-9981-11eb-9d84-cf0733295d8b.png)

**Comment by PaulMing** [comment] 2021-04-12 07:53
Is there anyone in the maintenance

worry

**Comment by moniika** [comment] 2021-04-12 17:13
I am having trouble reproducing this error.
@PaulMing what browser and version are you seeing this issue? Also, could you share more details on what you did on the Block Factory before you got this error in the console (or if this error was present from when you first loaded the page)?

**Comment by PaulMing** [comment] 2021-04-14 13:29
It's solved, run_ prettify.js Failed to load.
It is stored on the CDN. The CDN server is unstable, which leads to the failure of accessing resources. Load a copy locally
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html
https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js
Thank you

**Comment by PaulMing** [comment] 2021-04-14 13:32
It's solved, run_ prettify.js Failed to load.
It is stored on the CDN. The CDN server is unstable, which leads to the failure of accessing resources. Load a copy locally
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html
https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js
Thank you @moniika

**Comment by maribethb** [comment] 2021-04-16 23:43
Hi, thanks for reporting. Since this looks like an intermittent issue with a dependency rather than a bug in the developer tools itself, I'm going to close this issue, but if it keeps happening, feel free to reopen. If this continues to be an issue, we may want to rethink our dependency situation for this demo, but so far it does not seem like an ongoing problem. Thanks!

**Closed by maribethb** 2021-04-16 23:43 UTC
Labels: needs more info, type: bug, type: regression

**Comment by summer1120** [comment] 2022-09-27 09:15
The run_prettify.js module won't load in network-constrained areas. want to place run_prettify.js locally.@maribethb
