### ISSUE TITLE
`workspaceToDom` does not include `variables`

### ISSUE THREAD

**Issue by KlemenDEV** [google/blockly#6738] opened 2023-01-05 17:27 UTC
**Describe the bug**

`workspaceToDom` does not include `variables`. When calling `workspaceToDom`, `variables` XML element containing global variables is not included.

**To Reproduce**

* Add some variables using `workspace.createVariable`
* Variables are visible in Blockly variable blocks
* Use `Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace, true))` to generate XML of Blockly setup
* `variables` XML element is not present, but was present with the same code configuration in version Q1 2022 Patch 2 (v8.0.2)

**Expected behavior**

`variables` XML element is not present in XML, but should be (used to be)

**Additional context**

Calling `Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace, true))` generates XML without variables.

Calling `Blockly.Xml.domToText(Blockly.Xml.variablesToDom(Blockly.Variables.allUsedVarModels(workspace)))` instead on the same location generates XML with list of variables properly.

**Comment by KlemenDEV** [comment] 2023-01-05 17:48
Seems redefining https://github.com/google/blockly/blob/29acad04d3123a6d4df176bf03f7fe5e0b2c0ac7/core/xml.ts#L40 in custom JS (just copying it into custom function) and calling that method fixes the problem, so maybe this function is not getting exported properly?

**Comment by KlemenDEV** [comment] 2023-01-05 18:44
> Could you retest `workspaceToDom` after dragging some variable blocks into the workspace?

I did this (get and set variable blocks) and no change.

`allUsedVarModels` does return variables XML as stated in *Additional context* section. In fact, calling a custom method having the same code as `Blockly.Xml.workspaceToDom` returns XML with variables, whereas calling `Blockly.Xml.workspaceToDom` directly does not return XML with variables. Blocks and comments export correctly.

**Comment by BeksOmega** [comment] 2023-01-05 18:52
Weird, I'm not able to reproduce this. Can you reproduce it on the hosted [playground](https://blockly-demo.appspot.com/static/tests/playground.html), or any of the hosted [demos](https://google.github.io/blockly-samples/)?

If not, could you provide a link to your website/code? Or even better, a link to a minimal example that reproduces the issue?

**Comment by KlemenDEV** [comment] 2023-01-05 19:14
Can one access workspace in playground console?

**Comment by KlemenDEV** [comment] 2023-01-05 19:16
Interestingly enough, it works on my minimal reproducible example.

We reference variables in custom blocks in custom dropdowns. What does a custom block need to do in order to properly communicate it is using a variable?

**Comment by BeksOmega** [comment] 2023-01-05 19:43
It should return any models it's using from a method called `getVarModels` =) See [here](https://github.com/google/blockly/blob/37ad8eed836e9823210cee7ceeffb51d79d08ee0/core/variables.ts#L51) for reference.

**Comment by KlemenDEV** [comment] 2023-01-05 19:46
This is probably the problem.

It is still strange this worked in Q1 2022 Patch 2 (v8.0.2)

It is even weirder it works if I duplicate code from variablesToDom and allUsedVarModels.

We will probably use workspace variables list getter in custom DOM assembly function so not sure if I should leave this issue open or consider it resolved

**Comment by BeksOmega** [comment] 2023-01-05 20:37
I'll leave this open until I have time to refile as a docs issue =) Thanks for reporting this @KlemenDEV !

**Comment by BeksOmega** [comment] 2023-01-12 00:05
Closing in favor of #6760

**Closed by BeksOmega** 2023-01-12 00:05 UTC
Labels: issue: triage
