### ISSUE TITLE
Use workspace scale to resize the a dropdown accordingly

### ISSUE THREAD

**Issue by microsoftsam** [google/blockly#1515] opened 2017-12-14 19:06 UTC
### Problem statement

I think this is more of a feature request, but it would be great if the FieldDropdown applied the workspace scale.

### Expected Behavior

As you zoom in/out, a FieldDropdown's dropdown gets bigger and smaller accordingly.

### Actual Behavior

Static size for the dropdown.

### Additional Information

N/A

**Comment by rachel-fenichel** [comment] 2017-12-28 23:36
The dropdown menu and the context menu are both instances of `goog.ui.Menu`.  They live outside of the Blockly SVG, which is why they don't scale with the rest of Blockly.

Scale would need to be set in [position_](https://github.com/google/blockly/blob/master/core/contextmenu.js#L120) for the context menu and [positionMenu_](https://github.com/google/blockly/blob/master/core/field_dropdown.js#L238) for the dropdown.

**Comment by rachel-fenichel** [comment] 2017-12-28 23:56
Actually, this is a dupe of https://github.com/google/blockly/issues/1335 so I'll move the previous comment over to there and close this one.

**Closed by rachel-fenichel** 2017-12-28 23:56 UTC
Labels: affects: develop, affects: master, help wanted, low priority, type: feature request
