### ISSUE TITLE
Code demo: Switching tabs with the toolbox open leads to funny sized blocks

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1440] opened 2017-11-14 19:33 UTC
### Problem statement

Blocks shrink size when switching tabs in the code demo with the toolbox open in Safari. Chrome is fine.
- [x] Bug report
- [ ] Feature request

To Reproduce:
1. Open [code demo](https://blockly-demo.appspot.com/static/demos/code/index.html)
2. Open toolbox category (but don't close it)
3. click one of the language tabs (e.g. XML)
4. Click back to the blocks tab.  The blocks shrink. See attached screenshot.

![screen shot 2017-11-14 at 11 11 44 am](https://user-images.githubusercontent.com/15675877/32800423-1cb01ca8-c92f-11e7-9122-0b6cb401f421.png)

- [x] Desktop:
  - [ ] Chrome
  - [ ] Firefox
  - [x] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

**Comment by JarbasAl** [comment] 2018-06-13 22:33
also happens in firefox 52.8.1 (32-bit)

**Comment by AnmAtAnm** [comment] 2018-06-13 22:58
I'm not able to reproduce this in Safari v11.1.1 (13605.2.8) or Mac Firefox 60.0.1 or 60.0.2 (64-bit).

Firefox 52 was released on 2016-09-20 (with 53 two months later). It is currently taking 1.39% of the (desktop?) browser marketshare ([stetic.com](https://www.stetic.com/market-share/browser/)). It is not clear to me why there are more Firefox 52 users than 53-59 (webcrawler scripts?).

**Comment by AnmAtAnm** [comment] 2018-06-13 23:01
Oh... "Firefox version 52 will be the last complete update for Windows XP and Windows Vista. Security updates will be released, but no new features." ([mozilla.org](https://support.mozilla.org/en-US/kb/end-support-windows-xp-and-vista))

**Comment by MNSDivya** [comment] 2020-03-24 13:34
Worked fine in chrome,firefox,IE and Edge browsers.
Unable to verify on safari browser.

**Comment by BeksOmega** [comment] 2023-11-21 23:05
I think this is a measurement problem related to the order of measuring/rendering. Should no longer be an issue with the new render management system.

**Closed by BeksOmega** 2023-11-21 23:05 UTC
Labels: issue: bug, component: browser, component: toolbox/flyout, low priority
