### ISSUE TITLE
Toolbox categories scale when zooming

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#4047] opened 2020-07-14 20:51 UTC
Hello guys!

I would like to know if there's any way to prevent categories toolbox blocks from following the workspace zoom.Today, the blocks on the categories follows the main workspace zoom, getting extremely big or annoying small (see images below). That behavior is unlikeful on most situations, and i'm trying to figure out a way so the toolbox blocks maintain its original scale (the original scale being '1').

[Here's](https://i.imgur.com/l8HG32m.png) a picture of it
[Here's](https://imgur.com/a/ojQmFC2) a picture of what I trying to do so, i've been able to manage this result by applying 'transform: scale(1)' on 'blocklyBlockCanvas' CSS class, but with it the scroll on toolbox categories with many blocks just stopped working out, because of the transform: translate()' property beeing overlapped

**Comment by rachel-fenichel** [comment] 2020-07-16 16:22
Closing as a duplicate of #4038 

There is not currently a way to do this, but we have it as a feature request.

**Closed** 2020-07-16 16:23 UTC
