### ISSUE TITLE
The trash can layer

### ISSUE THREAD

**Issue by LionKenedi95** [google/blockly#5876] opened 2022-01-14 07:26 UTC
I believe controls should always be above any other canvas elements. It looks very strange that the blocks are above the trash can and only when d&d starts the trash can comes to the fore.
In the screenshot below, an example: all controls are above the blocks, but the basket is not :)

![image](https://user-images.githubusercontent.com/21295479/149466611-f188b282-151c-423d-a100-5e4c2461b96c.png)

I suggest moving the trash can to the same level as the zoom in and out buttons.

If there is a reason why the wastebasket is located exactly as it is now, please write why :)

**Comment by BeksOmega** [comment] 2022-01-14 13:04
Hi, thanks for filing this issue! I think we might want the trashcan to be behind the blocks when dragging so that it looks like the blocks are going "into" the trashcan. (This is how it works right now, the block just becomes slighty transparent, so you can also see the trashcan behind it.) But I definitely agree that it looks weird when the blocks aren't dragging.

Also related to #1188.

**Comment by rachel-fenichel** [comment] 2022-10-19 20:38
Closing because this is intended behaviour.

**Closed by rachel-fenichel** 2022-10-19 20:38 UTC
Labels: low priority, component: rendering
