### ISSUE TITLE
Editor on blockly website isn't working

### ISSUE THREAD

**Issue by yandod** [google/blockly#6609] opened 2022-11-09 04:30 UTC
**Describe the bug**

the editor on blockly website isn't working no matter language options.

**To Reproduce**

1. Go to 'https://developers.google.com/blockly'
2. Click on 'language'

**Expected behavior**

Editor shows blocks and accept user operation/

**Screenshots**
<img width="1298" alt="スクリーンショット 2022-11-09 13 25 28" src="https://user-images.githubusercontent.com/103903/200738910-a18c08c4-43d4-49e0-a6b8-d0b657553a81.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 107.0.5304.87（Official Build） （arm64）

**Comment by maribethb** [comment] 2022-11-10 01:14
Hey @yandod we can't reproduce this. Can you check if there are any errors in the console when this happens for you?

**Comment by yandod** [comment] 2022-11-10 04:15
Here is it.
and this looks suspecious
`xml.ts:449 Uncaught TypeError: Cannot read properties of null (reading 'childNodes')
    at Object.domToWorkspace$$module$build$src$core$xml [as domToWorkspace] (xml.ts:449:46)
    at blockly-demo:105:15`
<img width="1297" alt="スクリーンショット 2022-11-10 13 15 01" src="https://user-images.githubusercontent.com/103903/200999274-2b294ac1-3da9-4f73-be78-f2abbc77fa4a.png">

**Comment by yandod** [comment] 2022-11-10 04:17
testing with Safari just in case. same problem.
<img width="1373" alt="スクリーンショット 2022-11-10 13 16 26" src="https://user-images.githubusercontent.com/103903/200999397-4198d433-e472-4ea8-b562-46f428f328f5.png">

**Comment by yandod** [comment] 2022-11-10 04:22
Firefox 100.0.1

`Uncaught TypeError: a is null
    domToWorkspace$$module$build$src$core$xml xml.ts:449
    <anonymous> blockly-demo:105`

<img width="1269" alt="スクリーンショット 2022-11-10 13 19 23" src="https://user-images.githubusercontent.com/103903/200999762-2f44e03f-7aef-4a8a-82ae-536c5e2312d2.png">

**Comment by yandod** [comment] 2022-11-11 08:43
@BeksOmega  @maribethb I am seeing problem on those browsers which claim failure on xml.ts. was there anything I should try on my end?

**Comment by Zireael07** [comment] 2022-11-19 20:03
Same problem here on Vivaldi 5.5.2805.42 
Flood of errors that I can't figure out where things went wrong

**Comment by yandod** [comment] 2022-11-24 05:11
I suspect there was some issue on cache on CDN or webserver which make difference depends on where access from.
I see this from Japan.

**Comment by yandod** [comment] 2022-11-29 07:38
@Zireael07  @BeksOmega  Could you take a second look? we've seen error on xml.ts and blockly-demo.

**Comment by Zireael07** [comment] 2022-11-29 07:55
![image](https://user-images.githubusercontent.com/4525388/204471091-fde764b2-9cb9-4942-97a3-03f26adc8647.png)

**Comment by maribethb** [comment] 2022-12-01 00:04
As of 2 days ago this demo was updated to use unpkg CDN instead of an old location on app engine. Is anyone still seeing errors? If so could you please load the Network tab and share the URLs of what is giving a 404? Thanks!

**Comment by Zireael07** [comment] 2022-12-01 07:56
Ctrl+F5 (force refreshed, still seeing the same errors as above)

**Comment by NeilFraser** [comment] 2022-12-02 13:57
I also can't recreate this.  :(

Some notes:
* The `devsite-cyan.css` 404 is irrelevant to this bug and has been dealt with.
* The screenshots provided by @Zireael07 is a completely different issue which has been dealt with (all our compressed JS files disappeared for a few days).  I've hidden those specific comments since it's a known, resolved, unrelated issue.
* @yandod 's second screen shot clearly indicates that the XML block with the ID 'blocklyDefault' is not being found.  But this is difficult to explain since the definition and the getElementById are both in the same static file.  The fact that this is a cross-browser issue makes this even more difficult to explain.

As @maribethb mentioned, there was a bunch of work done on this page in the past few days for unrelated reasons.  Maybe those changes have inadvertently resolved this issue?  If not, then I think the next step is to convert the `defaultBlocks` from  XML to JSON.  So does anyone still see this issue?

**Comment by yandod** [comment] 2022-12-06 03:56
Hi, I still see problem on my end. and the error looks slightly different from before. it might be because of new deployment which @maribethb  mentioned.
There could be issue on asset generation or deployment.

> Uncaught ReferenceError: Blockly is not defined
    at blockly-demo:102:19

<img width="1746" alt="スクリーンショット 2022-12-06 12 54 19" src="https://user-images.githubusercontent.com/103903/205809038-4aa4ee5a-ceb3-4ee2-9bd5-e56ebeb7adb3.png">

**Comment by yandod** [comment] 2022-12-06 04:00
This is content of "blockly-demo" I retrieve from my devtool.
I could see Japanese strings even in this js file.  is this expected?

https://gist.github.com/yandod/afd531ef26567434592ce4ab531a301f

**Comment by yandod** [comment] 2022-12-06 04:04
There is bunch of js files fall to 404 because of still referring AppEngine location?

<img width="1737" alt="スクリーンショット 2022-12-06 13 03 30" src="https://user-images.githubusercontent.com/103903/205810457-f9075584-20c4-4766-8d4b-d7359418277b.png">

**Comment by yandod** [comment] 2022-12-06 04:13
I might found condition to reproduce this issue. when I put English as top of languages on browser setting, blockly editor shows up.
and when I set Japanese above English again, issue reproduced.

I assume this setting changes accept-language header on the request which might trigger this issue.

<img width="1737" alt="スクリーンショット 2022-12-06 13 08 20" src="https://user-images.githubusercontent.com/103903/205811347-42d4b004-84c5-497e-b0a4-353bf2c36a03.png">

**Comment by NeilFraser** [comment] 2022-12-06 20:21
Ok, we've made progress here.  The central issue is that Google's DevSite has failed to push the new content to non-English languages.  Specifically this page is still pointing at blockly-demo (with tons of 404s):
https://developers-dot-devsite-v2-prod.appspot.com/blockly/blockly-demo/blockly-demo?hl=es-419

The staging server shows the correct links, but no translations.  The production server is translated, buh shows old content.

I think the problem may be that I changed the word 'Language:' to 'Generate:', Google didn't know how to translate that, and thus didn't push the new page.

**Comment by yandod** [comment] 2022-12-07 02:28
I'm happy to see progress which unblock all other non-English users of Blockly!

**Comment by Zireael07** [comment] 2022-12-07 08:20
That means my issue may be related - I'm 90% sure my browser language is set to Polish first English second

**Comment by NeilFraser** [comment] 2022-12-07 19:55
This is a fractal of unrelated issues.  Let's list them out:

1. Google's DevSite is holding up release of non-English translations of this page.  This means we can't publish the change of script tags from blockly-demo to unpkg.
2. Google's DevSite is flakey in passing the language preference from the main page to the demo iframe.  This means that when the (English speaking) team here changes our language, we don't see the error since that change is not propagated to the demo iframe.
3. Our demo doesn't take the DevSite language and load the compatible language pack in Blockly.
4. The content of the page (Blockly, YouTube, Analytics) are so large that they are overflowing the cache limits on some browsers.
5. Google's DevSite is corrupting the page leading to invalid XML which breaks Blockly's loading.

The last error shows up as our source appearing as:
```
</div>
-
              </block>
 </value>
```
This is not Google's finest hour.

**Comment by NeilFraser** [comment] 2022-12-10 03:07
Other errors with the existing demo include:

7. Workspace scrollbar now overlaps the output pane (it didn't used to).
8. Syntax highlighting broke sometime in the past year.
9. Missing blocks in toolbox.
10. Blockly doesn't flip in RTL.
11. Google's automated policies are very unhappy with JS-Interpreter being checked into DevSite.
12. The "Colour" category is spelt wrong.

Most of these errors are the result of creeping dependency issues with DevSite.  Migrating the demo to blockly-samples (a site we control completely) reduces our dependencies and should increase reliability.

The PR https://github.com/google/blockly-samples/pull/1440 resolves all the above issues; with the exception of number 4.

**Comment by rachel-fenichel** [comment] 2022-12-12 19:00
For number 4
- I ran into cache limits in chrome, which showed up as an over limit message in the Applications tab of Chrome Dev Tools, under Storage. This was partly because the page is big and partly because certain Chrome settings keep your limit very low.
- I recommend that we remove the embedded YouTube video from the page, at least while we're not specifically highlighting the summit.

**Comment by NeilFraser** [comment] 2023-02-28 17:51
Finally resolved.  https://developers.google.com/blockly/

**Closed by NeilFraser** 2023-02-28 17:51 UTC
Labels: issue: docs

**Comment by NeilFraser** [comment] 2023-02-28 17:53
Thank you in particular to @yandod and @Zireael07 for helping diagnose this unexpectedly deep issue!

**Comment by Zireael07** [comment] 2023-03-01 08:07
You're welcome!
