### ISSUE TITLE
Horizontal toolbox items not right-aligned in RTL

### ISSUE THREAD

**Issue by vicng** [google/blockly#1466] opened 2017-11-21 03:02 UTC
### Problem statement

- [x] Bug report
- [ ] Feature request

Items in RTL horizontal toolboxes are not right-aligned.

eg.
![screen shot 2017-11-20 at 6 58 42 pm](https://user-images.githubusercontent.com/13488389/33052683-e05f90f8-ce24-11e7-9bf4-0a9c10a601e7.png)

### Expected Behavior

All items (blocks, buttons, whatever else) should be right-aligned.

### Actual Behavior

Items are left-aligned and fill the toolbox toward the right. (Note that the workspace positioning of the toolbox category is correct though -- the first item is always visible.)

**Comment by NeilFraser** [comment] 2017-11-21 05:39
I think this is a duplicate of https://github.com/google/blockly/issues/431.

**Comment by rachel-fenichel** [comment] 2017-12-28 23:47
Closing as dupe.

**Closed by rachel-fenichel** 2017-12-28 23:47 UTC
