### ISSUE TITLE
Onscreen keyboard closes automatically on Surface tablet on Edge, sometimes Chrome

### ISSUE THREAD

**Issue by paulkaplan** [google/blockly#1843] opened 2018-05-04 15:25 UTC
### Problem statement

When I try to click into a text field, the onscreen keyboard pops up, but then the field unfocuses and the keyboard goes away. 

### Expected Behavior

The keyboard should stay open and the input should remain focused.

### Actual Behavior

The field unfocuses and the keyboard goes away. In this gif, all I'm doing is clicking the input, the rest is happening automatically.

![keyboard](https://user-images.githubusercontent.com/654102/39635307-1ea66944-4f8b-11e8-8f75-a87066e7fd17.gif)

### Steps to Reproduce

1. Use a Microsoft surface tablet on Edge.
2. Go to blockly-demo.appspot.com, go to the "Fixed Blockly" demo.
3. Drag out a block that has an input (tested with both number and string fields)
4. Click on the input, see the input focus, keyboard come up, and then go away.

Note I can get the same behavior out of chrome when the window is not maximized. Not sure what that means...

### Stack Traces

None

### Operating System and Browser

* Windows Edge - **does not work (described above)**
* Desktop Chrome - **does not work unless window is maximized**
* Desktop Firefox - works maximized (keyboard appears and stays), but I can't even get the onscreen keyboard to show in the url bar if the window is not maximized...

Device: Microsoft surface tablet, newly updated to Edge 16 (although it was happening on previous Edge 15 version)

### Additional Information

Did not test on the other listed browsers (IEs, Opera), not sure if functionality there would be relevant, since it does work on Chrome/Firefox on the same device.

Using the surface for a bit, it really seems like the onscreen keyboard is supremely messed up in a lot of non-blockly contexts, but it does make it impossible to use blockly on this surface :(

I also have thought it is possible I have some setting enabled that this is causing only for me. I confirmed no bluetooth keyboards are attached (disabled bluetooth) and also tried using "tablet mode" (maximizes all apps), in which case Edge still doesn't work, but firefox/chrome do work. If anyone knows other settings to adjust, let me know, i'm a new windows user.

**Comment by AnmAtAnm** [comment] 2018-06-26 21:21
Confirmed in Edge on a Surface tablet. Both Chrome and Internet Explorer on the same device worked correctly. Tested in both master and June release candidate with the same results.

**Comment by AnmAtAnm** [comment] 2018-06-26 21:22
That Chrome worked may be the point about the window being maximized, which appears always true on a Surface.

**Comment by AnmAtAnm** [comment] 2018-06-26 21:30
@pelikhan Does your team have bandwidth to investigate this?

**Comment by maribethb** [comment] 2023-05-17 20:47
Duplicate of https://github.com/google/blockly/issues/6915 and fixed

**Closed by maribethb** 2023-05-17 20:47 UTC
Labels: issue: bug, component: browser, component: touch, component: mobile
