### ISSUE TITLE
Insertion marker flickering

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2255] opened 2019-02-04 17:13 UTC
Insertion markers on value inputs are flickering on the playground. Need to dig into this and tune the constants to make it stop, ideally before the next release.

**Comment by AnmAtAnm** [comment] 2019-02-07 22:25
Is this related to or a dupe of #2217?

**Comment by RoboErikG** [comment] 2019-02-07 22:32
yep, they're related. This is the immediate problem and that's the bigger issue.

**Closed** 2019-02-15 23:49 UTC
Labels: type: bug
