### ISSUE TITLE
Blocks looks clumsy when converted from xml code to blocks

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#3206] opened 2019-10-09 10:02 UTC
**Describe the bug**

Blocks are displayed clumsy when converted from xml code to blocks

**To Reproduce**

1. Go to 'https://rachel-fenichel.github.io/blockly/tests/playground.html?'
2. BUild a set of blocks which actually shows this image 
 https://docs.google.com/document/d/1-qTCj0gWNrkUHEMfSV_LV2wXn7bpiFmvRTyJBFlh798/edit?usp=sharing
3.copy the xml code
4. Go to 'https://rachel-fenichel.github.io/blockly/demos/code/index.html'
5. Paste the xml code and verify the block

**Expected behavior**

The blocks should be same as in the image mentioned in step 2

**Screenshots**
![image](https://user-images.githubusercontent.com/11066279/66499014-da881200-ea73-11e9-9cc5-cc033a73787e.png)

**Desktop (please complete the following information):**
 - Chromebook , Google chrome browser

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by RoboErikG** [comment] 2019-10-09 16:05
Duplicate of #2811

**Closed by RoboErikG** 2019-10-09 16:05 UTC
Labels: triage, type: bug
