### ISSUE TITLE
Improved Copy-Paste Functionality in Blockly

### ISSUE THREAD

**Issue by mmv-dev** [google/blockly#6983] opened 2023-04-16 06:57 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The current copy-paste functionality in Blockly is limited in that pasting only happens in the same location where the block was originally copied from, which can be frustrating and time-consuming for users.

### Request

I would like to suggest an improvement to the copy-paste functionality in Blockly. Specifically, I would like to request that pasting happens wherever the user is currently viewing, and especially where the pointer is located. This would significantly improve the efficiency of the copy-paste process and save time for users.

### Alternatives considered

I have not considered any alternative solutions at this time.

### Additional context

I am a regular user of Blockly and have experienced frustration with the current copy-paste functionality. I believe that the proposed improvement would greatly enhance the user experience and make Blockly a more effective tool for developers.

**Comment by BeksOmega** [comment] 2023-04-17 16:49
Dupe of https://github.com/google/blockly/issues/6848

Thanks for reporting this! If you have any thoughts that aren't covered by #6848 feel free to add them over there. That way we can keep all the info in the same place =)

**Closed** 2023-04-17 16:50 UTC
Labels: issue: feature request, issue: triage
