### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by RoachLin** [google/blockly#8184] opened 2024-05-30 02:27 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I'm using this example: https://github.com/google/blockly-samples/tree/master/examples/blockly-vue3
I want to use Chinese, so I modify this file: https://github.com/google/blockly-samples/blob/master/examples/blockly-vue3/src/components/BlocklyComponent.vue
In line 15, I change `'blockly/msg/en'` to `'blockly/msg/zh-hans'`, but the browser console shows an error `Blocked module loading from 'http://localhost:5173/node_modules/.vite/deps/blockly_msg_zh-hans.js?v=1f5554e6' because it used a disallowed MIME type ('').` and didn't show anything on the page. (I'm using firefox)
Then I struggled to find a possible solution, I turn to source code directory `blockly-vue3\node_modules\blockly\msg`, change filename `zh-hans.d.ts` to `zhHans.d.ts`, `zh-hans.js` to `zhHans.js`, `zh-hans.mjs` to `zhHans.mjs`, and change line 1 in `zhHans.mjs` to `import zh-hans from './zhHans.js';`
And it works, without any error.
I guess the key maybe the hyphen in `zh-hans`. Actually, I tried to change `'blockly/msg/en'` to `'blockly/msg/en-gb'`, but it didn't work either.

### Browsers

Firefox desktop

**Comment by BeksOmega** [comment] 2024-05-30 12:20
Thanks for reporting! This looks like a dupe of https://github.com/google/blockly/issues/8174 We're putting out a release today that fixes this =)

**Closed by BeksOmega** 2024-05-30 12:20 UTC
Labels: issue: bug, issue: triage
