### ISSUE TITLE
Recenter algorithm does not adapt to simple toolbox correctly

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2297] opened 2019-02-15 22:28 UTC
### Problem statement

When using an RTL workspace with a simple toolbox, the recenter algorithm does not account for the correct location of the simple toolbox. The algorithm appears to assume the simple toolbox is on the left edge, regardless of LTR/RTL and toolbox configuration. This leads to an incorrect size and placement of the user's view of the workspace.

### Expected Behavior

The recenter algorithm should calculate/query the placement of the toolbox to correctly calculate the viewable bounds of the workspace.

### Actual Behavior

![screen shot 2019-02-15 at 2 15 55 pm](https://user-images.githubusercontent.com/9916202/52887604-32f95080-312d-11e9-8ab6-59188e28a0b8.png)
![screen shot 2019-02-15 at 2 16 48 pm](https://user-images.githubusercontent.com/9916202/52887611-3ab8f500-312d-11e9-9b44-84f37ab8bfc4.png)

This is likely the root cause of #2036, where horizontal toolboxes are as wide as the visible workspace.
![screen shot 2019-02-15 at 2 17 26 pm](https://user-images.githubusercontent.com/9916202/52887595-2b39ac00-312d-11e9-9219-17833366c7c6.png)

### Steps to Reproduce

1. In the [simple toolbox multi-playground](https://blockly-demo.appspot.com/static/tests/multi_playground.html?toolbox=simple), drag the same block into each workspace.
2. Hit recenter in each workspace. Note the differences and similarities between the various workspaces. Note how several "recentered" workspaces actually place the block behind the toolbox, at least partially.

### Operating System and Browser

 * Desktop Chrome
 * Desktop Firefox

### Additional Information

This is the root cause of #2036, where horizontal toolboxes are as wide as the visible workspace.

**Comment by BeksOmega** [comment] 2019-02-16 00:14
I believe #2297 (this) and #2063 are probably dupes of #989.

And this is fixed in #2247 (scroll about half way down [this ](https://github.com/google/blockly/pull/2247#issuecomment-461502890) for pics), which is currently in [testing](https://workflowy.com/s/tasks/BA9fSKkSATEGLWMi), but should be finalized soon.

**Comment by rachel-fenichel** [comment] 2019-02-16 01:14
Closing as a dupe of #989

**Closed by rachel-fenichel** 2019-02-16 01:14 UTC
