### ISSUE TITLE
Screen scrolls down when user tries right click options(by long press on workspace) for disable/delete/redo/undo on multi playground _ iPad

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#3754] opened 2020-03-18 03:10 UTC
**Describe the bug**

Screen scrolls down when user tries right click options for disable/delete/redo/undo on multi playground _ iPad

**To Reproduce**

- create blocks as in below snapshot
https://screenshot.googleplex.com/cAvO0mnFueP.png

Procedure:
Drag into the flyout to delete the “not” block
Drag into the trash to delete the “and” block
Long press on workspace and try delete/disable/redo/undo

**Expected behavior**
Options should be shown without scrolling somewhere towards down

**Smartphone (please complete the following information):**
 -Device: iPad Model A1566
- Browser: safari

Please note that this is working as expected in iPhone XS.

**Comment by alschmiedt** [comment] 2020-03-18 15:50
Thanks for reporting! Is it highlighting everything when it scrolls?

**Comment by MNSDivya** [comment] 2020-03-19 07:48
@alschmiedt It is happening on all workspaces.

**Comment by samelhusseini** [comment] 2020-03-19 19:02
Based on my understanding of this issue, when you hold and click on a workspace in the multi_playground it scrolls down to that workspace.

Could you confirm the following: 
- What IOS version are you running?
- Does it scroll if you just click on the workspace, rather than click and hold?

I believe the issue is due to the fact the Safari and in turn Safari on Mobile do not support the preventScroll option when focusing, and we focus the workspace when a user clicks on it.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

**Comment by MNSDivya** [comment] 2020-03-20 12:34
Hi Sam,
- IOS version is 10.2.1
- No it does not scroll if you just click on workspace. 
Issue exists only when you click and hold for options.

**Comment by samelhusseini** [comment] 2020-03-31 17:31
I'm seeing this issue on IE11 as well.

**Comment by gonfunko** [comment] 2024-11-22 20:37
This no longer repros; MDN indicates that support for `preventScroll` was added to Mobile Safari in iOS 15.5. Closing accordingly.

**Closed by gonfunko** 2024-11-22 20:37 UTC
Labels: issue: bug, component: browser, component: multiworkspace
