### ISSUE TITLE
Markup in tooltip

### ISSUE THREAD

**Issue by Nekomajin42** [google/blockly#983] opened 2017-03-20 17:00 UTC
Hi guys!

Is it possible to pass a HTML string to the `setTooltip()` function? I'd like to show formatted text in the tooltip, but the HTML tags are printed as plain text.

**Comment by rachel-fenichel** [comment] 2017-03-23 18:20
I don't think we support this.

@NeilFraser to confirm.

**Comment by NeilFraser** [comment] 2017-03-23 18:41
Confirmed, not supported.  But I can't think of any reason why it couldn't be supported.  Tooltips are pure HTML, they don't live in SVG at all.  The quick and dirty approach would be to change [line 255](https://github.com/google/blockly/blob/master/core/tooltip.js#L255) from:
`div.appendChild(document.createTextNode(lines[i]));`
To:
`div.innerHTML = lines[i];`
You'd also need to switch off line wrapping by commenting out [line 250](https://github.com/google/blockly/blob/master/core/tooltip.js#L250).

However, the catch is that you'd be using innerHTML.  While that may be fine for @Nekomajin42 , it's a crazy-bad idea for Google.  To support this officially, we'd need to look at [goog.html.SafeHtml](https://google.github.io/closure-library/api/goog.html.SafeHtml.html) (already required by the toolbox).  And we'd need a heuristic to automatically detect text vs HTML with moderate confidence so that line wrapping could be switched on or off.

I think it's a good idea, and not too hard.  But I'm also not the one tasked with implementing it.  :)

**Comment by Nekomajin42** [comment] 2017-03-24 04:16
Thanks for mentioning the line wrapping. It makes me crazy. Now I use a big number, which is never reached in my app, but it's not an ideal solution.

**Comment by gonfunko** [comment] 2023-02-02 17:36
Closing since custom tooltips are now supported.

**Closed by gonfunko** 2023-02-02 17:36 UTC
Labels: issue: feature request
