### ISSUE TITLE
Minimap demo is broken

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2729] opened 2019-07-29 21:47 UTC
Previously there were multiple errors due to the implementation being only 80% complete.

But now there's massive console spam due to something really bad happening.  Needs some TLC.

**Comment by BeksOmega** [comment] 2021-08-14 01:30
I'm going to close this as a dupe of https://github.com/google/blockly-samples/issues/337

**Closed by BeksOmega** 2021-08-14 01:30 UTC
Labels: type: bug, low priority, component: demos
