### ISSUE TITLE
Unable edit text input on a desktop/tablet device that popup the virtual keyboard

### ISSUE THREAD

**Issue by Wei12345** [google/blockly#5926] opened 2022-02-10 03:19 UTC
**Describe the bug**

Click text input on a desktop/tablet device that popup the virtual keyboard, popup the virtual keyboard cause resize trigger, the text input blur.

On other the mobile device that popup the virtual keyboard is working because it can get `Blockly.utils.userAgent.IPAD = true` or `Blockly.utils.userAgent.MOBILE = true`, that Blockly popup edit input that working great.
But desktop/tablet device that popup the virtual keyboard can't popup edit input cause problem.

I have this problem on the tablet(windows 10)
However, all devices that are not mobile but have a popup virtual keyboard will have this problem.

**To Reproduce**

1. Open the browser using the desktop device(windows 10 + tablet is also) that popup the virtual keyboard
2. Go to https://developers.google.com/blockly/blockly-demo/blockly-demo
3. Click on text input
4. Text input get focus then lose focus

**Expected behavior**

The popup text input to enter text

**Desktop/Tablet:**
 - Device: Surface Pro 7
 - OS: Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.82
 - UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

**Comment by gonfunko** [comment] 2022-02-11 16:56
Thanks for reporting this! I think we're already tracking this, but's it's very useful to know it's still an issue with current browser versions on these devices.

Duplicate of #1843

**Comment by gonfunko** [comment] 2022-02-11 16:57
Duplicate of #1843

**Closed** 2022-02-23 16:11 UTC
Labels: component: browser, component: touch, component: mobile
