### ISSUE TITLE
Pinch zoom redraw is janky on Edge

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1941] opened 2018-06-26 22:01 UTC
### Problem statement

Pinch zoom behavior is slow to react and refresh on Microsoft Surface 3 Tablet. First zoom visualization is approximately a second after touch and start of gesture, and later refreshes occur around every half second.

Dragging and panning are unaffected.

The same behavior in Chrome on the Surface is significantly faster. Chrome on a Pixel 2 is even faster  (but could still improve). Both "capture" the pinch-zoom gesture more often than Edge.

### Expected Behavior

Pinch zoom redraw/refresh should be responsive within a tenth of a second, on par with the behavior on the Pixel 2 phone.

### Steps to Reproduce

1. On Surface 3 or comparable device, open Edge.
2. Open Blockly code demo or playground.
3. Add a few blocks to the desktop to visualize the scale changes.
4. Attempt pinch zoom on the workspace with two fingers, ensuring both touches begin on the workspace background at about the same time.

Observe how not every gesture attempt registers as a pinch zoom.
Observe how the workspace is slow to refresh/redraw, reducing the user's ability to control the zoom.

Attempting the same in Chrome has a much faster refresh.

### Operating System and Browser

 * Windows Edge

**Comment by gonfunko** [comment] 2023-02-02 23:54
Duplicate of #1545.

**Closed by gonfunko** 2023-02-02 23:54 UTC
Labels: component: browser, component: performance, component: touch
