### ISSUE TITLE
Function naming bug on page reload  (so when going through xml?)

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#503] opened 2016-07-25 20:06 UTC
This is true at least in the current Blockly Code Demo (and my blockly version from a week ago, which is how I found it):

I define the code in the first image (Blockly helpfully renaming the functions for me so I don't get two functions with the same name - hooray!).

Then I refresh the page (so the code is saved to xml, put in local storage, retrieved from local storage, the xml is converted to blocks and the workspace is populated) and I get the second image.  I have highlighted the change for you.  One of the function callers has changed names.

![func_name_bug_1](https://cloud.githubusercontent.com/assets/10271662/17115476/4d4277ce-5268-11e6-9077-fbe3a0a1e4ba.png)

![func_name_bug_2](https://cloud.githubusercontent.com/assets/10271662/17115526/8456c2ec-5268-11e6-981c-ed0937a61401.png)

**Comment by NeilFraser** [comment] 2016-07-26 13:12
Confirming.  The following XML is a minimal trigger (the function call should be 'do something', but gets renamed to 'do something2'):

```
<xml>
  <block type="procedures_callnoreturn" x="0" y="88">
    <mutation name="do something"></mutation>
  </block>
  <block type="procedures_defnoreturn" x="0" y="138">
    <field name="NAME">do something</field>
  </block>
  <block type="procedures_defnoreturn" x="0" y="238">
    <field name="NAME">do something2</field>
  </block>
</xml>
```

**Comment by AnmAtAnm** [comment] 2016-12-20 22:00
Reported again [here](https://groups.google.com/forum/#!topic/blockly/ZXszVFbRNtU).

This is dependent on the order of the blocks. If the order is definition, definition2, call, then the call doesn't change. Same for definition2, call, definition.  However definition-call-definition2 does create problem.  Maybe it is any time the call comes before the definition?

It also depends on the name of the called function to remain "do something".  If you rename it, it works fine.

**Comment by AnmAtAnm** [comment] 2016-12-20 22:20
Theory:
 * Function def "do something" and its calling block are created normally, in either order.
 * The creation of the next function definition block starts with "do something", the default name. This triggers findLegalName(), which sees the existing "do something" and proceeds to rename this block and all matching calls to "do something2".
 * Finally, the mutator for the function runs, again renaming this block and all matching calling block.

**Comment by AnmAtAnm** [comment] 2016-12-20 22:46
Alternative steps to recreate.
 1. Construct a "do something" definition and call.
 2. Duplicate the definition. New definition is "do something2" while the call remains "do something".
 3. Select and duplicate "do something2". This creates a new definition "do something3", and update the call to be the same.

**Comment by harbaum** [comment] 2016-12-21 06:47
I can confirm that this only happens when using the same language as on initial creation and thus using the same names during auto renaming.

And it happens when restoring from xml. The xml being saved is still correct.

**Comment by picklesrus** [comment] 2016-12-22 00:52
I traced through this today just by importing the xml @NeilFraser provided above to the playground. I also added ids so I could more easily identify blocks, but that shouldn't matter.  @AnmAtAnm's theory above is almost it, except for the mutator part. The problem is updating the "NAME" field to "do something2".

- Function definition "do something" and the caller are created correctly. 
- During the deserialization of the "do something2" block, the initial Block object is created with a field name value of "do something" since that's what's specified in the init().
- Later domToBlockHeadless tries to set the field to "do something2" [here](https://github.com/google/blockly/blob/master/core/xml.js#L472),  in turn calling the [callValidator](https://github.com/google/blockly/blob/master/core/field.js#L262) for the procedure and we end up renaming any existing callers in [rename](https://github.com/google/blockly/blob/master/core/procedures.js#L145).

It looks like this may have been exposed in https://github.com/google/blockly/commit/2dab19c015279d8d9bd665ac68f5b8e7ce8f8113, then mostly fixed by https://github.com/google/blockly/commit/57390fd744495ea07826402ba0bfd743f9f716b6, except for in the case of the default name Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE (which is "do something") in English.

**Comment by picklesrus** [comment] 2016-12-22 01:01
Ooops, commented too soon. A little more info:

I verified this by changing the default name sent to the [init function()](https://github.com/google/blockly/blob/master/blocks/procedures.js#L44) was something other than "do something" and the xml loads correctly without renaming the caller block.

Changing the default in init isn't a real solution (although maybe it is part of one?) since iiuc, the flyout currently uses that value populate the initial blocks in the procedures category.

**Comment by rachel-fenichel** [comment] 2017-01-04 02:47
https://github.com/google/blockly/pull/803 may fix this, but I'd like a robust sanity check.

It's changing the default function name to the empty string instead of to "do something", and populating the blocks in the flyout with the appropriate strings.

But now if you import a procedure definition from XML and leave out the block name, you end up with a procedure block with no name instead of with "do something" as the name.  I suspect there's a reason @NeilFraser didn't do this from the beginning.

**Comment by rachel-fenichel** [comment] 2017-01-04 21:25
An update: we're using #803 to fix this for the current develop->master push, which should remove the pain point that people have been hitting a lot; we will follow up to try to find a better way of handling function names when initializing the block.

**Comment by NeilFraser** [comment] 2017-01-05 04:40
#803 is a very cute solution.  Wish I'd thought of that.

**Comment by NeilFraser** [comment] 2018-01-19 00:23
This has been fixed.  I cannot reproduce anymore.

**Closed by NeilFraser** 2018-01-19 00:23 UTC
