### ISSUE TITLE
"Import Toolbox" on Workspace Factory is not working when trying to load the file second time

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#6043] opened 2022-03-29 15:52 UTC
**Describe the bug**

**To Reproduce**

1. Go to 'http://google.github.io/blockly/demos/blockfactory/index.html'
2. Create configuration in Block factory and verify the preview
3. Navigate to Block Exporter and select the preview Block
4. Click on Export and verify the files are downloaded successfully
5. Navigate back to the “Workspace Factory” tab (Notice that your category has disappeared)
6. Click on the “Load to Edit” button near the top of the page
7. Choose “Toolbox” from the dropdown menu
8. Choose the “toolbox.xml” file you downloaded from the previous step
9. Click “open” and Make sure your category has reappeared on the right hand side of the screen
10. Clear the page and repeat from step 6 to import toolbox

**Expected behavior**

Ideally the same toolbox.xml file once downloaded should be reused any no.of times

**Actual behavior**
No error thrown on UI but few console errors found and no file has been uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/56336353/160653247-9cb8526a-8009-4fe5-a86c-ede43713cd05.png)

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [chrome]
 - Version [99.0.4844.57 (Official Build) (64-bit)]

**Comment by cpcallen** [comment] 2023-06-23 21:34
The reproduction steps in this bug do not really make sense; in summary, they are:

- On the Block Factory tab, create a block.
- On the Block Exporter tab, export the block (as either JSON or JS, it's not specified which).
- On the Workspace Factory tab, try to load a file named `toolbox.xml`, which is claimed to be the file downloaded in the previous step—but the previous step would have produced a `.js` or `.json` file, and attempting to load these as XML will always fail.

So as described it is not possible for this test to be successful.

I have verified that I can use the Export and Load to Edit buttons to save/load a toolbox configuration.

Looking at the error messages in the console, they are the errors that one would expect to see when encountering the bug reported in #6043 (which was previously reported in #697).

I am closing this issue as either unreproducible, working as intended, broken as intended, or duplicate.  I'm just not sure which.

**Closed by cpcallen** 2023-06-23 21:34 UTC
Labels: issue: bug, component: devtools
