### ISSUE TITLE
Dynamically generated blocks output is being lost after last lib update

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#4757] opened 2021-04-05 13:00 UTC
**Describe the bug**

After last blockly update (version 5.20210325.0) a dynamically set output on a block of mine is losing info on getCheck() function. The scenario consists in:

- I have a setOutput(true, value) inside a block validator.
- I have a getCheck() inside a block setOnChange function

Previously on version 4.20201217.0) and even before it, the `setOnChange()` function calling the `getCheck()` on the `outputConnection` of this block, attached to the source block listened on the `setOnChange` function returns the output dynamically set correctly, but now, it always returns undefined, breaking all the logic

**To Reproduce**

- Add a setOutput(true, value) inside a block validator.
- Add a getCheck() inside a block setOnChange function

**Expected behavior**

The getCheck() function must return the arrays of types defined previously by calling the setOutput() function, as documented.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Ubuntu 20.04.1 LTS
 - Browser [e.g. chrome, safari] - Chrome 
 - Version [e.g. 22] 88.0.4324.182 64 bits

**Comment by alschmiedt** [comment] 2021-04-07 16:19
Hello! Thanks for reporting, can you add an example of the block definition that is not working?

**Comment by rachel-fenichel** [comment] 2021-06-17 04:39
I tried to make a block that would reproduce this, but couldn't repro.

Here's my block:
```
function defineBlock() {
  Blockly.Blocks['dynamic_output_type'] = {
    init: function() {
      this.appendDummyInput()
          .appendField('my test block')
          .appendField(new Blockly.FieldTextInput('default text', function(newValue) {
            this.getSourceBlock().setOutput(true, newValue);
            return newValue;
          }));
      this.setStyle('procedure_blocks');
      this.setOutput(true, ['test type'])
      this.setOnChange(function(changeEvent) {
        console.log(this.outputConnection.getCheck());
      });
    }
  }
}
```

And I tested by importing the following XML into my workspace:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="dynamic_output_type">
  </block>
</xml>
```

Then I typed in the field and checked the output types array.

If this doesn't match your block, please reply with a block definition that I can use to debug.

**Comment by rachel-fenichel** [comment] 2021-06-24 23:35
Closing (cannot reproduce).

**Closed by rachel-fenichel** 2021-06-24 23:35 UTC
Labels: component: connection, type: bug
