### ISSUE TITLE
Variables does not set check of connection

### ISSUE THREAD

**Issue by duzc2** [google/blockly#1469] opened 2017-11-21 20:01 UTC
### Problem statement

- [x] Bug report
- [ ] Feature request

_What were you trying to do when you hit this bug?  Or, what do you want to do with Blockly that your proposed feature would enable?_

### Expected Behavior
workspace.createVariable(name,type);
should add a variable with a type check enabled.

### Actual Behavior

it does not set a check on the input or output connection.

### Steps to Reproduce
just add a variable with opt_type : workspace.createVariable("abc","string");
it should only be set with string type value , or should use as string type.
but it's treat as no type check.

### Operating System and Browser

_Remove this hint: these checkboxes can be checked like this: [x]_

- [x] Desktop:
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

**Comment by rachel-fenichel** [comment] 2017-11-21 21:02
Dupe of https://github.com/google/blockly/issues/1281

If you're interested in implementing this, let me know.  We'd love the help.

**Closed by rachel-fenichel** 2017-11-21 21:02 UTC

**Comment by duzc2** [comment] 2017-11-22 06:00
Sure , I will implement this. @rachel-fenichel 
And before I start this work any thing important need I know ?

**Comment by rachel-fenichel** [comment] 2017-11-22 18:56
Awesome!  I'll put a few comments on that issue to keep it all in one place.
