### ISSUE TITLE
Discussion: Meaning of the 'rendered' property on blocks and workspaces

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1676] opened 2018-03-01 01:38 UTC
Workspaces and blocks both have a `rendered` property.  

On a workspace it's true if the workspace is a `WorkspaceSvg` and false otherwise.  The exception is that it's set to false at the beginning of `dispose`.

On a block it's false if the block is a `Block`.  If it's a `BlockSvg` it's true if the block is currently rendered (has been rendered for the first time, not hidden, etc.).

There are a few possible meanings for `rendered`:
1. Whether it has ever been initialized ("Has it been rendered yet?")
2. Whether it is currently correctly rendered onscreen ("Is it visible?")
3. Whether is is renderable ("Is it on a WorkspaceSvg?")

--------
`Bubble`s also have a `rendered_` property, though it's private.  Workspace comments will have a `rendered` property, and may have other properties or helper methods to answer the three questions above.

**Comment by samelhusseini** [comment] 2020-06-08 19:46
Minor nuance as I came across this recently:
> On a block it's false if the block is a Block. If it's a BlockSvg it's true if the block is currently rendered (has been rendered for the first time, not hidden, etc.).

On a block, it's undefined if it's a Block. False if it's a BlockSvg and not yet rendered, and true if it's a Block and it is rendered.

We can consider matching that behavior in the Workspace code so that it's consistent in meaning.

**Comment by maribethb** [comment] 2023-02-15 22:33
Going to close this as a duplicate of #4288. It's not a perfect duplicate, but the work done by #6786 will improve the situation a lot because we'd be able to check `isDirty` (or similar) instead of abusing the `rendered_` property. We can reopen this if we find we need further cleanup here or we ever come up with a clean proposal. But for now it's not clear that there is a next step (beyond the work mentioned above) so closing.

**Closed by maribethb** 2023-02-15 22:33 UTC
Labels: type: question, internal
