### ISSUE TITLE
Issue with text fields on Firefox / OSX

### ISSUE THREAD

**Issue by msprotz** [google/blockly#154] opened 2015-08-14 17:03 UTC
I'm forwarding an issue that was reported to me.

<img width="1109" alt="screen shot 2015-07-21 at 11 46 18" src="https://cloud.githubusercontent.com/assets/12099488/8798957/44298b3e-2f9e-11e5-9f40-82f8c71d0143.png">

Apparently, trying to type in a text field gives a weird rendering due to firefox highlighting the text outside of the text field...? I was unable to reproduce this myself (I don't have an OSX machine).

The testcase is still http://jonathan.protzenko.free.fr/t/editor.html

let me know if you managed to reproduce this somehow. Thanks!

Jonathan

**Comment by NeilFraser** [comment] 2015-08-14 18:37
I can confirm in Firefox on OSX.  Interestingly, on the Blockly demo pages this bug does not occur (technically the text is misaligned by 1px, but nothing like what's seen on microbit).  A few minutes of poking doesn't reveal a smoking gun.

We are about to land the zooming code early next week, which (as you might imagine) shakes up the coordinate calculations a bit.  Can this bug be ignored till then?  With luck it might just go away, but if it doesn't at least we'll all be working on the same branch.
https://github.com/google/blockly/pull/125/files

**Comment by msprotz** [comment] 2015-08-14 20:53
From preliminary testing, it seems like the zooming branch fixes this issue. I'll wait to hear back from my primary tester and close the issue if he's satisfied with the fix. Thanks for the prompt reply!

**Comment by carlosperate** [comment] 2015-08-17 15:01
Probably not as relevant now, but I can confirm this is also an issue in Firefox on Windows. Since it seems to be working fine in Linux, could this possibly be a bug on Firefox worth reporting in their tracker?

**Comment by NeilFraser** [comment] 2015-08-20 00:42
Zooming code just landed.  Is this bug still valid?

**Comment by msprotz** [comment] 2015-08-21 18:52
The text field is still slightly off (less so, though) on Firefox (windows) using master.

**Comment by NeilFraser** [comment] 2015-08-21 21:13
I'm seeing behaviour on OSX where Firefox (only) will place the text field perfectly when first clicked, but on subsequent text edits will misplace the field one pixel too low and too right.  Does this match your observations?

Digging into the one-pixel bug that I can see, it seems that goog.style.getPageOffset is the origin of this bug.  Looking at the source, it is easy to see why a bug like that could lurk there:
https://code.google.com/p/closure-library/source/browse/closure/goog/style/style.js?r=9b73fbdafe29be2f4344805dcecb7a3efaa74999#628

I've added a little hack in Blockly to fix this issue.  Let me know how Windows likes this.

**Comment by msprotz** [comment] 2015-08-21 21:43
I can sure try it out, but I can't bring the bugfix in our codebase because of #166, unfortunately

**Comment by msprotz** [comment] 2015-08-24 20:55
Hmm... it looks like it's still one pixel off.

![capture](https://cloud.githubusercontent.com/assets/10673049/9452181/b7e12d5a-4a67-11e5-948c-8a74571083b1.PNG)

**Comment by carlosperate** [comment] 2015-08-24 21:19
That looks like the one pixel Neil was referring to on his first response.

**Comment by NeilFraser** [comment] 2016-12-07 07:19
Closing this bug since it is no longer reproducible in the current codebase.

**Closed by NeilFraser** 2016-12-07 07:19 UTC
