### ISSUE TITLE
MultilineInput - Not sized properly when workspace is loaded.

### ISSUE THREAD

**Issue by nanhishweta-26** [google/blockly#6071] opened 2022-04-11 13:46 UTC
Hi Team,

As shown in the below screenshots, when the Workspace is cleared and loaded

Multiline block is not sized properly to show all the text within the block as seen in Image1. 

But, if we try to edit the block the multiline block is resized to accommodate the text as seen in Image 2. Also, afterwards it retains the size.

Image 1:
![image](https://user-images.githubusercontent.com/56015624/162752966-0c3386bd-a4ab-4b11-a1e6-4fc9b41b4fc0.png)

Image 2:
![image](https://user-images.githubusercontent.com/56015624/162753059-3c2f82fe-815a-4656-8c33-7eb1385c3a60.png)

Any help is much appreciated.

Thanks,
Shweta

**Comment by maribethb** [comment] 2022-04-16 20:04
Hi, I'm not able to reproduce this. Can you provide more detailed reproduction steps? How are you clearing and reloading the workspace?

Thanks!

**Comment by nanhishweta-26** [comment] 2022-04-18 06:34
This is the code to reproduce the bug. Please review and let us know if you need any more details.


`blocklyWorkspace.clear();

var workspaceJSONValue =
{
    "blocks": {
        "languageVersion": 0,
        "blocks": [
            {
                "type": "modify_form",
                "id": "4PMzIgAFVO2s_-m?$:1d",
                "x": 10,
                "y": 10,
                "inputs": {
                    "modify_form": {
                        "block": {
                            "type": "variables_set",
                            "id": "ud4J|#g9tWCPdL?gO,(K",
                            "fields": {
                                "VAR": {
                                    "id": "zFF)Ar@[ZdrIxEL}n)Ao"
                                }
                            },
                            "inputs": {
                                "VALUE": {
                                    "block": {
                                        "type": "text_multiline",
                                        "id": "|YCm`eZO3k?7g/dw0hb(",
                                        "fields": {
                                            "TEXT": "This is a very long message"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        ]
    },
    "variables": [
        {
            "name": "Message",
            "id": "zFF)Ar@[ZdrIxEL}n)Ao"
        }
    ]
}

Blockly.serialization.workspaces.load(workspaceJSONValue, blocklyWorkspace);`

**Comment by Juliandebruin** [comment] 2022-07-18 15:57
Is there a workaround for now? I am having the same issue

**Comment by shals1031** [comment] 2022-08-09 03:40
Hi Blockly team

Even we are facing the same issue in our environment, any plans as to when this fix can be provided or do we any work around for the same.
Expecting as always quick response from your side

**Comment by ionous** [comment] 2022-09-02 08:53
I've encountered this on Windows 10 using Chrome 104.0.5112.102, Firefox 104.0.1, and Edge 104.0.1293.70.

The reason is that `textElement.getComputedTextLength()` in `Blockly.utils.dom.getTextWidth()` called by  [Blockly.FieldMultilineInput.updateSize_()](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/field_multilineinput.js#L286)  returns `0` because the svg element isn't rendered yet ( `Node.isConnected` is still `false` )

re: bugzilla "[SVGTextElement.getComputedTextLength() returns 0 if element not rendered](https://bugzilla.mozilla.org/show_bug.cgi?id=345635)" and "[SVG display:none rules](https://bugzilla.mozilla.org/show_bug.cgi?id=376027)"

To work around, i derived my own class based on `Blockly.FieldMultilineInput`, duplicated the `updateSize_()` implementation, and  changed the `dom.getTextWidth()` call to `dom.getFastTextWidth()` like the ["isBeingEdited_" section](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/core/field_multilineinput.js#L312) uses. 

before:
![image](https://user-images.githubusercontent.com/335250/188079232-fe5f9ee1-2d45-4ed0-ba6d-5d8b6d6139ec.png)

after:
![image](https://user-images.githubusercontent.com/335250/188079152-0071f08c-c543-4879-92d5-6ce84a02d308.png)

I don't know what the actual correct fix is though.

**Comment by Juliandebruin** [comment] 2022-09-03 16:00
Thank you @ionous this fixed my problem. For me dom.getFastTextWidth was undefined so the solution is to use Blockly.utils.dom.getFastTextWidth which is the alias given in the [documentation](https://github.com/google/blockly/blob/55a707662409a8829416e38e7655bb5d009aca39/typings/blockly.d.ts#L497).

This is how it worked for me:

`class MyFieldMultilineInput extends Blockly.FieldMultilineInput {
			updateSize_() {
				const nodes = this.textGroup_.childNodes;
				let totalWidth = 0;
				let totalHeight = 0;
				for (let i = 0; i < nodes.length; i++) {
					const tspan = /** @type {!Element} */ (nodes[i]);
					const textWidth = Blockly.utils.dom.getTextWidth(tspan) || Blockly.utils.dom.getFastTextWidth(tspan, fontSize, fontWeight, fontFamily);
					if (textWidth > totalWidth) {
						totalWidth = textWidth;
					}
					totalHeight += this.getConstants().FIELD_TEXT_HEIGHT +
						(i > 0 ? this.getConstants().FIELD_BORDER_RECT_Y_PADDING : 0);
				}
				if (this.isBeingEdited_) {
					const actualEditorLines = this.value_.split('\n');
					const dummyTextElement = Blockly.utils.dom.createSvgElement(
						Svg.TEXT, { 'class': 'blocklyText blocklyMultilineText' });
					const fontSize = this.getConstants().FIELD_TEXT_FONTSIZE;
					const fontWeight = this.getConstants().FIELD_TEXT_FONTWEIGHT;
					const fontFamily = this.getConstants().FIELD_TEXT_FONTFAMILY;

					for (let i = 0; i < actualEditorLines.length; i++) {
						if (actualEditorLines[i].length > this.maxDisplayLength) {
							actualEditorLines[i] =
								actualEditorLines[i].substring(0, this.maxDisplayLength);
						}
						dummyTextElement.textContent = actualEditorLines[i];
						const lineWidth = Blockly.utils.dom.getFastTextWidth(
							dummyTextElement, fontSize, fontWeight, fontFamily);
						if (lineWidth > totalWidth) {
							totalWidth = lineWidth;
						}
					}

					const scrollbarWidth =
						this.htmlInput_.offsetWidth - this.htmlInput_.clientWidth;
					totalWidth += scrollbarWidth;
				}
				if (this.borderRect_) {
					totalHeight += this.getConstants().FIELD_BORDER_RECT_Y_PADDING * 2;
					totalWidth += this.getConstants().FIELD_BORDER_RECT_X_PADDING * 2;
					this.borderRect_.setAttribute('width', totalWidth);
					this.borderRect_.setAttribute('height', totalHeight);
				}
				this.size_.width = totalWidth;
				this.size_.height = totalHeight;

				this.positionBorderRect_();
			}
		}

		let myField = new MyFieldMultilineInput("MultiLineText\n\n\n");`

**Comment by BeksOmega** [comment] 2022-10-12 17:51
Fixed by #6461

**Closed by BeksOmega** 2022-10-12 17:51 UTC
Labels: issue: bug, component: fields, needs more info
