### ISSUE TITLE
Trashcan doesn't accept blocks?

### ISSUE THREAD

**Issue by acbart** [google/blockly#498] opened 2016-07-22 18:43 UTC
I'm on Chrome on Windows, and can't seem to drag blocks into the trashcan. However, the bug is intermittent. When I first visit the page, I can't delete blocks. However, if I create a nested block (i.e. a block with a statement, e.g., a for loop with a print statement inside), I can successfully drag this to the trashcan and delete it. Afterwards, blocks can be deleted using the trashcan normally.

This happens even on the demos, for me:
https://blockly-demo.appspot.com/static/demos/toolbox/index.html

Hopefully you can reproduce this, and I don't just sound crazy.

**Comment by rachel-fenichel** [comment] 2016-07-22 18:53
Hi @acbart,

I think you might be crazy!  I (chrome on linux) can't reproduce it with the steps you described, but I'll keep an eye out for this.

**Comment by rachel-fenichel** [comment] 2016-07-22 21:07
Can't repro with chrome on linux, mac, or windows.  If you can find a way to make it happen consistently, please let us know.

**Comment by acbart** [comment] 2016-07-22 21:21
It happens very inconsistently for me; when filming the following, it happened 1 out of 3 times. Please forgive the sketch quality and ignore the weird fragments. It doesn't lag like that in real life, that's just the screen capture software being lousy.

![blockly-trashcan-error](https://cloud.githubusercontent.com/assets/897227/17071604/c86d2eee-501f-11e6-9b08-79941a79669e.gif)

**Comment by picklesrus** [comment] 2016-07-22 22:03
Hmm. I haven't reproduced either, but haven't tried windows yet.  Which version of chrome are you on?
Do you see any errors in the js console when it fails? 
Can you reproduce the same thing when trying to delete a block while dragging over the toolbox on the left?

**Comment by acbart** [comment] 2016-07-22 22:13
Version 51.0.2704.103 m (64-bit)

No errors in the console, except for the usual Chrome one about "the play() request was interrupted by a call to pause()". Wish I could silence that one...

No problems dragging the block off to the left in order to delete it.

**Comment by picklesrus** [comment] 2016-07-28 18:30
Update: I'm still waiting to get the windows machine I have access to connected to the internet...  Once I do, I'll see if I can reproduce

**Comment by picklesrus** [comment] 2016-08-01 21:25
I've now got access to windows so I tested on the same chrome version as you (version 510.2704.103 m) but I still cannot reproduce.  I'm going to close for now, but I'll keep an eye out for this.  Also, if you find a more reliable set of steps to reproduce, please reopen.

**Comment by acbart** [comment] 2016-08-01 22:56
I'll let you know if I ever do. It's not a show-stopper by any means, so it's okay. Thanks for taking the time to look into it!

**Comment by acbart** [comment] 2016-08-06 15:52
Just to advance this a little, I encountered this bug again while I was working today, so I decided to do a little investigating. My current values for deleteAreaTrash_ seem incorrect to me; wouldn't this position it somewhere offscreen to the left? I don't always have a firm hold on Blockly's coordinate system.

![image](https://cloud.githubusercontent.com/assets/897227/17457641/ec5f9ea6-5bcb-11e6-991d-77c2933999c3.png)

After some finagling to grab and delete other blocks, I was able to reenable the trashcan and got these values:
![image](https://cloud.githubusercontent.com/assets/897227/17457662/2c0e921e-5bcc-11e6-9faa-98a914219c12.png)


So it is possible that the canvas' scrolling somehow sets the trashcan somewhere bizarre?

**Comment by acbart** [comment] 2016-08-07 02:15
Ah! I can reliably trigger this problem. If the trashcan is offscreen when I load the page, then when I scroll it on screen I won't be able to drag a block onto it. If I load the page with it on, then I can drag a block on. I note that the deleteAreaTrash_ is different from the trashcan.getClientRect() value in the former case. Could this somehow be involved? BlockPy pages often load in different contexts, so sometimes I'm able to see the whole thing up front and sometimes I'm scrolling; that would account for the variability in what I see.

**Comment by picklesrus** [comment] 2016-08-07 02:58
Thanks for digging into this more! Yes, I think that makes a lot of sense.  There was a change made relatively recently to re-calculate the position of the trash less frequently (originally we were doing it on every mouse move event) because it required the browser to re-layout the whole page so is pretty expensive.  We now calculate it when we think it has moved (e.g. a window resize event) but I don't think I ever tested the case where the trashcan starts off outside the view of a scrollable page. 

If I make my window small I can reproduce this on one of the fixed size blockly demos that allows the page to scroll too: https://blockly-demo.appspot.com/static/demos/maxBlocks/index.html

There are some workarounds I could suggest if that'd be helpful, but they'll slow down interaction a bunch, so I'll try and get it fixed this week.

Thanks again for following up!

**Comment by rachel-fenichel** [comment] 2016-08-17 00:03
Fixed by #534

**Closed by rachel-fenichel** 2016-08-17 00:03 UTC

**Comment by drizzt451** [comment] 2021-07-07 00:37
Hello folks, I am having the "Trashcan doesnt accept blocks" issue with the blocky app on ipad for the dash robot by wonder workshop.

[https://ibb.co/S30RJKL](url)

As you can see from the picture, there is a start nest that was from the previous section of the puzzle (puzzle stage two, part two is where the problem happens) which does not go away on the next stage and when i try to take elements of that nest/blocks to trashcan, the lid on the trashcan doesnt work and the block just sits over it. we are stuck at this level with my son and we are looking for help to resolve this. tried installing it on a different ipad and we got stuck at same exact spot.

any help would be appreciated.
![gith](https://user-images.githubusercontent.com/3580918/124682940-04b17280-de9a-11eb-9850-dcb778d36ab7.jpg)
