### ISSUE TITLE
blockly developer tools block display is broken

### ISSUE THREAD

**Issue by rylid-umil** [google/blockly#6820] opened 2023-02-05 16:57 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

when ever i load a block from block library on firefox, the preview does not show no matter what. its supposed to be there. when i create a new block however, it works fine. all other block displays work.

### Reproduction steps

1. have blocks in the block library
2. load one
3. look at the preview

### Screenshots

![image](https://user-images.githubusercontent.com/81439905/216833100-0de18cde-7fcf-406b-b574-7606938e7629.png)

### Browsers

Firefox desktop

**Comment by mrkprdo** [comment] 2023-02-06 20:06
It could be that you have conflicting "names" in the editor workspace. If you see something like blue triangles next to the name, you should change that to something else.

**Comment by rylid-umil** [comment] 2023-02-08 17:02
i dont have any conflicting names and it still doesnt show

**Comment by Njinx** [comment] 2023-02-09 20:19
@rylid-umil Do you see a message like mine on the left pane? 
![2023-02-09_15-17](https://user-images.githubusercontent.com/6340528/217927714-664c0a3c-acfe-4ae2-a99b-0385a2e09249.png)

**Comment by lkarthee** [comment] 2023-04-05 04:29
I have encountered same issue and it makes the dev workspace unusable. 

All the blocks in workspace are not rendered in preview with the same error: 

```
You can't make a block called <BlockName> in this tool because that name already exists. 4 factory.js:193:15
    warnExistingBlock factory.js:193
    updatePreview factory.js:205
    updateLanguage factory.js:148
    fireChangeListener workspace.ts:686
    fireNow$$module$build$src$core$events$utils utils.ts:249
    (Async: setTimeout handler)
    utils utils.ts:227
    (Async: FrameRequestCallback)
    fireInternal$$module$build$src$core$events$utils utils.ts:226
    fire$$module$build$src$core$events$utils utils.ts:211
    dispose block.ts:325
    dispose block_svg.ts:854
    clear workspace.ts:357
    clear workspace_svg.ts:2356
    openBlock block_library_controller.js:68
    setSelectedAndOpen_ block_library_controller.js:253
    makeOptionSelectHandler_ block_library_controller.js:271
    (Async: EventListener.handleEvent)
    addEventListener eval:4
    addOptionSelectHandler block_library_controller.js:278
    addOptionSelectHandlers block_library_controller.js:289
    populateBlockLibrary block_library_controller.js:165
    AppController app_controller.js:22
    init index.html:40
    (Async: EventListener.handleEvent)
    addEventListener eval:4
    <anonymous> index.html:44
```

I have checked local storage in the browser - it has no duplicate blocks.
![image](https://user-images.githubusercontent.com/2712395/229981078-cc2d44e5-f28a-4b82-a32f-d50df16daab1.png)

Any Idea why this is happening ?

**Comment by 993499094** [comment] 2023-04-08 02:40
**I had the same problem.**

### **Reproduction steps**
`Blockly > Demos > Blockly Developer Tools`
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html

Change the default `name [block_type]` to `name [block_test]`

Save `"block_test"`
F5 `refresh the webpage`

Click on `"Block Library"` and select `"block_test"`.

Dialog Box: `You have unsaved changes. By proceeding without saving  your block first, you will lose these changes.`
-`YES`!

Console error:
`You can't make a block called block_test in this tool because that name already exists.
warnExistingBlock @ factory.js:`

**Comment by NeilFraser** [comment] 2023-04-10 13:59
Another external report: https://groups.google.com/g/blockly/c/AIC5qvOXAn4

**Comment by Apro123** [comment] 2023-12-28 03:31
A quick workaround is to rename the block to show the preview, then rename it back when done editing/viewing before clicking "Update" (if necessary)

**Comment by lancefisher** [comment] 2024-02-24 18:55
Another workaround is to clear local storage, then re-import your block library.

**Comment by cpcallen** [comment] 2024-07-01 12:41
Marking this as triage again because it [appears to be preventing people from updating to the new block factory](https://groups.google.com/g/blockly/c/DvGtlzGJaNY/m/PJWkG7IfFgAJ).

**Comment by cpcallen** [comment] 2024-07-26 17:12
I think this may be a duplicate of (or at least related to) #5570.

**Comment by tashee** [comment] 2024-09-06 15:14
Seems to be called from updateLanguage which marks the Blocklyblock as already created in Firefox but not in Chrome

**Closed** 2024-10-02 00:01 UTC
Labels: issue: bug, component: devtools, help wanted
