### ISSUE TITLE
Complementary "setDisabled(false)" needed?

### ISSUE THREAD

**Issue by acbart** [google/blockly#233] opened 2016-01-12 01:50 UTC
I'm not clear how this works without a complementary `setDisabled(false)` in the else component. It was needed in my own version. But it's possible that I broke something when developing, and my fix is unnecessary for others.

https://github.com/google/blockly/blob/b1b96e45dbe883231430f529b63df3a57a902600/core/flyout.js#L676

**Comment by slyfox75** [comment] 2016-01-12 02:01
I'm not sure how any of this works in still trying to figure out how to write in the souce code and make changes to the html to view in html format

Sent from my Windows Phone
________________________________

**Comment by carlosperate** [comment] 2016-01-12 08:41
The flyout gets regenerated every time it is opened, if the block limit has been reached, then it disables the blocks displayed on it.

**Comment by acbart** [comment] 2016-01-12 08:49
But for some of the games and applications, the fly out is permanently out.
What triggers the enable?

**Comment by carlosperate** [comment] 2016-01-12 12:17
Well, if there are not toolbox categories and the blocks are not redrawn, then they would not get disabled either on max count, unless there is another refresh mechanism in place.

I guess this should probably be tested by merging the "Maximum Block Limit" and "Fixed blockly" demos.

**Comment by NeilFraser** [comment] 2016-02-03 02:21
Really good question.  It had me stumped for a while.  Turns out this is a recent regression caused by this change:
https://github.com/google/blockly/commit/1026d353cedd23c63361f7057d462025d8f86904

**Comment by NeilFraser** [comment] 2016-02-03 02:21
Really good question.  It had me stumped for a while.  Turns out this is a recent regression caused by this change:
https://github.com/google/blockly/commit/1026d353cedd23c63361f7057d462025d8f86904

**Comment by NeilFraser** [comment] 2016-02-03 03:54
Fixed in the 2016 branch:
https://github.com/google/blockly/commit/0585cea1e3c7a16f75d1bbd3c5a918390377f70d

**Closed by NeilFraser** 2016-02-03 03:54 UTC
