### ISSUE TITLE
Support injecting Blockly into the shadowDom/Web Component

### ISSUE THREAD

**Issue by letrthang** [google/blockly#5230] opened 2021-07-27 03:39 UTC
I would like to suggest to have plan to support Web Component with Lit-Element.

**Comment by BeksOmega** [comment] 2021-07-27 14:12
Hello, could you provide some more info about this issue? For example:
  * What problem would this solve for you?
  * How would this solve the problem?
  * What are alternatives you've considered?

Once we have a bit more info, we'll be able to better prioritize this =)

Best,
Beka

**Comment by letrthang** [comment] 2021-07-29 17:41
Hi Beka,

Basically we need to add blockly to our project which is generated by `https://start.vaadin.com/welcome`

My js file to load blockly is: 
`https://github.com/letrthang/vaadin-flow-14-starter/blob/master/frontend/views/blockly-view.js`

and we got error:

![blockly_error](https://user-images.githubusercontent.com/13396193/127539142-0b6b9ec4-65b6-4cad-b493-43781b9f09ab.jpg)

And i think this issue is due to Blockly doesn't support Web component. The element  **blocklyDiv** is put inside the Shadow DOM, so it cannot initialize properly.

Full proj repo:
[https://github.com/letrthang/vaadin-flow-14-starter](url)

**Comment by BeksOmega** [comment] 2021-07-29 22:58
Thanks for providing more info! That makes a lot of sense. I've updated the title to provide a bit more info =)

For people trying to fix this:
It looks like inject checks whether the passed div is [attached to the current document](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/inject.js#L54), which causes the above error to be thrown. I'm not sure if this is necessary or not, since it's been there since the [beginning of time](https://github.com/google/blockly/commit/a8acffd81c520b83027eebedc45543f14c5a8059#diff-39225b1cb48f8fe24ff0610ab32534efef90308f1b9a3f0ee08622bddaf84549R38).

**Comment by letrthang** [comment] 2021-07-30 01:43
Thanks Beka for helping to update this issue. Hope we will have new release to fix it soon.

**Comment by cpcallen** [comment] 2021-08-09 17:10
> It looks like inject checks whether the passed div is [attached to the current document](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/inject.js#L54), which causes the above error to be thrown.

@NeilFraser: Does this check exist just to help confused programmers trying to `inject` Blockly into a DOM element that's not actually attached to anything, since they might otherwise wonder why doing so seems to have no effect?

Maybe the check should just be removed, or the `throw` replaced by a suitably-worded `console.log`.

**Comment by BeksOmega** [comment] 2021-08-14 01:25
Apparently dupe of #1114

**Closed by BeksOmega** 2021-08-14 01:25 UTC
Labels: help wanted, type: feature request
