### ISSUE TITLE
Blockly documentation

### ISSUE THREAD

**Issue by guidoPaglie** [google/blockly#523] opened 2016-08-05 17:55 UTC
Hi guys, i am using blockly to make a game and i wanted to ask where i can find all the functions, variables, etc i can get from blockly.

For example, i wanted to clear the workspace and it took more than the necessary to found that somebody used this( Blockly.mainWorkspace.clear() ).

Thank u in advance!

**Comment by acbart** [comment] 2016-08-10 15:07
I've been hosting a copy of the API docs here: https://dl.dropboxusercontent.com/u/23141976/blockly-documentation/index.html

This was pretty easy to generate with JSDoc. Perhaps the team should, at some point, have the build system automatically generating documentation? I wasn't planning on keeping that documentation up-to-date or anything, and it's probably already lagging behind.

**Comment by guidoPaglie** [comment] 2016-08-10 15:11
Thank u acbart!

**Comment by NeilFraser** [comment] 2016-08-24 10:20
Duplicate of #119.  (But it's valid.)

**Closed by NeilFraser** 2016-08-24 10:20 UTC
