### ISSUE TITLE
TypeError: Object doesn't support property or method 'blur'

### ISSUE THREAD

**Issue by kyoncy** [google/blockly#4440] opened 2020-11-09 07:40 UTC
## **Describe the bug**
Our product's Sentry catches lots of error events

```
Object doesn't support property or method 'blur'
```

![image](https://user-images.githubusercontent.com/24786802/98511613-4dcc0b00-22a8-11eb-946e-a652c7c3ffdb.png)

occurs at `WorkspaceSvg.prototype.setBrowserFocus`.
All of this error occurs on **IE11**.

According to users feedback, when this error occured, they will not be able to operate the Blockly block.

## **To Reproduce**
Sorry, I can't reproduct this error.

## **Expected behavior**
https://github.com/google/blockly/blob/8d5d2be0284a98f1a53423a5cb07d0a7e36a95c0/core/workspace_svg.js#L1816-L1818

I'm expecting to occur this error, In case of activeElement is SVGElement(`svg`, `path`)
So, suggest to change

```diff
-  if (document.activeElement) {
+  if (document.activeElement && document.activeElement.blur) {
    document.activeElement.blur();
  }
```

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 11.0

**Comment by rachel-fenichel** [comment] 2020-11-18 01:59
I found this page about focus/blur with SVG, but haven't dug in to check what the recommended solution is.

Skipping the `blur()` call will definitely help with not freezing, but we should also make it actually do the correct thing in IE.

**Comment by maribethb** [comment] 2020-12-07 18:53
I tried to reproduce this in Win-IE11 and couldn't. What I find strange is that, since svg elements can't be focused or blurred in ie, how does the svg originally become focused anyway? `setBrowserFocus` should be setting it to the parent of the svg and theoretically if one tried to focus the svg, they'd get an error there. So I'm not sure why exactly this could be happening, and I couldn't reproduce it. I tried all the methods I could think of that would call `setBrowserFocus` in the normal course of using Blockly, as well as calling it directly, and the activeElement was always the parent node, as expected.

Since it is unexpected behavior for the svg to be the focus anyway, I think it's okay to just add the check if `blur` exists. I can't think of anything else we even could do. So I opened https://github.com/google/blockly/pull/4506 with that fix.

Even with a fix coming, I'd still like to understand when this is happening, if possible. Do you have stack traces available? Maybe this happens from a particular caller?

**Comment by maribethb** [comment] 2020-12-14 19:19
I'm going to close this for tracking purposes since I think we've mitigated the issue, but I'd still be interested in seeing a stack trace if you have one. Thanks!

**Closed by maribethb** 2020-12-14 19:19 UTC
Labels: affects: browser, type: bug
