### ISSUE TITLE
Angle picker still live while disappearing

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3245] opened 2019-10-14 21:43 UTC
Mousemove is still active in the time between when the angle picker is dismissed and when it finishes animating.  The result is random numbers if the mouse is moved during this time.  Here's a video:
https://youtu.be/qYRY4ChOOps

Of note, the angle picker animates closed, whereas the note picker custom field (which also uses live-input mousemove) does not animate.  They should probably be consistent with each other.  I think the note picker not animating is a bug, but that bug also fixes this bug, in a "two wrongs make a right" kind of way.

Will hold back pushing Blockly Games since this makes things rather frustrating for the user.

**Comment by NeilFraser** [comment] 2019-10-14 21:57
Related: double-clicking a colour in the colour picker can result in the colour below the initially selected colour to be selected.  Not as severe an issue (though users are often known to double-click everything, including web links), but it shows that it affects all fields.

A general principle when creating any animation effect is to make the animation take 10 seconds, and torture test it with race conditions.  The trashcan lid, block disconnect wiggle, and connect ripple were are all tested like this.

**Comment by samelhusseini** [comment] 2019-10-14 22:13
Duplicate of https://github.com/google/blockly/issues/3235. Fixed by https://github.com/google/blockly/pull/3202. It was decided not to pull it in for this release.

**Comment by NeilFraser** [comment] 2019-10-14 22:58
Definitely a blocker on pushing Blockly Games.  It makes Bird and Pond basically unplayable.

**Comment by RoboErikG** [comment] 2019-10-14 23:11
@rachel-fenichel it will be pretty frustrating for a lot of users. How do you feel about cherry-picking the fix over to master and bumping the patch version?

**Closed** 2019-10-15 19:41 UTC
Labels: component: fields, triage, type: bug, type: regression
