### ISSUE TITLE
Foreignobject misalignment in Chrome 55/56 and Safari 10 for Mac

### ISSUE THREAD

**Issue by ewpatton** [google/blockly#897] opened 2017-01-31 15:10 UTC
On macOS 10.12.3, in Chrome 55 and 56, Chromium 58, and Safari 10, textarea elements for comments within a foreignobject tag appear at (6, 6) absolute coordinates relative to the Blockly svg frame if the value of the textarea is vertically longer than the comment bubble (see screenshot). This does not happen in Firefox 50.1 or 51 on macOS, nor does it happen in Chrome  55 or 56 on Windows 10.

![blocklyforeignobjectbug](https://cloud.githubusercontent.com/assets/1331253/22469882/6f90f440-e79b-11e6-883a-aaf07f2faa30.png)

Odds are that this is a bug in Webkit and likely needs to be handled upstream, but it is possible to update the x and y attributes of the foreign object with the appropriate transforms for it to appear in the right position (tested via the developer tools).

**Comment by picklesrus** [comment] 2017-02-06 21:40
I tried reproducing this on the mac I have (running 10.11 not 10.12) with Safari 10, Chrome 55 & chrome 56 but can't reproduce.  I'll be updating to 10.12 soon and will try again then.

**Comment by picklesrus** [comment] 2017-02-13 20:44
I tried this on mac os 10.12 and chrome 56 and safari but still couldn't reproduce.  I see the x=6 y =6 coordinates on the <foreignobject> tag though.  Changing them via chrome dev tools seems to put  the text area in the wrong place though so I'm hesitant to change it.  Closing for now, but if I'm missing something, please reopen!

**Closed by picklesrus** 2017-02-13 20:44 UTC
Labels: browser bug, bug, coordinates
