### ISSUE TITLE
Variable context menu create getter option prints out variable id instead of name

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#1740] opened 2018-03-28 06:25 UTC
### Problem statement

Create variable getter context menu option prints out variable id instead of variable name.
<img width="444" alt="screen shot 2018-03-27 at 11 22 10 pm" src="https://user-images.githubusercontent.com/16690124/38012309-c7fda5cc-3215-11e8-984d-559e1fac1625.png">

### Expected Behavior

Context menu options should say 'create "get test"'

### Actual Behavior

Context menu option says 'create "get VARIABLE_ID"'

### Steps to Reproduce

1. Start by dragging a set variable block onto the workspace
2. Right click on that block, and read the context menu options.

### Operating System and Browser

All

**Comment by samelhusseini** [comment] 2018-03-28 06:35
Issue here is that getFieldValue('VAR') is returning the variable id. Is that intentional?
Would the best fix here be to change calls to getFieldValue('VAR') to perhaps getField('VAR').getText() ?

**Comment by rachel-fenichel** [comment] 2018-03-28 17:41
Dupe of #1658, and it shows up on all of the blocks with this pattern.

Fixing the context menu option is trivial (just getText(), as you mentioned) but I also need to fix the generated XML that we use to make the new block--it needs to be based on the variable model and correctly include the variable id and type as well as name.

**Closed by rachel-fenichel** 2018-03-28 17:41 UTC

**Comment by rachel-fenichel** [comment] 2018-04-13 20:47
Fixed in #1777.
