### ISSUE TITLE
Namespace spam in shadow fields

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4515] opened 2020-12-09 04:04 UTC
Here is an example of generated XML that contains a superfluous `xmlns` attribute:
```
<value name="A">
  <shadow xmlns="http://www.w3.org/1999/xhtml" type="math_number">
    <field name="NUM">1</field>
  </shadow>
  <block type="variables_get">
    <field name="VAR" id="xxxxxxxxxxxxx">cos</field>
  </block>
</value>
```

I have access to thousands of such cases from Blockly Games (Blockly team ping me if you want full examples).  Note that this is always a shadow block that's being overridden by a normal block.

However, a cursory test in playground does not seem to be able to replicate this bug.  Sadly I don't have date stamps, so I can't identify when this XML was generated.  All I do know is that the top-level XML tag has the `xmlns="https://developers.google.com/blockly/xml"` which makes it relatively recent.

Is this an old bug that's been fixed?  Or is it still a thing?  Not high priority, but I thought it might ring a bell with active developers.

**Comment by BeksOmega** [comment] 2021-06-03 21:50
Dupe of #2899. Just going through all of the XML related issues and thought I'd flag it.

**Comment by rachel-fenichel** [comment] 2022-10-19 20:48
Closing because it does not reproduce in the playground.

**Closed by rachel-fenichel** 2022-10-19 20:48 UTC
Labels: issue: bug, low priority

**Comment by rachel-fenichel** [comment] 2022-10-19 20:52
Based on the information in #2899, this problem was solved by switching to using a consistent `xmlUtils.createElement` function instead of calling `document.createElement` directly.
