### ISSUE TITLE
Bug with workspace-dragging and block-selection under highly specific conditions

### ISSUE THREAD

**Issue by stevekrouse** [google/blockly#888] opened 2017-01-30 15:50 UTC
I've been working on a project that uses Blockly, and I recently pulled the new compressed Blockly files. Almost instantly I noticed a bug but it took me a while to figure out how to reproduce it. My application consists of Blockly programs with hundreds of blocks, so I'm often clicking and dragging the workspace furiously to get to where I need to in my Blockly code, and that's when the bug happens.

You can reproduce this bug on https://developers.google.com/blockly/

Step 1. Place a block to the left of x=0 in the workspace. This is as simple as dragging a single block slightly to the left of where the blocks normally start.

Step 2. Click on an empty place in the workspace and drag your mouse out of the Blockly editor. Release your mouse. (Now if you bring your mouse back over the Blockly workspace, you will see that Blockly still thinks your mouse is down and you are dragging presumably because it hasn't registered your mouseup event that was fired outside of the Blockly workspace.)

Step 3. Click on the blockly workspace to the left of x=0, to the left of the block you placed to the left of x=0. You will see the workspace jump to another position in a jarring way. 

Step 4. Try to select a block in your workspace to move or delete it. You will see that you cannot.

**Comment by stevekrouse** [comment] 2017-01-30 16:14
Upon further digging, this jarring movement I mentioned  in Step 3 seems to be caused by this function: https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/core/workspace_drag_surface_svg.js#L110

I did a git blame on that line and found that there was a large commit https://github.com/google/blockly/commit/e1cd21842a191bf9a2b3f90ad9f4c2d4436f58d1 that refactored the way dragging works. I pulled the code from right before this commit and it fixed the bug.

**Comment by picklesrus** [comment] 2017-01-30 17:00
Are you injecting blockly in an iframe? And then mousing outside of the iframe's bounds?

**Comment by stevekrouse** [comment] 2017-01-30 17:07
Yes, yes I am!

**Comment by stevekrouse** [comment] 2017-01-30 18:02
I see now that the Blockly demo I linked to above is also using an iframe. 

Is there a fix for this or is Blockly not supported in an iframe?

**Comment by picklesrus** [comment] 2017-01-30 18:26
Iframes should be supported, but sometimes cause annoying bugs like this :)
Now that I know how to reliably reproduce using an iframe, I'll dig in and see what we can do to fix this.  I hope to get back to you at some point this afternoon (pacific time) with more info.

**Comment by stevekrouse** [comment] 2017-01-30 18:27
Thanks @picklesrus! Much appreciated :)

**Comment by picklesrus** [comment] 2017-01-31 00:13
I don't have a work around for you yet (other than not using an iframe), but I do understand the problem and am still looking for a workaround. Is your parent of the iframe on the same domain as the iframe? 

I have an have an idea of how to fix it, but it is only 1/2 thought through at the moment so will take a bit more time to sort out.

Sorry for the not so satisfying update.

**Comment by stevekrouse** [comment] 2017-01-31 16:12
Thanks for the follow up! 

I can live with the problem for now and will maybe migrate away from an iframe eventually if it bothers me enough.

The parent of the iframe is indeed on the same domain of the iframe.

**Comment by stevekrouse** [comment] 2017-01-31 18:46
Removing the iframe did *not* fix this bug. Let me know if you have trouble reproducing it without an iframe.

**Comment by picklesrus** [comment] 2017-01-31 19:20
Hmm, Yeah, I might need some help reproducing.  Can you reproduce the problem on https://blockly-demo.appspot.com/static/tests/playground.html?

**Comment by stevekrouse** [comment] 2017-02-01 00:56
Ah, I have *another* iframe on my page that's screwing things up. If I mousedown on blocky and then move my mouse over to the other iframe and mouseup there, blockly doesn't detect it.

**Comment by picklesrus** [comment] 2017-02-01 01:19
Phew. That makes me feel slightly less crazy.
I have a potential fix in https://github.com/google/blockly/pull/899.  Feel free to grab it and see if it solves the problem.  We'll probably decide tomorrow whether it is a reasonable fix.

Background for why it could be a bad idea:
#899 has some assumptions about touch & mouse event behavior baked into it.  For example, if we were not receiving the touchend event on iOS (we currently are so it isn't a problem today), this would likely freeze up interaction. If we didn't have the touchend event from outside the iframe, The touch identifier for the initial touchstart would not be cleared by the last touchend since the touch identifiers would not match.

**Comment by picklesrus** [comment] 2017-03-23 23:33
This should be fixed now.

**Closed by picklesrus** 2017-03-23 23:33 UTC
Labels: type: bug
