### ISSUE TITLE
Deleting a block does not resize the workspace such that the view is within the content bounds

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7815] opened 2024-01-29 21:41 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you delete a block from the workspace, the workspace viewport does not move such that the viewport is within the new content bounds.

### Reproduction steps

1. Open the playground
1. Drag a block into the workspace.
2. Drag the workspace such that the block is at the top of the workspace.
3. Drag a block onto the bottom of the workspace.
4. Drag the workspace such that the block is in the middle of the workspace.
5. Delete the second block.
6. Drag the workspace.
7. Observe how the view jumps so the original block is within the bounds of the view.

### Screenshots

[Screen recording 2024-01-29 1.39.54 PM.webm](https://github.com/google/blockly/assets/25440652/fe4f7560-62ff-494a-8efa-35df8ca5020b)

### Additional Info

This makes the minimap plugin look weird, because it does properly resize when the block is deleted.

**Comment by BeksOmega** [comment] 2024-05-17 20:43
I'm going to punt on this because resizing the workspace on delete actually has performance implications if we're (e.g.) clearing the workspace

**Comment by gonfunko** [comment] 2024-11-15 21:26
Duplicate of #7866

**Closed by gonfunko** 2024-11-15 21:26 UTC
Labels: issue: bug, component: coordinates
