### ISSUE TITLE
Two ways to create vars mean user can create the same var with different casing

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1115] opened 2017-05-19 20:54 UTC
**Steps**
1. Create a variable name "ABC"
2. Create a new function
3. Mutate the function to take in argument "abc"
4. See function block describes variable "abc", but variable blocks only provide "ABC"

<img width="536" alt="screen shot 2017-05-19 at 1 41 47 pm" src="https://cloud.githubusercontent.com/assets/9916202/26266455/39751324-3c9a-11e7-81ef-d614c96e5c08.png">

**Expected**
Able to find a variable block that matches the label on the function. That is, for all variable names that map to a single variable (via `toLowercase()`), there should be a single user representation used by all blocks.

In this case, the function argument (created second) should probably replaced with the existing matching function.  However, that heuristic does not help when loading XML files that declare multiple variations of a variable.

**Comment by rachel-fenichel** [comment] 2017-05-19 21:07
At step 3 the ABC variable should be renamed to abc.  We're supposed to use the most recent casing of the variable name.

Possibly will be resolved by switching to dropdowns for input names.

**Comment by rachel-fenichel** [comment] 2017-05-19 22:41
@marisaleung

**Comment by BeksOmega** [comment] 2021-08-14 01:23
Could not reproduce. ABC gets renamed to abc when you complete adding the procedure parameter.

**Closed by BeksOmega** 2021-08-14 01:23 UTC
Labels: type: question, component: variables
