### ISSUE TITLE
Field.text_: Documentation vs use

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2720] opened 2019-07-27 14:01 UTC
Our documentation is very clear about not using Field's `.text_` property.

> "Warning: Never access the text_ property directly, instead access it through getText. It is maintained for backwards compatibility."
> "Caution: Never use the text_ property to access or edit the text of your field. It is maintained for backwards compatibility."
https://devsite.googleplex.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating

> "We recommend that you never access or update the text_ property of your field directly."
https://devsite.googleplex.com/blockly/guides/create-custom-blocks/fields/customizing-fields/upgrading

Yet our codebase uses it all over the place:
* Blockly.Block.prototype.toString
* Blockly.FieldAngle.prototype.onMouseMove
* Blockly.FieldDropdown.prototype.doValueUpdate_
* Blockly.FieldImage
* Blockly.FieldImage.prototype.initView
* Blockly.FieldImage.prototype.setAlt
* Blockly.FieldTextInput.prototype.doValueUpdate_
* Blockly.FieldTextInput.prototype.showPromptEditor_
* Blockly.FieldTextInput.prototype.widgetDispose_
* Blockly.FieldVariable.prototype.doValueUpdate_
* Blockly.FieldVariable.prototype.refreshVariableName

Is `.text_` a fundamental part of fields that needs to be used whenever one creates a new field?

**Comment by BeksOmega** [comment] 2019-07-27 14:32
So here was my thought process (which may or may not be correct):

Setting the text_ property every time a new value gets set is inefficient. For fields that display text it's necessary, but for fields that only display text when they're collapsed you're doing extra work you don't need to do. The [turtle field](https://developers.google.com/blockly/guides/create-custom-blocks/fields/anatomy-of-a-field#other_display_modes) is a good example of this.

Moving outside devs to use getText is also good because it keeps peoples code more organized. Instead of having text_ updates split between doValueUpdate_, doValueInvalid_, and render_ we can tell people, "just handle that inside getText".

Now the reason text_ wasn't removed anywhere in this codebase is because we can't know how, if, where, or why any outside developers are accessing the property and I didn't want to be the one to break everyone. (It remains to be seen whether I did or did not break everyone lol)

If you want to pull text_ out of this codebase, I'm totally down for that (as long as you agree to take part of the blame :P ).

And if you have a different opinion about text_'s use I'd love to discuss =) This just explains what I was thinking when I made these decisions.

**Comment by samelhusseini** [comment] 2019-08-07 22:48
We had a design discussion about this the other day, and wanted to just summarize our thoughts here. The ultimate goal is to get rid of setText as it's confusing to developers which one to use to set the value. We'd rather the text on the block be derived from the value through a getDisplayText method. 

Currently, many of our internal fields are still setting text directly, and we need to shy away from that. However, there's still a need to "set" the text of the block during editing to a temporary value so that the block grows as the user types into the text field. 

## Proposal

- Get rid of ``setText`` and any notion of ``text_`` in field.js
- In field_textinput introduce the concept of a temp value and add a ``setTempValue`` method
 - setValue will wipe the temp value and call doValueInvalid/Update
 - getDisplayText will return the temp value if its set, otherwise return the field's value.

**Comment by BeksOmega** [comment] 2019-08-08 15:58
> * Get rid of `setText` and any notion of `text_` in field.js

I love it! Getting rid of `text_` sounds rad and this seems like the perfect time to do it!

> * In field_textinput introduce the concept of a temp value and add a `setTempValue` method

So the temp value is meant to be the value displayed on the block right? If so I think it would be better to name it `displayValue_`. This makes more sense to me because the fields "actual value" isn't getting temporarily overriden (getValue should still return something valid for use in code generation) it's just that the display is different.

An added bonus of using this naming is that `getText` turns the `value_` into a string, and `getDisplayText_` turns the `displayValue_` into a string.

> * setValue will wipe the temp value and call doValueInvalid/Update

Hmm so I really like this, but my problem is that `setValue` is a [template method](https://en.wikipedia.org/wiki/Template_method_pattern) and shouldn't be overriden by individual fields. Luckily I think there's a way the same thing can be achieved just using the provided hooks :D

Thinking about a field in general (since the text input field has the added complexity of needing to ignore changed values which I don't want to get into right now):

`doValueInvalid` can update the `displayValue_` (if the field wants to display invalid values).

`doValueUpdate` can update the `value_` *and* the `displayValue_`.

Then if we make a little change this:

> * getDisplayText will return the temp value if its set, otherwise return the field's value.

And instead say:
`getDisplayText_` will always return based on the fields `displayValue_`

We arrive at the same functionality without having to edit the `setValue` function :D

---

If you want an example of a `text_`-less field the [turtle field](https://github.com/google/blockly/blob/master/demos/custom-fields/field_turtle.js) is already `text_`-less. It uses a very similar pattern to the one described above =)

Also I wanted to note, I'm happy to impliment whatever system is decided on!

**Comment by samelhusseini** [comment] 2019-08-08 16:32
## Temp value: 
I think calling it the displayValue is misguiding. Even though in some circumstances (while editing) it is the display value. The temp value is way to bypass all the checks we do on setting the display value including running through getDisplayText_ and set something in the textElement. In effect a lot of this is similar to what setText was attempting to do, the thing we're trying to tackle here is making sure developers know what public methods to extend for their fields. Hence why we're moving this pattern away from ``field.js`` and into ``field_textinput``. The need for a temporary value in order to easily set the width of the block while editing is a field_textinput problem, and moving it there and making everything private means we can move away from that pattern once we come up with a better way to size fields while editing. 

## Not overriding setValue
That sounds good to me. I would rather fields use the methods available as well.

 ## getDisplayText
getDisplayText_ currently derives a value based on this.text_. We'd want to move away from that and have it derive the value based on this.value or better yet take in a value and derive the display text based on that. This gives us a little more flexibility in subclass render methods to pass it a different value than this.value_.

Question for you, why doesn't setValue set this.isDirty and the this.value and instead rely on doValueUpdate to do it? Those look to me like internal values and we shouldn't rely on subclasses to set them.

**Comment by BeksOmega** [comment] 2019-08-08 20:35
I'm a little bit confused about what you're proposing. Let me try and rephrase it back to you, and then you can tell me where I'm wrong =)

- The temp value is what gets displayed while editting.
- It can also be used in general to override what's being displayed, and in doing so it bypasses all checks:
```
setTempValue(value) {
  this.tempValue_ = value;
  this.isDirty_ = true;
  this.forceRerender();
}
```
- Bypassing all checks makes it more efficient.
- the `setTemp` function will be called whenever the `onHtmlInputChanged` function is called, instead of calling `setValue`

---

- The value is what is used for code generation.
- It is also what is used for displaying when the field is not being editted.

---

- `getDisplayText` should return based on the temp value if it is set, and the value if it is not.
- Alternativly `getDisplayText` could be made into a [utility function](https://github.com/google/blockly/issues/1624) that returns based on a value it gets passed.

---

-  The problem of temporarily displaying something different than the value is not generalizable, and hence should be solved on the text input field alone.

**Comment by samelhusseini** [comment] 2019-08-08 21:18
> I'm a little bit confused about what you're proposing. Let me try and rephrase it back to you, and then you can tell me where I'm wrong =)
> 
> * The temp value is what gets displayed while editting.
> * It can also be used in general to override what's being displayed, and in doing so it bypasses all checks:
Yes, only in text fields. I don't know about generalizing it, if for whatever reason some custom field also needs this ability to override the display text, then sure it can be implemented in a similar way, but the assumption here is this isn't a common problem. (Other alternatives to generalizing this is creating a class that goes in between field and field_textinput that adds this functionality, but at this point let's solve this in field_textinput).
> 
> ```
> setTempValue(value) {
>   this.tempValue_ = value;
>   this.isDirty_ = true;
>   this.forceRerender();
> }
> ```
Yes, something like that.
> 
> * Bypassing all checks makes it more efficient.
> * the `setTemp` function will be called whenever the `onHtmlInputChanged` function is called, instead of calling `setValue`
It's not a question of efficiency. The reason we need to bypass all checks in the case of input fields is a user might type something that's invalid. The ``this.value_`` should only ever be a valid value, but in the case of text fields we need the concept of an intermediate temporary value that getDisplayText can use instead of value as we want to temporary (while the user is editing) set the display text to the "invalid" value. (otherwise bad things happen and we don't get the right sizing of the text field).
Yes to your second point, we would call setTempValue in onHtmlInputChanged instead of setValue. 
This raises a question of when do we commit the value? I'll try to answer that later.
> 
> * The value is what is used for code generation.
> * It is also what is used for displaying when the field is not being editted.
What gets displayed on the field is the result of getDisplayText. I think of fields kind of like HTML selects, they have a text/value combo. In some cases they could be the same, but sometimes they're not. In order to avoid developers having to maintain the lifecycle of both a text and a value property (the problem we have today), I'd rather have the display text be derived from the value, so whenever we render and need to display something on the screen, we call getDisplayText and that converts whatever the value is at the time into the text property. 
> 
> * `getDisplayText` should return based on the temp value if it is set, and the value if it is not.
> * Alternativly `getDisplayText` could be made into a [utility function](https://github.com/google/blockly/issues/1624) that returns based on a value it gets passed.
Yes, but not in the generic case. Since this "temp" value problem is only a text field problem, I'd rather limit it to that, and override `getDisplayText` in `field_textinput.js` and introduce the concept of a temp value that is both set and used internally in field_textinput.
> 
> * The problem of temporarily displaying something different than the value is not generalizable, and hence should be solved on the text input field alone.
Totally!

## Committing. 
Current fields commit their value as soon as it's changed. In addition, they only do so if the value is valid. So thinking about this a little more, just saying that we call setTempValue when an input is changed isn't enough. As we need to pass through setValue to a - set the value if it's valid, and b- show the validator feedback as we type. 

Since this is only a problem when the value is invalid, perhaps we could go about this another way. Maybe we can override doValueInvalid_ to set the temporary value there, and continue as planned with getDisplayText_ showing the temporary value if it's set. I'm not sure if this would work, but something to keep in mind.

**Comment by rachel-fenichel** [comment] 2019-08-09 00:43
#2496 is also related.

**Comment by BeksOmega** [comment] 2019-08-09 16:02
> The problem of temporarily displaying something different than the value is not generalizable, and hence should be solved on the text input field alone.

It may not be common problem with the current _built in fields_, but I promise you it _is generalizable_.

Take the turtle field for example:
![Validator_Turtle](https://user-images.githubusercontent.com/25440652/62785609-d80a3b80-ba75-11e9-9fe8-ca72e2221cb7.gif)

As you can see the turtle is temporarily displaying something different than the value. It is displaying that it has a crown, but when we export to XML we can see that the value is actually stovepipe.

**Anytime a field wants to display invalid values it will run into this problem.**

I think this is the fundamental misunderstanding I tried to explain in my first reply to your proposal.

---

You mentioned:
> we can move away from [this] pattern once we come up with a better way

I have already provided you with that better way.

My additions to your proposal:
* Allow fields to display values that are different than their actual values in a generalized way.
* Use only methods that are already exist.
* Integrate well with the current setValue template method.
* Carry a minimum of overhead. In essence they add a single property to the abstract field.

And I know how to implement it, because:
1) I have already set up the text input field to easily transition to this new method.
2) I have already implemented it on the turtle field.
3) I know the text input field (and its quirks) intimately.

As you can see from my first post adding to your proposal, I agree with lots of your points, and I think many of your ideas for implementation were great as well.

I just have an understanding of the system which comes with building it, testing it, and using it (I've been building lots of custom fields to demo at the summit). I'm not infallible (obviously lol), but I know what I'm talking about.

---

I think the problem is that we've been talking too abstractly. How about I spin up a demo so that we can talk about something more concrete? That sound cool to you?

**Comment by samelhusseini** [comment] 2019-08-09 16:58
Thanks for bearing with me @BeksOmega. First off, I'd very much appreciate a demo. My reservation with making this generic has been to not end up with a solution that's pretty much the same as what we have with ``this.text_`` just renamed to a ``displayVaue`` or a ``tempValue``. 

> Allow fields to display values that are different than their actual values in a generalized way.
I think that's a great idea, instead of having the field_textinput have to set the ``this.text_`` field directly in order to "hack" the field sizing, providing a more generic way to replace what is shown in the display would be great. I don't see how you can do that with a single property on the field (unless that property is a DOM element), but please feel free to go ahead with a demo, I think that will give me a much better idea of your proposal.

**Comment by BeksOmega** [comment] 2019-08-09 22:24
Ok @samelhusseini demo has been posted. Don't feel like you have to look at it today! I do realize it's Friday hehe.

**Comment by BeksOmega** [comment] 2019-08-16 15:49
Thank you guys for working with me and taking a look at my demo. Since the original proposal is still the prefered solution I will work up a PR for it over the weekend.

If instead you would like someone else to handle it, that's cool too. : )

**Comment by RoboErikG** [comment] 2019-09-16 21:22
developers.google.com/blockly needs verification, otherwise done.

**Comment by samelhusseini** [comment] 2019-09-23 17:45
CL out to update documentation accordingly.

**Comment by samelhusseini** [comment] 2019-09-23 18:10
Documentation updated and will be published in the next release.

**Closed by samelhusseini** 2019-09-23 18:10 UTC
Labels: component: fields, type: cleanup, type: documentation, type: question
