### ISSUE TITLE
API for accessing generated function code

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2317] opened 2019-02-26 23:57 UTC
### Problem statement

The built in function blocks don't return code from their generators. Instead it puts the code in an internal array that gets used to declare functions at the top of the code. This means when you generate code for a single block on a function nothing is returned. The single block code generation should probably return the function's code even if the standard generation path doesn't.

See https://groups.google.com/forum/#!topic/blockly/C5MMgkU48S8 for additional discussion.

### Steps to Reproduce

1. Start by..
2. Next, do..

### Stack Traces

```
Replace with error stack trace.
```

**Comment by surajguduru** [comment] 2024-08-01 13:00
Hey @RoboErikG I would like work on this issue. Can you assign it to me ?

**Comment by BeksOmega** [comment] 2024-08-02 17:46
Sorry @surajguduru But I think this requires a bit more design before it can be worked on.

Closing this as a dupe of https://github.com/google/blockly/issues/7326

**Closed by BeksOmega** 2024-08-02 17:46 UTC
Labels: help wanted, issue: feature request, component: developer apis
