### ISSUE TITLE
"Allow statements" checkbox not working

### ISSUE THREAD

**Issue by vicng** [google/blockly#835] opened 2017-01-18 03:33 UTC
In Blockly Playground, drag a function block with a return statement. Open the mutator and click on the "allow statements" checkbox. Nothing happens.

**Comment by rachel-fenichel** [comment] 2017-01-18 19:01
Dupe of #797, which is a dupe of #742, which is fixed in scratch-blocks by https://github.com/LLK/scratch-blocks/pull/733.  I need to evaluate if that fix works in blockly.

**Closed** 2017-01-18 19:02 UTC
Labels: bug
