### ISSUE TITLE
Flyout can obscure workspace (making it unclickable)

### ISSUE THREAD

**Issue by PreethiBh** [google/blockly#4519] opened 2020-12-11 06:13 UTC
**Zoom out option is not clickable when zoomed in to maximum on Blockly Multi Playground (LTR, RTL, Start, End, Vertical)** 

**When the complete page is at 100 percent resolution - The zoom in option should work only till these signs  "+, -" , so that the zoom out "-" option is clickable.**

**Steps to reproduce the behavior:**
1. Go to 'http://google.github.io/blockly/tests/multi_playground.html?toolbox=simple'
2. Click on '+' zoom in option on LTR, RTL, Vertical to its maximum
3. Try to access the zoom out "-" option
4. The zoom out option is clickable to zoom out of the page, and the complete page has to be refreshed

**Expected behavior**
The zoom out option should be in the posting to click even after magnifying LTR, RTL to their maximum zoom in

**Screenshots**
![Screenshot 2020-12-11 at 11 14 18 AM](https://user-images.githubusercontent.com/72138408/101868714-f4efdb00-3ba3-11eb-8d1c-dc15e0787960.png)

![IMG-2880](https://user-images.githubusercontent.com/72138408/101869710-19e54d80-3ba6-11eb-86a3-ff07c2a29c8f.PNG)

**Desktop (please complete the following information)**
 - Chromebook
 - Browser [chrome]
 - Version [87.0.4280.88]

**Smartphone (please complete the following information)**
 - Device: [iphone 7plus]
 - OS: [13.6.1]
 - Browser [safari]

**Comment by moniika** [comment] 2021-03-18 17:54
This zoom in behavior can be observed in any small Blockly workspace.

I think it's ok that the zoom controls are obscured, but there is a problem with the Blockly workspace potentially being completely obscured such that the user can no longer click on the workspace to close the flyout. The workaround for this is that the user can click on the toolbox category to hide the flyout, but that isn't necessarily intuitive.

**Comment by BeksOmega** [comment] 2021-06-28 16:32
I think the zoom controls being obscured is a bit of an issue, because this issue also occurs in workspaces that use a simple toolbox, where it is impossible to close the flyout.

Perhaps the zoom controls should be z-indexed above the flyout? But I'm not sure if the way the flyout is injected makes that possible or not. If z-indexing is a valid solution, this is related to #1188

**Comment by BeksOmega** [comment] 2021-07-07 14:05
A similar problem can also occur if the user puts too wide (vertical flyout) or tall (horizontal flyout) of a block in the trashcan/backpack. The flyout gets so large that the workspace is obscured, and the only way to close it is by pressing esc.

I think the way to deal with this is to give the flyout a maximum width/height (maybe assignable by the developer?) after which the flyout gains a horizontal (verttical flyout) or vertical (horizonal flyout) scrollbar.

Related forum issue: https://groups.google.com/g/blockly/c/bpU_UVB7vhg/m/7LY5_xQOBAAJ

**Comment by gonfunko** [comment] 2024-09-10 22:43
Duplicate of #4715.

**Closed by gonfunko** 2024-09-10 22:43 UTC
Labels: issue: bug, low priority
