### ISSUE TITLE
Clicking on document should call Blockly.hideChaff

### ISSUE THREAD

**Issue by ronniesir** [google/blockly#2066] opened 2018-09-25 10:13 UTC
when i finish input text,i want to make the workspace get focus

**Comment by NeilFraser** [comment] 2018-09-25 10:27
Help me understand what you mean by focus (it's an overloaded term).  If a workspace had the focus, what would you be able to do?

**Comment by ronniesir** [comment] 2018-09-26 01:34
![image](https://user-images.githubusercontent.com/3816871/46051792-a645fa00-c16d-11e8-9f26-f8e6fd81495d.png)
![image](https://user-images.githubusercontent.com/3816871/46051855-076dcd80-c16e-11e8-8d57-770d9c69bfb8.png)

I input text '123' then switch another page.the text '123' still show. when the input lose focus the text show nomal.so i want to make the workspace get focus

**Comment by NeilFraser** [comment] 2018-09-26 02:32
I think I understand.  Allow me to rephrase the issue.

Problem:
WidgetDiv doesn't get unfocused when page elements outside Blockly are clicked.

Steps to recreate:
Click on a text or numeric input.  Field becomes editable as expected.
Click on the page body (not Blockly).  Field does not lose focus.
Click on workspace (Blockly).  Field does lose focus.

Sounds like there needs to be an event handler on the body to hide chaff.  I'm pretty sure this was the case a long time ago, and that this is a regression.  But if that's the case, it was so long ago that our old reference copy of Blockly Games doesn't show it.

**Comment by ronniesir** [comment] 2018-09-26 02:55
Your description is very exact.
I want to know if this problem will be fixed.

**Comment by alschmiedt** [comment] 2019-04-11 18:40
There were multiple attempts to fix this issue: #2359 and #2286. However, both were reverted because they caused other issues: #2312 and #2362 . We have decided that adding a 'mouseup' event listener at the document level has the potential to cause too many side effects. The current way around this is for the user to add an event listener on their own div that will call Blockly.hideChaff().

**Comment by rachel-fenichel** [comment] 2019-07-01 20:57
Closing this issue: developers should call Blockly.hideChaff() when the user starts doing things outside of the area that Blockly manages.

**Closed by rachel-fenichel** 2019-07-01 20:57 UTC
Labels: affects: develop, affects: master, type: feature request, wontfix

**Comment by BeksOmega** [comment] 2020-03-06 20:17
Do you think this could be fixable now since Blockly no longer depends on Closure for its context menus & other UI components? I'm wondering if it might be fixable now since you should have total control of the event handling. @rachel-fenichel @samelhusseini
