### ISSUE TITLE
Blockly in an iframe does not grab focus on click

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#904] opened 2017-02-02 19:40 UTC
This means that keyboard listeners don't fire.  See #891 for one example.

**Comment by rachel-fenichel** [comment] 2017-02-02 19:42
We should eventually fix this, but in general Blockly doesn't need to be used in an iframe.

**Comment by stevekrouse** [comment] 2017-02-02 20:53
Thanks for making this!

For reference, when I took blockly out of an iframe, the issue mostly stopped happening.

However, there's another iframe on the page, the output of the blockly code, so my users can see the result of what they're making. If you play around with the output and then try to delete a block, the delete key doesn't work.

Also to be more specific, it's not just the "first click." You can click on blocks multiple times and blockly still won't grab focus. Only clicking on the toolbox or other such actions grab focus.

**Comment by ctrowat** [comment] 2017-03-02 18:35
We are using blockly outside of an iframe and also noticing that it does not grab focus when clicking on blocks.  We are using master branch from January 11, 2017.  Is there a workaround for this?  It causes some unfortunate behaviour when focus remains in a text box and the user is pressing delete to get rid of blocks.

**Comment by picklesrus** [comment] 2017-03-03 00:47
@ctrowat Hmm, I haven't seen it without the iframe.  Do you have a link I could play with? Or can you reproduce it on this page that has an input box: https://blockly-demo.appspot.com/static/tests/playground.html?

No idea if this will work or if you'd have the info do to this at the right time, but if you call blur() on your text node, does that solve the problem?

**Comment by ctrowat** [comment] 2017-03-03 15:16
It is happening for me there as well.  To recreate the issue please do the following:

1) Drag a block from the bar at the top into the workspace, say Logic > if/do
2) After placing it in the workspace click into the large text box on the left
3) Enter some text in the text box
4) Now click on the block you placed earlier and drag it to a new position
5) Press the delete key


At step 3 I still see the block as highlighted even though the Blockly control has lost focus
At step 4 I can still see the text input box as highlighted even though it should have lost focus
At step 5 nothing happens because the delete key is going to the text box and not the Blockly control
In order to delete the block I have to click into something interactive, such as a text input or the toolbox.  If I only click on blocks or drag around blocks the Blockly control does not get focus and the delete key is ignored.

I am currently testing on Chrome 56.0.2924.87 which shows as the most recent version.  The issue also occurs on my computer in IE11 11.576.14393.0 and Microsoft Edge 38.14393.0.0 and it is happening for everybody in my office who has tried this including too many different browsers and OS versions to list.

On a side note, can we please bump this bug up from being "low priority" since I can show it happens outside of iframes and it also affects keyboard copy and paste (ctrl+c / ctrl+v) and has visual issues as well (such as blocks showing as highlighted when they don't have focus)?

**Comment by rachel-fenichel** [comment] 2017-03-03 19:01
Definitely not low priority when it happens outside of iframes.  Our crack team of code monkeys* is hard at work trying to find the root cause.

*me and pickles

**Comment by picklesrus** [comment] 2017-03-03 20:00
This code monkey seems to have caused this way back in May 2016 by adding a preventDefault  in https://github.com/google/blockly/commit/ca16d1fefe9d1725b770469975857ce2a9f5e323. Sour pickles, sour :(

@rachel-fenichel thinks the touch handling code that has been refactored since then now depends on this behavior though so undoing likely won't work well on touch devices.

Instead I will probably add this line of code:
this.getParentSvg().focus();
here:
https://github.com/google/blockly/blob/master/core/workspace_svg.js#L1341

Look for a PR against develop in a few hours.

**Comment by ctrowat** [comment] 2017-03-03 20:02
Excellent!  Thanks for the hard work and dedication!

Any idea how long that would take to make it's way into the master branch?  We don't have a Blockly build environment and have been using the precompiled js files from the master branch - we're a bit shy of branches labelled "develop" as we're developers ourselves :)

**Comment by picklesrus** [comment] 2017-03-04 01:17
Fix submitted to develop.  We are due for a develop->master push, but there are some bug fixes we want to include that aren't quite ready yet so it'll probably be few more weeks. I understand your hesitance w.r.t develop :)

I don't have time to test the fix thoroughly enough to believe it is ready to push today, but we can either provide you a version of blockly_compressed.js with the change cherrypicked in or potentially cherrypick it to the master branch next week.

Another thought:
I don't know your app, but if you have a way of knowing when the user is done using the text area on your page, you could add a temporary hook there and call blur() on the element.

**Comment by ctrowat** [comment] 2017-03-06 17:21
Thanks for the detailed response!

Would it be possible to get a cherrypicked build?  We are presently undergoing regression testing prior to a release and QA would really like to get their hands on the version we will ship as quickly as they can.

I understand about the remaining issues in develop - that is also what has kept us from using the develop branch right now :)

**Comment by picklesrus** [comment] 2017-03-06 19:32
@ctrowat:  If you give us an email address (or send one to fenichel@google.com), we can send along the blockly_compressed file with the cherrypick in it.

**Comment by ctrowat** [comment] 2017-03-07 17:20
Sorry to drag this back up but testing with the fix implemented we are getting an error under Internet Explorer 11:
Object doesn't support property or method 'focus'

Works great on FF and Chrome though!

**Comment by picklesrus** [comment] 2017-03-07 17:32
:( Sorry about that. I (obviously) hadn't tested it in IE yet.

Luckily I had set aside this morning to test the current develop branch and deal with IE (we currently have a separate problem in IE 10 too).

**Comment by picklesrus** [comment] 2017-03-07 18:25
Update before I have to context switch for a bit.  I will try and get back to this before the end of the day.

It appears IE doesn't support calling focus on <svg> elements.
I can solve this problem in IE by calling this.getParentSvg().parentNode.focus() instead of this.getParentSvg().focus() as I did in  https://github.com/google/blockly/commit/ab042d4dd86b9a9c4d629f5b9c8e104a70f33f02.  That puts  focus the <div id="injectionDiv"> html element instead. However, what works in IE doesn't work in Chrome. Mild shock :)

There is a potential workaround we could used described here: https://allyjs.io/tutorials/focusing-in-svg.html#focusing-svg-elements, but it makes me a little sad...

**Comment by picklesrus** [comment] 2017-03-07 18:32
whoops, sent too soon and forgot to include this info:
this.getParentSvg().parentNode.focus() works in IE 11 but not Edge
document.activeElement.blur() works in Edge but not IE 11

**Comment by picklesrus** [comment] 2017-03-08 03:00
I have a solution for this that seems to work on Edge, Chrome, Firefox, Safari, and IE11.  I still need to run some more tests on mobile devices before I send a PR though.

**Comment by ctrowat** [comment] 2017-03-08 15:22
We feel your pain - IE and Edge have been the cause of many words shouted in anger in our office.  Hopefully your new fix does the trick, please let us know when it is ready!

**Comment by picklesrus** [comment] 2017-03-08 22:37
Fix is ready.  I don't recommend pulling from develop yet - there are more IE bugs we need to work through there... 
@ctrowat: Look for a rebuilt file soon.  Sorry for the hassle. Hopefully this does the trick for real this time.

**Comment by ctrowat** [comment] 2017-03-09 22:29
We have done some testing with this new build and the issue we had is solved but it has triggered a new (and slightly hilarious) issue - when rendering a blockly workspace in IE the page scrolls to the workspace after it draws.  So on a page where we might have 8 or 10 blockly controls that render at different times IE goes completely nuts scrolling all over.

I'm going to try to set up a blockly build environment and see if I can be more useful but I thought I should share this with you in case the fix is very obvious to you.

Thanks again for working on this!

**Comment by picklesrus** [comment] 2017-03-10 18:34
Wow. So sorry about the back and forth!  I believe the culprit are these calls to markFocused in Blockly.inject: https://github.com/google/blockly/blob/develop/core/inject.js#L68
https://github.com/google/blockly/blob/develop/core/inject.js#L215
I think the main purpose of those calls is to set Blockly.mainWorkspace.

I could remove them and assume that the mousedown on the workspace will set it... but I'm not convinced that is safe given how many times I've already messed this up. I could add a helper to set the main workspace explicitly and call that there instead.  I'm going to try that out and see if it helps.

**Comment by ctrowat** [comment] 2017-03-10 19:45
It's no problem - I appreciate your quick replies and willingness to look into this!

I was able to set up a blockly build environment so you will no longer have to do builds just for me however I have not yet gotten to the point where I understand enough of the event system to feel confident tackling this issue.

**Comment by picklesrus** [comment] 2017-03-10 23:04
Another hopeful fix submitted... Thanks for your patience and reporting these bugs!

Develop still has some other ugly IE bugs so I'd advise a cherrypick of 9b98573 and 847d83e to master for a build.  Sadly the two will likely conflict in the setBrowserFocus method.

**Comment by picklesrus** [comment] 2017-03-22 21:49
Closing since this works on develop now and we're clearing out bugs for a merge with master soon.

**Closed by picklesrus** 2017-03-22 21:49 UTC
Labels: bug
