### ISSUE TITLE
The default image in a image dropdown doesn't change when selecting an option.

### ISSUE THREAD

**Issue by theyork2000** [google/blockly#1232] opened 2017-07-20 01:59 UTC
I created a drop down input with images as the options. The default shows the first image, but when selecting a different image it doesn't update the default value to show the new image. It works perfectly fine if there is text in there.

If there is a mix of text and image options you can select a text option and then an image option and it switches to that image, but not from an image to another image.

I noticed the same issue in the block factory.

**Comment by rachel-fenichel** [comment] 2017-08-18 20:10
I'm closing this as a duplicate of #1047, but I'll take a look at it again.

**Closed** 2017-08-18 20:45 UTC
Labels: affects: browser, type: bug
