### ISSUE TITLE
field_image opt_onClick not work

### ISSUE THREAD

**Issue by duzc2** [google/blockly#2034] opened 2018-08-30 04:36 UTC
### Problem statement
when use a opt_onClick to field_image
it does not work when the image clicked.

### Expected Behavior

invoke the function when click the image

### Actual Behavior

nothing

### Steps to Reproduce

1. 
.appendField(
            new window.Blockly.FieldImage('https://www.gstatic.com/codesite/ph/images/star_on.gif', 15, 15, '*', function () {
                alert(1);
            }));
2. 
click the image
### Additional Information
to fix it
replace Blockly.FieldImage.prototype.maybeAddClickHandler_ by :
Blockly.FieldImage.prototype.maybeAddClickHandler_ = function () {
    if (this.clickHandler_) {
        this.mouseDownWrapper_ =
            Blockly.bindEventWithChecks_(
                this.fieldGroup_, 'mousedown', this, this.clickHandler_);
    }
};

**Comment by AnmAtAnm** [comment] 2018-08-31 17:51
Dupe of #1887

**Closed by AnmAtAnm** 2018-08-31 17:51 UTC
