### ISSUE TITLE
Feature Request: Scroll to center on a block

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#1013] opened 2017-03-30 18:28 UTC
How can I scroll the selected/any block into view?
I'd like to set the scrollbars somehow that the block (at least its top left corner) will be in the center of the visible part of the workspace. 

I've tried
- `Blockly.mainWorkspace.scrollbar.set( , )`
- `block.getRelativeToSurfaceXY()` fields
- `Blockly.mainWorkspace.getMetrics()` fields
- `Blockly.mainWorkspace.scale`

and a lot of expressions combining these (+, -, /2), but without success.
Is the coordinate system documented somewhere?

I give up. Please help.

**Comment by rachel-fenichel** [comment] 2017-03-30 21:10
Hi bkisdi,

Are you also the author of [this post](https://groups.google.com/forum/#!topic/blockly/APDCJi3B78U)?  I'm going to assume yes and answer there.

**Comment by bkisdi** [comment] 2017-03-31 13:36
Negative, that's another user.
Please don't "assume" and don't close the issue until solved.

Thanks for the explanation, anyway. It was not complete, but gave some hints.
Finally this is my solution - just for those who are interested in:

	block.select();      // *block* is the block to scroll into view.
	var mWs = Blockly.mainWorkspace;
	var xy = block.getRelativeToSurfaceXY();	// Scroll the workspace so that the block's top left corner
	var m = mWs.getMetrics();					// is in the (0.2; 0.3) part of the viewport.
	mWs.scrollbar.set(	xy.x * mWs.scale - m.contentLeft - m.viewWidth  * 0.2,
					xy.y * mWs.scale - m.contentTop  - m.viewHeight * 0.3);

The (0.2; 0.3) is arbitrary, but LGTM for showing the *block* and the surrounding blocks as well. The RTL case is not handled here.

**Comment by rachel-fenichel** [comment] 2017-03-31 16:39
Okay, since that isn't you, you get our standard response, which is to send you this message, try to be helpful, and close the issue because it's not a bug.

"For future questions like these, that aren't necessarily bugs, I suggest mailing the blockly google group. You'll reach a wider audience of blockly users that are likely to have good advice."

In this case you should post your solution to the linked thread, so that the other user can see what you have done.  I can post it and attribute it to you if you'd prefer.

**Comment by bkisdi** [comment] 2017-04-01 09:31
Thanks, Rachel, now I learned that the bug list and the support list are different. But what is the link of the latter?
Anyway, I suggest to include the code above into Blockly as a prototype function (improved with RTL support and configurable parameters instead of the constants).

**Comment by picklesrus** [comment] 2017-04-01 21:42
Here's the generic link to the mailing list: https://groups.google.com/forum/#!forum/blockly
The post Rachel was referring to is linked in Rachel's original response here:
https://groups.google.com/forum/#!topic/blockly/APDCJi3B78U)

**Comment by rachel-fenichel** [comment] 2017-04-03 18:16
Reopening as a feature request.

**Comment by towerpark** [comment] 2018-08-13 04:48
For those who are still interested in this issue, [an improved version of this function](https://developers.google.com/blockly/reference/js/Blockly.WorkspaceSvg#centerOnBlock) has been added to `WorkspaceSvg` class.

**Comment by rachel-fenichel** [comment] 2018-08-13 16:56
Closing since we did implement this (thanks for the reminder, @towerpark)

**Closed by rachel-fenichel** 2018-08-13 16:56 UTC
Labels: component: coordinates, help wanted, type: feature request
