### ISSUE TITLE
Android 28,can not open soft keyboard

### ISSUE THREAD

**Issue by gt-zhenqiang** [google/blockly#7990] opened 2024-04-02 08:46 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Android 28,click input ,can not open soft keyboard

### Reproduction steps

1. 
2. 
3.

**Comment by maribethb** [comment] 2024-04-03 21:27
Hi @gt-zhenqiang can you provide more information?

The default behavior is that if you tap a text input, we'll pop up a modal to allow the user to enter the text. The modal uses the browser's dialog implementation, so it's the browser's responsibility to open the soft keyboard.

We also support using the regular Blockly interface instead of modal inputs. This may not work well on older devices, so it's not the default behavior. To activate this mode, you can pass `modalInputs: false` in the Blockly injection options struct.

If what I've described doesn't match what you're seeing, we need more information before we can debug this issue. If you don't provide this information then unfortunately we will not be able to investigate this issue properly.

1) Can you reproduce this issue on our [demo page](https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html)?
2) Can you describe the behavior in more detail, or upload a screen recording?
3) Are there any errors in the developer console?
4) Please provide the version of Blockly you're using, the operating system version and device, and browser + version.

**Comment by maribethb** [comment] 2024-04-10 20:33
Hi @gt-zhenqiang if we don't hear back you from by next week we'll close this issue since we can't reproduce this. You can reopen it though if you're able to provide the additional information at a later time. Thanks!

**Comment by maribethb** [comment] 2024-04-19 16:37
Hi @gt-zhenqiang feel free to reopen this issue if you can provide the additional info requested above. Thanks!

**Closed by maribethb** 2024-04-19 16:37 UTC
Labels: issue: bug, issue: triage, needs more info

**Comment by cpcallen** [comment] 2024-04-19 16:39
(Note: "Android 28" presumably refers to Android 9, "Pie", [which is "level 28"](https://apilevels.com/).)
