### ISSUE TITLE
Blockly freeze on iOS 12.4 using function block with parameter

### ISSUE THREAD

**Issue by upetri** [google/blockly#3690] opened 2020-02-13 15:47 UTC
**Describe the bug**

When using an iPad mini 2 with iOS 12.4.5 (last supported iOS version for that device) installed Blockly freezes when trying to add a parameter to a function block.

I can also confirm this bug exists using an iPad Pro simulator with iOS 12.4 installed.

**To Reproduce**

1. Go to https://developers.google.com/blockly using an iPad mini 2 with iOS 12.4.5 installed (tested in Chrome and Safari).
2. In the demo window ('Try Blockly') click on 'Functions' and drag one of the first two function blocks into the workspace.
3. Click on the settings symbol of the newly created function.
4. Try to drag the "input name: x" block into the function block inside the function configuration window to add a parameter to that function.
5. Notice that after dragging the parameter block for a few millimeters the whole Blockly window froze and you have to reload the page. To be specific the Blockly app doesen't freeze completely but dragging any block is not possible anymore. Also opening a block category or closing the function configuration window is not possible anymore.

**Expected behavior**

I would expect the Blockly app to not freeze and just add a parameter to that function block. 

**Tablet:**
 - Device: iPad mini 2, iPad Pro simulator, ...
 - OS: iOS 12.4, iOS 12.4.5
 - Browser: Safari, Chrome

**Comment by samelhusseini** [comment] 2020-02-13 17:26
Thanks for filing @upetri. I was able to repro using your steps. We'll take a look.

**Comment by toabi** [comment] 2020-02-26 13:10
For completeness, here the post in the app inventor community https://community.appinventor.mit.edu/t/using-app-inventor-on-ipad-for-development/3632

**Comment by samelhusseini** [comment] 2020-03-23 21:20
I spent a good amount of time trying to investigate this. Unfortunately it appears the browser is crashing and I'm unable to get any diagnostic errors or a hint of what could be causing the crash.

It's important to point out that this repros only on IOS 12, and not on IOS 13. Perhaps the workaround is to upgrade, although I recognize that's not always feasible.

If someone out there has more experience with IOS 12 debugging, and is able to look into this, would very much appreciate it.

**Comment by toabi** [comment] 2020-03-24 10:02
Seems weird, in the original ticket (on community.appinventor) is written:

> We are using 2018 iPads on iOS 13.3.1

**Comment by Agajon** [comment] 2020-05-08 11:41
Regarding to problem of the freezing GUI in App Inventor (which occurs also on iPad with iOS 13): It seems, that there is a problem with the implementation of Blockly in App Inventor, that causes the freezing GUI. Because I was not able to reproduce this issue on https://developers.google.com/blockly

Original Ticket on https://community.appinventor.mit.edu/t/block-editor-freezes-on-ipad/8653

**Comment by awhart3** [comment] 2020-05-21 10:47
If it helps, I have encountered the same issue on an Android device using blocks with parameters in App Inventor. Has there been any progress on isolating the issue since the last comment?

**Comment by ewpatton** [comment] 2020-05-21 20:29
We have a fix for this prepared for App Inventor, but I can't explain the behavior observed in the OP, which was done with the Blockly demo page. I think it is possible the two issues may be unrelated.

**Comment by gonfunko** [comment] 2024-11-21 22:22
This no longer repros on iOS 18, and iOS 12 is old enough at this point it doesn't seem worth worrying about. Closing accordingly.

**Closed by gonfunko** 2024-11-21 22:22 UTC
Labels: issue: bug, component: touch, component: mobile
