### ISSUE TITLE
Workspace comments and all other bubbles should consistently handle single clicks.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1673] opened 2018-02-28 21:24 UTC
### Problem statement
Workspace comments, block comments, mutators, and warnings are all bubbles.  They don't all do the same thing on a single click.

### Expected Behavior

Clicking a bubble should bring it to the front of the workspace and select it for editing if possible.

### Actual Behavior

Clicking a workspace comment brings it to the front and focuses the text area.
Clicking any other type of bubble brings it to the front only if the click was on the colored outline.
Clicking on the contents of other bubbles focuses the bubble.

**Comment by BeksOmega** [comment] 2024-05-29 14:17
Dupe of #7675 I think

**Closed by BeksOmega** 2024-05-29 14:17 UTC
Labels: component: comments
