### ISSUE TITLE
The key events does not work when load xml previous generated by blockly

### ISSUE THREAD

**Issue by samael205** [google/blockly#1836] opened 2018-05-02 14:02 UTC
### Problem statement

¿Bug?

### Expected Behavior
Keyboard events must be enabled, and when I load an already created workspace, keyboard events function correctly

### Actual Behavior

We have programmed an application from blockly, which allows to save the xml configuration of a script generated with blockly in xml. This code is stored in a variable.

When we open blockly and load this xml content, keyboard events like the Delete key, do not delete the object in question until the blocks are updated, for example, change the selection of a DropDown.

### Steps to Reproduce

1. Start by..
    Add any block in blockly, and export its XML content to a variable.
2. Next, do..
Load blockly, with the XML content of the previous variable

### Operating System and Browser

 * Desktop Firefox

**Comment by AnmAtAnm** [comment] 2018-05-07 18:05
I am not able to reproduce this using the [playground](https://blockly-demo.appspot.com/static/tests/playground.html). I tested this with `Delete` (which requires a click to select the block) and `Ctrl-Z` on both Chrome and Firefox on Mac.

Finally, you mention `Delete` as your example key.  If no block is focused (with yellow border), this key does nothing. When I click a block to focus it, and then hit the `Delete` key, it performs as expected.

`Ctrl-Z` does not require block focus.  If I hit it immediately after importing the blocks, the import will revert the added blocks.

Finally, this may also have something to do with keyboard and block focus. Presumably, the code to load the blocks is coming from an event handler for a UI component outside Blockly's control. Performing this UI action probably sets the UI focus to something outside the Blockly view hierarchy.

I'm going to close this bug.  If you disagree, please reopen with specific steps to take in the Playground or similar app with available code.

**Closed by AnmAtAnm** 2018-05-07 18:05 UTC
Labels: type: bug

**Comment by samael205** [comment] 2018-05-08 07:00
hi @AnmAtAnm It may be my version of blockly, this version is at least July 2016, the fact is that, I followed your instructions, and do exactly what you tell me, I put the focus on a block, and in this one creates a yellow border, and I press the delete key, and it does nothing. On the other hand, if I refresh the contents of blockly, by changing a dropdown list, I press the delete key and the object is deleted.

We do not update blockly, because it would take us a lot of work to update all that this entails, besides I do not know where it should start. I have not compiled in blockly for a while, I modify the compiled files directly, I can manage them as I can.

I have generated an example of my blocks exported in XML, in case I see some failure in the generation of these, because I have not managed to load them into blockly playground.

`<xml xmlns="http://www.w3.org/1999/xhtml"><block type="scada_posicion" id=":-;7:?{w,LP@B36o_n*5" x="88" y="38"><value name="Objetos"><block type="scada_id" id="u5ZT@xyIqaGV0CmVd^Vn"><field name="id_list">2</field></block></value><value name="POS_X"><block type="math_number" id="{Up6=Dn^FSRV3C}0F?6A"><field name="NUM">50</field></block></value><value name="POS_Y"><block type="math_number" id="{!nr5If*YJNc1O[Y[D:I"><field name="NUM">50</field></block></value></block></xml>`

Thanks for everything
