### ISSUE TITLE
Dropdown with images doesn't select

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1287] opened 2017-08-19 15:15 UTC
Reported on the forums [here](https://groups.google.com/d/msg/blockly/sPllPNTn9q8/CoRYgx1LCwAJ):

i'm using "google-blockly-e064235". (2017 June 30 release + translations.)

I created a dynamic Dropdown with IMG instead of Text. The block displays all options correctly, but somehow the image doesn't change  if i try to choose another option. In addition the generator i always get "null" instead of the id i want to get. Any idea why?

Blockdefinition:
Blockly.Blocks['anki_car_img_id'] = {
  init: function() {
	  	  	function dynamicOptions() {
				var options = [];
				var b = get_all_car_ids();
				for(j=0;j<b.length;j++){
					options.push([{"src":"img/"+b[j]+".png","width":50,"height":50,"alt":"*"},String(b[j])]);
				}
				return options;
			}
    this.appendDummyInput()
        .appendField("ANKI Car ID")
        .appendField(new Blockly.FieldDropdown(dynamicOptions), "ANKICARIMGID");
    this.setOutput(true, "car_id");
    this.setColour(230);
 this.setTooltip("");
 this.setHelpUrl("");
  }
};

Generator:
Blockly.JavaScript['anki_car_img_id'] = function(block) {
  var dropdown_name = block.getFieldValue('NAME');
  var code = '"'+dropdown_name+'"';
  return [code, Blockly.JavaScript.ORDER_ATOMIC];
};

Here some snippets:
![ankidropdown1](https://user-images.githubusercontent.com/9916202/29487951-839890ac-84b6-11e7-8c0f-7ad9ebaa258f.jpg)
![ankidropdown2](https://user-images.githubusercontent.com/9916202/29487956-8ad99dc0-84b6-11e7-9007-81c9f019de70.jpg)
![ankidropdown3](https://user-images.githubusercontent.com/9916202/29487960-900aaeb0-84b6-11e7-9d63-154459605b06.jpg)

**Comment by rachel-fenichel** [comment] 2017-08-23 19:16
Dupe of #1047.  It's a problem with setText and setValue.  I spent some time looking into it last week but I don't have a fix yet.

**Closed by rachel-fenichel** 2017-08-23 19:16 UTC
Labels: affects: master, type: bug
