### ISSUE TITLE
For loop error

### ISSUE THREAD

**Issue by TKDKid1000** [google/blockly#5431] opened 2021-09-06 20:00 UTC
**Describe the bug**

I kept trying to add the loop block to my project, but there are a few problems. When I add it, I get 2 things.
1. The blocks in the control section are stacking on top of each other making it hard to access them.
2. The for loop block isn't showing, and there is an error in the console mainly saying `Block "controls_for": Message does not reference all 4 arg(s)`
3.

**To Reproduce**

1. Setup a basic blockly app. 
2. Run the following javascript code (done through npm, webpack may be needed), some of the code is removed as it is unnecessary.
3. Open up the core>control section and see stacked blocks.
4. Open console to see error.

**Expected behavior**
Blocks shouldn't stack, and for loop should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/69736165/132256923-f104cf71-dff2-42bd-be14-ff4103e50502.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Electron (chromium)
 - Version [e.g. 22] 14.0.0

**Smartphone (please complete the following information):**

**Stack Traces**

```
C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:550 Uncaught Error: Block "controls_for": Message does not reference all 4 arg(s).
    at Blockly.BlockSvg.Blockly.Block.validateTokens_ (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:550)
    at Blockly.BlockSvg.Blockly.Block.interpolate_ (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:549)
    at Blockly.BlockSvg.Blockly.Block.jsonInit (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:544)
    at Blockly.BlockSvg.init (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:821)
    at Blockly.BlockSvg.Blockly.Block (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:511)
    at new Blockly.BlockSvg (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:612)
    at Blockly.WorkspaceSvg.newBlock (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:716)
    at Object.Blockly.Xml.domToBlockHeadless_ (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:139)
    at Object.Blockly.Xml.domToBlock (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:130)
    at Blockly.VerticalFlyout.Blockly.Flyout.createBlock_ (C:\Users\_____\Desktop\BlocklyDiscordBot\node_modules\blockly\blockly_compressed.js:867)
```

**Additional context**
If this is the wrong place to put this, please tell me.

**Comment by gonfunko** [comment] 2021-09-07 20:54
I think the code in your step #2 ("run the following javascript code") may have been omitted - can you add it in a comment or gist?

**Comment by TKDKid1000** [comment] 2021-09-08 03:22
My bad! Thought i had it. https://gist.github.com/TKDKid1000/38c40f960df26510013a3476086b2001  Made the gist, guess I didn’t add it.

**Comment by gonfunko** [comment] 2021-09-10 20:23
No worries, your code appears to work for me but I suspect the overlapping blocks is being caused by the error. Can you check the value of Blockly.Msg.CONTROLS_FOR_TITLE in your console?

**Comment by TKDKid1000** [comment] 2021-09-10 23:17
The value was undefined previously, but even after adding it do my language file, I still get the same error.
![image](https://user-images.githubusercontent.com/69736165/132927000-ea54628e-e628-4c63-a505-7958254f8ff2.png)

**Comment by gonfunko** [comment] 2021-09-13 15:24
Ah, that's at least part of the problem - the message string needs to both be defined and have the correct number of placeholders, e.g. https://github.com/google/blockly/blob/master/msg/js/en.js#L39.

**Comment by TKDKid1000** [comment] 2021-09-14 06:09
> Ah, that's at least part of the problem - the message string needs to both be defined and have the correct number of placeholders, e.g. https://github.com/google/blockly/blob/master/msg/js/en.js#L39. 

Perfect link. Exactly what I needed to go in the right way. Thanks for the help!

**Comment by gonfunko** [comment] 2021-09-14 15:21
No problem! I'll close this for now, if you run into any other issues feel free to ask on the forum (https://groups.google.com/g/blockly) as well.

**Closed by gonfunko** 2021-09-14 15:21 UTC
Labels: type: bug, triage
