### ISSUE TITLE
Custom field, the width of parent element is not enough, overflow, how to solve it?

### ISSUE THREAD

**Issue by senbochen** [google/blockly#3528] opened 2020-01-02 02:29 UTC
![image](https://user-images.githubusercontent.com/45449695/71649539-b4100500-2d4a-11ea-91fd-1c42b1868db2.png)

**Comment by senbochen** [comment] 2020-01-02 09:32
![image](https://user-images.githubusercontent.com/45449695/71660394-decb7f00-2d85-11ea-90fe-bd822db582a2.png)

**Comment by samelhusseini** [comment] 2020-01-06 22:06
Dupe of https://github.com/google/blockly/issues/3529

**Closed by samelhusseini** 2020-01-06 22:06 UTC
