### ISSUE TITLE
Create an ADVANCED_OPTIMIZATIONS demo

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1241] opened 2017-07-31 15:52 UTC
We've broken advanced optimizations in Blockly a few times without noticing. We should create a demo that builds using Closure's advanced optimizations and if possible a minimal smoke test to our Travis testing to catch when things have gone wrong.

See https://developers.google.com/closure/compiler/docs/api-tutorial3 for details on using optimizations.
See https://github.com/google/blockly/pull/1240/files for the most recent fix.

**Comment by petrusek** [comment] 2017-08-02 13:01
Hi, I consider this issue to be a general ADVANCED_OPTIMIZATIONS discussion with a goal to make the demo (I don't want to create another issue with only the discussion without any goal). I hope it's OK.

The ability to build Blockly Games and trying/testing [Turtle level 10](https://blockly-games.appspot.com/turtle?lang=en&level=10) could be enough for the beginning.

Another advantage of using advanced optimizations is that it provides better typechecks and warnings (at least in our project).

I've noticed #1240 from @NeilFraser about fixing the strings. I would suggest using `@export`, since it has some benefits.
1. no need to overwrite all existing code `Blockly.Msg.SOMETHING` to `Blockly.Msg["SOMETHING"]`
2. better optimization when used on many places (IMHO not very significant in this case)

So all generated messages (in `??.js`) would have a `/** @export */` in front of them (autogenerated). To enable it in the compiler, this needs to be added: `--compiler_flags=--generate_exports`
The only issue is to access it in `utils.js` via e.g. `window['Blockly']['Msg'][msgKey]` which is not nice, but the only way (not to get renamed) - but still just in one file (it can be a function).

The `@export` solves some of the other issues too (e.g. function names), but not everything. For local properties this needs to be switched on `--compiler_flags=--export_local_property_definitions`.

**Comment by RoboErikG** [comment] 2017-08-02 16:25
Thanks for the tips! 

Our first task is just to get everything working with ADVANCED_OPTIMIZATIONS again, but we're far from experts on closure so suggestions/PRs are welcome. I'll take a look at using @export with the flag. It looks like we still have a lot of places that use Blockly.Msg.MSG_KEY which I don't think will work with the Blockly.Msg["MSK_KEY"] initializer.

**Comment by RoboErikG** [comment] 2017-08-03 00:32
I think I'm missing something, because I can't find a variation of export_local_property_definitions that works with the rest api. It accepts "generate_exports":"true" as a parameter, but that doesn't seem to do anything.

@petrusek any hints for getting this to work with the rest API?

**Comment by petrusek** [comment] 2017-08-03 15:58
The problem is a bit more complex, but I will prepare some small demo for you, which will help you create a better and bigger smoketest. Please have a look at https://github.com/petrusek/blockly/tree/compile-messages-with-externs and the individual commits.

**Comment by RoboErikG** [comment] 2017-08-03 16:09
And there's a fix for the extensions.js file here: https://github.com/google/blockly/pull/1253

**Comment by petrusek** [comment] 2017-08-03 17:01
The messages with externs and a small demo of advanced compilation will wait for that to be merged. It is at #1259.

**Comment by rachel-fenichel** [comment] 2018-05-17 18:41
Done: we have an advanced optimizations test, [instructions](https://developers.google.com/blockly/guides/modify/web/advanced), and a travis run.

**Closed by rachel-fenichel** 2018-05-17 18:41 UTC
Labels: affects: develop, affects: master, component: tests, help wanted, type: feature request
