### ISSUE TITLE
[Android] Suggest to open number keyboard when edit number field 

### ISSUE THREAD

**Issue by dieudv** [google/blockly#2341] opened 2019-03-27 01:46 UTC
Currently I edit the number field, although can't input character and just can input number but it still open the character keyboard,

**Comment by RoboErikG** [comment] 2019-04-19 17:03
This can probably be done by overriding [showInlineEditor_](https://github.com/google/blockly/blob/master/core/field_textinput.js#L190) in field_number.js and adding a [type="number"](https://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input) property to the input element.

**Comment by BeksOmega** [comment] 2019-04-20 00:47
Dupe of #1595 ?

**Comment by RoboErikG** [comment] 2019-04-20 02:44
Yep. Thanks for the pointer, Beks

**Closed by RoboErikG** 2019-04-20 02:44 UTC
Labels: affects: mobile, component: fields, help wanted, type: feature request
