### ISSUE TITLE
Output pop up shown twice on iPad for procedure testing

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#3751] opened 2020-03-17 05:47 UTC
**Describe the bug**
Output pop up shown twice on iPad for procedure testing

**To Reproduce**

Build the above set of blocks on the empty playground by selecting " categories(untyped variables)"
https://screenshot.googleplex.com/Y8TsM31vvqo.png

1.Export the blocks to xml
2.Clear the workspace
3.Import the xml you just exported
4.Verify the blocks are the same as above
5.Copy the XML from the text area
6.Paste it into the XML tab on the Blockly code demo(https://google.github.io/blockly/demos/code/index.html)
7.Click the red play button in the upper right corner

**Expected behavior**
Verify you get a popup that prints the value 10.

**Actual behavior**
Value pop up 10 is shown twice.

**Smartphone (please complete the following information):**
 - Device: iPad Model A1566
 - Browser: safari

Please note that it is working fine on desktop version with chrome and firefox browsers.

**Comment by samelhusseini** [comment] 2020-03-17 15:41
Thanks for filing, this is a dupe of https://github.com/google/blockly/issues/1949

**Closed by samelhusseini** 2020-03-17 15:41 UTC
Labels: triage, type: bug
