### ISSUE TITLE
Do not record undo for no operation.

### ISSUE THREAD

**Issue by jlaurens** [google/blockly#1884] opened 2018-05-20 20:33 UTC
### Problem statement

Example of noop: drag a block from the flyout directly to the flyout (the toolbox or the trashcan). This may happen when you started dragging the wrong block and do not want to conclude.

### Expected Behavior

For that kind of blank operation, there should be no event recorded at all on the undo stack

### Actual Behavior

A `Create/Move/Delete` event sequence is recorded. There might be side effects too (eg variable creation). When undoing, nothing visible happens. Bad user experience.
If there are side effects, undoing may seem weird. For example, if you drag the `randomize` block in the Blockly/Demos/toolbox.html from the toolbox flyout to the trash, you have absolutely nothing on the workspace but when undoing many dialogs ask for deleting a variable.

**Comment by cpcallen** [comment] 2024-08-30 17:21
This is a duplicate of #1458.

**Comment by gonfunko** [comment] 2024-10-30 20:07
Closing since this is a dupe, as noted above.

**Closed by gonfunko** 2024-10-30 20:07 UTC
Labels: component: events
