### ISSUE TITLE
Blocks Without a Next Connection Cannot Replace Blocks With a Next Connection

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2949] opened 2019-09-02 16:55 UTC
**Describe the bug**

Blocks without a next connection cannot replace blocks with a next connection.

**To Reproduce**

1. Add the following blocks to the test blocks file:
```
Blockly.defineBlocksWithJsonArray([
  {
    "type": "red_stack",
    "message0": "",
    "previousStatement": null,
    "nextStatement": null,
    "colour": 0,
  },
  {
    "type": "end_stack",
    "message0": "",
    "previousStatement": null,
    "colour": 0,
  },
]);
```
2. Load the following XML to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="red_stack" id="XjZRlVd3!b*StcLwKswS" x="21" y="20">
    <next>
      <block type="red_stack" id="fC0AE)e3EskHI]?$D~I1"/>
    </next>
  </block>
  <block type="end_stack" id="!hDCWa=%B*[qG:D.#sv6" x="87" y="17"/>
</xml>
```
3. Try to insert the orphaned red block between the two connected red blocks.
4. Observe how you cannot.

**Expected behavior**

You should be able to insert the orphaned red block.
The insertion marker manager should choose to highlight the bottom connected red block.

**Screenshots**

![InsertionStacks2](https://user-images.githubusercontent.com/25440652/64127652-61581980-cd67-11e9-8bfc-2227694fe5a6.gif)

**This is not browser specific**

**Additional context**

Rows work correctly:
![InsertionRows2](https://user-images.githubusercontent.com/25440652/64127713-b6942b00-cd67-11e9-8a1c-89878eff0713.gif)

**Comment by BeksOmega** [comment] 2019-09-06 20:18
I'll grab this.

**Comment by c3ho** [comment] 2019-11-05 17:02
Hi, I'm new-ish to open source. Can I try working on this issue?

**Comment by BeksOmega** [comment] 2019-11-05 20:50
Absolutely! I would start by checking if [showPreview_ ](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/insertion_marker_manager.js#L507)is getting called. If it is not I'd try and trace back through calls in that file and figure out why. If it is getting called, I'd check if there was a problem with [shouldReplace_](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/insertion_marker_manager.js#L411).

It could be something else, but I think that's a good place to start.

Happy bug hunting!
--Beka

**Comment by c3ho** [comment] 2019-11-14 08:06
@BeksOmega unfortunately, none of those were being called. However, I did find the issue though. 

Checking through the calls, it did find a connection, but it failed on the Blockly.Connection.prototype.isConnectionAllowed function, specifically this case(3)

```
case Blockly.NEXT_STATEMENT: {  
      // Don't let a block with no next connection bump other blocks out of the  
      // stack.  But covering up a shadow block or stack of shadow blocks is  
      // fine.  Similarly, replacing a terminal statement with another terminal  
      // statement is allowed.  
      if (candidate.isConnected() &&  
          !this.sourceBlock_.nextConnection &&  
          !candidate.targetBlock().isShadow() &&  
          candidate.targetBlock().nextConnection) {  
        return false;  
      }
```
I did a simple and dirty fix for now and made the switch case return true instead.

Before:
![image](https://user-images.githubusercontent.com/18711727/68837566-d5c60780-068a-11ea-9510-e8d184b2d52c.png)

After:
![image](https://user-images.githubusercontent.com/18711727/68837591-e37b8d00-068a-11ea-9d68-9bb96ea68f2b.png)

However, could you advise on how I should approach this? As setting the return to true would ruin the idea of the case(unless we don't need the case).

**Comment by BeksOmega** [comment] 2019-11-14 14:51
That's awesome @c3ho! I'm glad you found it!

Disclaimer: I don't actually work on the Blockly team, so I don't have final say in any decisions.

That said I do have some advice on figuring out if this is needed! What I did first is I checked out the git blame for the relevant lines:
![GitBlame](https://user-images.githubusercontent.com/25440652/68867022-0e290e00-06aa-11ea-935d-675f7f3f7334.png)
This will tell you who added what lines of code, what commit the changes were a part of, and what pull request those commits were a part of.

Using this I found that the changes were originally a part of #283.

Now these are the questions I'm looking to answer when I look at this PR:
* Was the change a request from an outside developer?
* Was there a relevant use case?
* Was the change recent?

As none of these things is the case, and no one on the Blockly team has commented on this issue saying that the behavior is intended, I think it's safe to remove this case. 

I'd go ahead and put up a PR, but again I don't have a final say about these things hehe. Thank you again for digging into this!

**Comment by RoboErikG** [comment] 2019-11-14 16:48
Whoops, sorry we hadn't been paying attention to this issue.

This was intended behavior and is to prevent a block without a next connection from disconnecting a large stack of blocks unexpectedly. There are some cases where this can be annoying if you accidentally bump a large stack.

That being said, I'm not sure there's a strong opinion on the Blockly team. @carljbowman does Scratch team have an opinion on this behavior?

**Comment by BeksOmega** [comment] 2019-11-14 17:13
> This was intended behavior and is to prevent a block without a next connection from disconnecting a large stack of blocks unexpectedly.

I don't think the blocks disconnecting will be unexpected anymore because insertion markers clearly highlight the blocks that will be replaced. It was probably much more of a problem when the only indication was the connection being highlighted.

**Comment by RoboErikG** [comment] 2019-11-14 17:17
Yeah, I agree which is why I don't have a strong opinion on this anymore. I do want to hear from Scratch team since this would be a change in behavior.

**Comment by c3ho** [comment] 2019-11-15 03:56
Thanks for the update! I'll hold off on making any changes until I hear back.

**Comment by c3ho** [comment] 2019-11-26 17:31
Any updates on this?

**Comment by RoboErikG** [comment] 2019-12-03 17:58
Heard back from @carljbowman , they'd prefer to not have a change in behavior on their side so it's probably better to leave it out of core Blockly for now.

Longer term, we've talked about adding a hook for setting your own connection checking. This would be useful for some more advanced use cases, such as type inheritance as well. Let's put this on hold until we can flesh out a design for that API.

**Comment by c3ho** [comment] 2019-12-05 19:54
Thank you for the update @RoboErikG . Thank you @BeksOmega a lot for all the help with this issue!

**Comment by alschmiedt** [comment] 2021-01-07 21:34
@rachel-fenichel is this case covered with the new ability to override the connection checker?

**Comment by maribethb** [comment] 2022-10-26 21:03
Closing this now, one can override the connection checker if they wish to change this behavior. There's an [example](https://github.com/google/blockly-samples/tree/master/plugins/strict-connection-checker) of a custom connection checker in samples.

**Closed by maribethb** 2022-10-26 21:03 UTC
Labels: component: coordinates, issue: feature request, component: connection
