### ISSUE TITLE
Dropdown field value doesn't update when options are dynamic

### ISSUE THREAD

**Issue by Nrosa01** [google/blockly#8056] opened 2024-04-27 23:04 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I created a block that has a dynamic option list. Let's say the first option of this dynamic array changes and the dropdown had the first option selected. Its field value should change too, but it doesn't. Example:

![image](https://github.com/google/blockly/assets/62796415/e05f2408-96b3-41d9-9815-91d775204b9e)

Expected:

![image](https://github.com/google/blockly/assets/62796415/27756e1e-353c-4aa4-b07f-5fbd65c0fe85)

Strangely, the dropdown values change, it's just the field value that doesn't

![image](https://github.com/google/blockly/assets/62796415/b79d2c86-2497-4513-b438-c92d0d265831)

### Reproduction steps

1.  Create dropdown block with dynamic options
2. Select an option
3. Edit the array that contains that options

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment] 2024-04-29 15:27
Mirror forum question: https://groups.google.com/g/blockly/c/Uh0EZREIGEI/m/pPkhnZNJBQAJ

**Comment by maribethb** [comment] 2024-04-29 23:42
Hi @Nrosa01 this is not a bug in Blockly so I'm going to close the issue. Someone will follow up with you on the forum soon. Thanks!

**Closed by maribethb** 2024-04-29 23:42 UTC
Labels: issue: bug, issue: triage
