### ISSUE TITLE
The block is disconnected after being dragged to the backpack

### ISSUE THREAD

**Issue by RAElwin** [google/blockly#6341] opened 2022-08-15 00:57 UTC
After using the backpack plugin, I encountered an issue, when I drag a block under the parent block into the backpack, the block will be disconnected from the parent block. The problem can also be reproduced from the official Backpack Demo.

For more details, please refer to the official forum link:
https://groups.google.com/g/blockly/c/3hV3icfw8TA

 I think this may be a blockly bug, is there a solution for this issue, or will official fix this bug in the future? Thanks.

**Comment by maribethb** [comment] 2022-08-15 18:55
Duplicate of https://github.com/google/blockly-samples/issues/1220

**Closed by maribethb** 2022-08-15 18:55 UTC
Labels: issue: triage
