### ISSUE TITLE
Blockly.setLocale do not translate all block

### ISSUE THREAD

**Issue by YUN-RU-TSENG** [google/blockly#4617] opened 2021-02-03 08:24 UTC
**Describe the bug**

I want to change the language of blockly. Since Blockly needs to set the language before generating the Workspace, I regenerate the workspace every time I change the language using Blockly.setLocale, but not all blocks will be changed, some blocks' dropdown menu language will not be changed and will remain the same.

**To Reproduce**
here is [online demo](https://codesandbox.io/s/blockly-7186z?file=/src/App.vue), i use vue2.

1. Click on select button, change language English to Chinese.
2. Check blocks' language, specially dropdown menu.
3. See Block do not all  translate.

<img width="597" alt="截圖 2021-02-03 下午4 14 33" src="https://user-images.githubusercontent.com/41847720/106717949-562faa00-663b-11eb-8e56-64a295c53009.png">

App.vue
```
<template>
  <div id="app">
    <div style="margin-bottom: 12px;">
      <label for="language">language: </label>
      <select name="language" id="language" v-model="language">
        <option value="en">English</option>
        <option value="zh-hans">Chinese</option>
        <option value="zh-hant">Chinese(Trandition)</option>
      </select>
    </div>
    <div class="workspace" ref="workspace" :key="workspaceId"></div>
  </div>
</template>

<script>
import Blockly from "blockly";

export default {
  name: "App",
  components: {},
  data() {
    return {
      workspace: null,
      language: "en",
      workspaceId: 0,
    };
  },
  watch: {
    async language() {
      ++this.workspaceId;
      const lang = await import(`blockly/msg/${this.language}`);
      Blockly.setLocale(lang);
      this.initBlockly();
    },
  },
  mounted() {
    this.initBlockly();
  },
  methods: {
    initBlockly() {
      this.workspace = Blockly.inject(this.$refs.workspace, {
        toolbox: `
<xml id="toolbox" style="display: none">

  <block type="text"></block>
  <block type="text_print"></block>
    <block type="math_arithmetic">
      <value name="A">
        <shadow type="math_number">
          <field name="NUM">1</field>
        </shadow>
      </value>
      <value name="B">
        <shadow type="math_number">
          <field name="NUM">1</field>
        </shadow>
      </value>
    </block>
    <block type="math_single">
      <value name="NUM">
        <shadow type="math_number">
          <field name="NUM">9</field>
        </shadow>
      </value>
    </block>
    <block type="math_trig">
      <value name="NUM">
        <shadow type="math_number">
          <field name="NUM">45</field>
        </shadow>
      </value>
    </block>
</xml>`,
      });
    },
  },
};
</script>

<style>
.workspace {
  width: 100vw;
  height: 100vh;
}
</style>
```

**Expected behavior**

all blocks translate to current language.

**Desktop (please complete the following information):**
 - OS
 - Browser : Chrome

**Comment by moniika** [comment] 2021-02-08 18:55
This could be related to #4369.

**Comment by YUN-RU-TSENG** [comment] 2021-02-22 05:59
I found somthing like this #1964 #1895

**Comment by YUN-RU-TSENG** [comment] 2021-02-22 06:00
is that blockly dropdown api's problem, seems like it doesn't support translate

**Comment by BeksOmega** [comment] 2021-02-22 23:10
> I found something like this #1964 #1895

@YUN-RU-TSENG I think you're right and that is the issue.

> I don't want to refresh my site, is there any other solution?

As mentioned [here](https://github.com/google/blockly/issues/1964#issuecomment-401861394), you should be able to change all of the broken JSON block-definitions to JavaScript block-definitions to fix the issue. If you change them to JavaScript blockly-definitions you can pass the actual Blockly.Msg references, rather than the %{BKY_...} strings that break the dropdowns. For example:

```
Blockly.Blocks['math_single'] = {
  init: function() {
    this.appendValueInput("NUM")
        .setCheck('Number')
        .appendField(new Blockly.FieldDropdown(
          [
            // Use the actual Blockly.Msg properties.
            [Blockly.Msg['MATH_SINGLE_OP_ROOT'],"ROOT"],
            [Blockly.Msg['MATH_SINGLE_OP_ABSOLUTE'],"ABS"],
            ["option","NEG"]
            ["option","LN"],
            ["option","LONG10"],
            ["option","EXP"]
            ["option","POW10"]
          ]), "NAME");
  }
};
```

But be warned, this could take a lot of work :/

**Comment by YUN-RU-TSENG** [comment] 2021-02-23 04:45
thanks.

**Comment by maribethb** [comment] 2021-03-20 00:08
Closing as a duplicate of #1895 . Thanks for reporting!

**Closed by maribethb** 2021-03-20 00:08 UTC
Labels: type: bug
