### ISSUE TITLE
problem work with webview of javafx

### ISSUE THREAD

**Issue by luokailiang** [google/blockly#99] opened 2015-05-13 05:33 UTC
there is a problem when put the  webpage into a webview of javafx
![qq 20150513132245](https://cloud.githubusercontent.com/assets/6735061/7604396/a5c38a26-f974-11e4-8598-187b7106df22.png)

**Comment by NeilFraser** [comment] 2015-05-14 06:08
Thanks for the bug report.  This is the second report of JavaFX getting filters wrong.  I've added a check for JavaFX and disabled the bubble's filter for this case.  See if the problem is fixed now.

**Closed by NeilFraser** 2015-05-14 06:08 UTC

**Comment by luokailiang** [comment] 2015-05-15 13:02
Thank you very much, the problem is already fixed
