### ISSUE TITLE
Ability to force a line break when inputs are inline

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3804] opened 2020-04-09 18:46 UTC
**Is your feature request related to a problem? Please describe.**

Have a way to force a line break when inputs are inline.

**Describe the solution you'd like**

Some way for developers to create a line break when inputs are inline.

**Describe alternatives you've considered**

Add a dummy input with a specific name, such as "ROW". 
Update the renderer to create a new row when it sees that, eg: 
```
var shouldStartNewRow = Blockly.zelos.RenderInfo.prototype.shouldStartNewRow_;
Blockly.zelos.RenderInfo.prototype.shouldStartNewRow_ = function(input,
  lastInput) {
  if (input.type == Blockly.DUMMY_INPUT && input.name == 'ROW') {
    return true;
  }
  shouldStartNewRow.call(this, input, lastInput);
};
```

**Additional context**

https://groups.google.com/forum/#!topic/blockly/eRFrGahCpxA

**Comment by BeksOmega** [comment] 2021-08-14 01:16
Dupe of #216

**Closed by BeksOmega** 2021-08-14 01:16 UTC
Labels: type: feature request
