### ISSUE TITLE
Long press broken on Playground and Multi-Playground

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1955] opened 2018-06-28 16:51 UTC
### Problem statement

In Chrome on Android long press doesn't work to bring up the context menu on both the Playground and Multi-Playground pages. It works correctly on the Code demo and other Blockly pages. 

### Expected Behavior

Long press brings up the context menu.

### Actual Behavior

Long press selects the text left of the workspace.

**Comment by AnmAtAnm** [comment] 2018-06-28 17:06
There is something particular about the playgrounds. The context menu appears as expected in both the Code demo and in Blockly Games.

**Comment by BeksOmega** [comment] 2021-06-28 16:37
This looks like a dupe of #2188 Leaving that one open because it has more info.

**Closed by BeksOmega** 2021-06-28 16:37 UTC
Labels: affects: browser, component: touch, help wanted, low priority, type: bug
