### ISSUE TITLE
Value missing while performing undo option in multi playground_Edge browser

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#3962] opened 2020-06-12 08:29 UTC
**Describe the bug**

Value missing while performing undo option in multi playground_Edge browser

**To Reproduce**

1. Load http://google.github.io/blockly/tests/multi_playground.html
2. Create complex blocks in LTR or RTL workspace
3. Delete the highlighted block in image1
4. Undo the activity by Ctrl+Z and verify

*Expected behavior**
Entire block should be recovered without missing value 10 in loop block

**Screenshots**
image 1: ![image](https://user-images.githubusercontent.com/56336353/84481455-bc824980-acb3-11ea-93cc-66e13d742c2c.png)

image2:
![image](https://user-images.githubusercontent.com/56336353/84481701-171ba580-acb4-11ea-8b9f-4948ca774e93.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8 Version 6.3]
 - Browser [Edge]
 - Version [Version 83.0.478.45 (Official build) (64-bit)]

**Comment by samelhusseini** [comment] 2020-06-12 15:26
Dupe of https://github.com/google/blockly/issues/3929

**Closed by samelhusseini** 2020-06-12 15:26 UTC
Labels: triage, type: bug
