### ISSUE TITLE
Procedure caller blocks should be disabled when dragged from the toolbox if the procedure def is disabled

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6700] opened 2022-12-12 22:10 UTC
**Describe the bug**

Normally when you disable a procedure definition, all of the procedure callers are disabled as well (because they have nothing to call essentially). However, if you disable a procedure definition and then drag another caller from the toolbox, the new caller is not disabled.

**To Reproduce**

1. Go to the playground.
2. Drag out a procedure definition.
3. Disable the procedure definition.
4. Drag out a procedure caller.
5. Observe how it was not disabled.

**Expected behavior**

The new procedure caller should be disabled after it is dragged into the workspace.

Alternatively, we could just disable it in the flyout, in which case it would be impossible to drag it into the workspace.

**Additional context**

N/A

**Comment by gonfunko** [comment] 2024-11-19 23:27
Duplicate of #8661

**Closed by gonfunko** 2024-11-19 23:27 UTC
Labels: component: functions, PR: feature
