### ISSUE TITLE
New bundles cause monkey-patch issues

### ISSUE THREAD

**Issue by oltdaniel** [google/blockly#6578] opened 2022-10-22 10:49 UTC
**Describe the bug**

Currently there aren't many options regarding customizing the contextmenu regarding its DOM content. Thereby, we've monkey patched version `8.0.5` in order to add icons to the contextmenu items. This is an ugly solution, but in the end it works.

Upgrading to version `9.0.5` there we're no real issues at first. However, it turns out monkey patching `Blockly.ContextMenu` functions are happily ignored by the new bundle due to internal references that ignore a new assigned value to the exposed functions.

This at least happens with the following functions of `Blockly.ContextMenu`:
- `show`
- `dispose`
- `hide`

**To Reproduce**

1. Go to https://google.github.io/blockly-samples/examples/generator-demo/
2. Open the developer tools in your browser of choice.
3. Open the contextmenu and do not close it again.
4. Execute the following line in the developer tools console: `Blockly.ContextMenu.hide()` and the context menu should be closed now.
5. So we can make a call from the exposed functions down into the bundle. Let's assign a new value to `Blockly.ContextMenu.show` by executing `Blockly.ContextMenu.show = () => console.log('success')`.
6. In theory, both the `showContextMenu` calls internally should all print `success` to the console. So try to open the contextmenu again.
7. The contextmenu is visible even though we tried to overwrite the regarding function.

**Expected behavior**

No contextmenu should appear, as we've assigned a new function to the `show` call.

**Additional context**

We've demonstrated that these are the correct functions by using the `Blockly.ContextMenu.hide` call first. However, due to new internal bundle references it is not possible to assign new values to them.This is probably related to the Typescript change that causes more use of internal references which is a big issues due to the monkey-patch nature of Blockly applications.

**Comment by rachel-fenichel** [comment] 2022-10-26 23:46
Hi @oltdaniel,

We've been steadily moving Blockly away from a fork/monkey-patch model and to a plugin model. As a team we've done our best to communicate that this change was coming, including through the [forum](https://groups.google.com/g/blockly-announce/c/bDw2DkX-KJc), github activity, and the developer summit. Solidifying the boundaries of the package allows us to clearly communicate about breaking changes and actually understand how developers are using the library. Monkey-patching works around this, and forces the team to freeze all APIs, internal and external, which was blocking actual bugfixing and feature development. 

As a result of modularization and the TypeScript rewrite, monkey-patching is no longer a viable way to modify Blockly's behaviour. Since this is working as intended, I'm closing this issue.

I see you already filed https://github.com/google/blockly/issues/6406 requesting the specific API that you need. I'll leave that open, because I agree that there's room for an API there.

**Closed by rachel-fenichel** 2022-10-26 23:46 UTC
Labels: issue: triage
