### ISSUE TITLE
Keyboard shortcuts should only fire when the workspace is focused

### ISSUE THREAD

**Issue by semiaddict** [google/blockly#8202] opened 2024-06-10 12:21 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I am using Blockly within a larger application, which also registers keyboard shortcuts.
Blockly shortcuts are handled via a keydown event listener on the document (see https://github.com/google/blockly/blob/master/core/inject.ts#L336).

My application also handles copy-paste shortcuts, but the listeners are added to the element on which the shortcuts are handled.
However, Blockly's shortcuts are also invoked when the workspace is not in focus, interfering with the application's shortcuts.

It seems best to either add Blockly's listener on the workspace's element, or only invoke the shortcuts if the main workspace is focused (see https://github.com/google/blockly/blob/master/core/inject.ts#L307).

### Reproduction steps

1. 
2. 
3.

**Comment by mark-friedman** [comment] 2024-06-10 18:36
I believe that this is a duplicate of #8187, and the good news is that that issue has been fixed in the latest (but not yet released) code.  The fix was in PR #8188.

**Closed** 2024-06-10 20:42 UTC
Labels: issue: bug, issue: triage
