### ISSUE TITLE
Blocks connected to blocks with multiple connections overlap with each other in Minimalist renderer

### ISSUE THREAD

**Issue by hpnrep6** [google/blockly#5371] opened 2021-08-14 06:04 UTC
**Describe the bug**
The top and bottom parts of blocks that are connected to blocks with multiple connections (e.g. lists) overlap with adjacent connecting blocks.

**To Reproduce**

1. Go to the [advanced playground ](https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html)
2. Set renderer to minimalist
3. Add a list block, or any block with multiple connections
4. Add a few connecting blocks to the list block. Notice how they overlap with each other

**Expected behaviour**

Blocks should not overlap.

**Current behaviour**

![Screenshot from 2021-08-14 01-52-18](https://user-images.githubusercontent.com/57055412/129435737-2c1e39b9-0edd-4c8b-b8cb-be874436de2b.png)

**Desktop**
OS: Ubuntu 21.04, macOS 11.4

**Browsers**
- Safari on macOS
- Chromium on Ubuntu
- Firefox on Ubuntu

**Additional context**

Actually not quite sure whether this is intentional or not.

Also, there is a similar situation with the thrasos renderer with an overlap of one pixel. (This might need to be opened as its own issue if this isn't also intentional)

https://user-images.githubusercontent.com/57055412/129437331-d4fd00ff-7a1f-4b54-a715-3368c1c7e28f.mp4

**Comment by alschmiedt** [comment] 2021-08-16 23:14
Thanks for the issue!

I believe this is working as intended. The reason we added this to the playground was to test the common renderer ([relevant issue](https://github.com/google/blockly/pull/3136)). I don't believe it was meant to be used by developers, other than possibly as a starting place. Because of this I am going to close the issue. However, if you think this is incorrect or have other concerns feel free to comment and I can reopen.

**Closed by alschmiedt** 2021-08-16 23:14 UTC
Labels: type: bug, triage
