### ISSUE TITLE
Block colour_rgb is Counterintuitive

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2612] opened 2019-07-06 14:20 UTC
### Problem statement

This block generates #ffffff:
![ColourRGB_100](https://user-images.githubusercontent.com/25440652/60757258-2e8ae280-9fbd-11e9-8bdf-233a839e3ad2.png)

This block also generates #ffffff:
![ColourRGB_300](https://user-images.githubusercontent.com/25440652/60757262-36e31d80-9fbd-11e9-971b-bcf557dc5c51.png)

### Expected Behavior

The resulting colour would be based on the relative size of the different inputs.

### Actual Behavior

The colourRgb function clamps the values without scaling, so the relative sizes are not preserved.

### Steps to Reproduce

1. Create the first block in the playground.
2. Generate javascript.
3. Run it in the console (and log the last line).
4. Repeat steps 1-3 for the second block.

### Additional Information

I do realize that the block has a tooltip that informs you of this function: "Create a colour with the specified amount of red, green, and blue. All values must be between 0 and 100." This is good, but still sub-optimal because:

A) People will often run into trouble /before/ checking the tooltip.
B) People who want to use this block to create gradients will have to do a lot of extra work to keep the values in range.

### Proposal

Create a new colour_rgb_proportional block that generates better code. Add it to the toolbox by default instead of the colour_rgb block.

**Comment by NeilFraser** [comment] 2019-07-06 15:11
Under this proposal, what numbers would generate #080808?

Sent (awkwardly) from an Android device.

**Comment by BeksOmega** [comment] 2019-07-08 14:10
> Under this proposal, what numbers would generate #080808?

Good point, I can't think of a solution for that one (or a solution that is better than the current solution anyway). So since the values /do/ need to be clamped to handle that situtation, I guess B is pretty much unfixable. :/

I do think A could be helped though, my proposal is to add custom shadow blocks inplace of the default number ones:
![ColourRGB_Percent](https://user-images.githubusercontent.com/25440652/60816637-fca98580-a14e-11e9-9d24-95e10b3e38b7.png)
![ColourRGB_Fraction](https://user-images.githubusercontent.com/25440652/60816650-00d5a300-a14f-11e9-8571-bd07e1448a76.png)
![ColourRGB_OutOf](https://user-images.githubusercontent.com/25440652/60816761-3bd7d680-a14f-11e9-903c-f066c5d61942.png)
This way you could also add constraints to the number field (you'd still have to keep the clamps in the generated code, but it would be another hint to users).

I'm not sure if you guys have ever done something like this / are interested in doing this though.

**Comment by maribethb** [comment] 2022-10-19 21:56
Going to close this as working as intended. A better solution would be to use a custom color field that doesn't has a better user input. For example, see the new hsv color picker in samples: https://google.github.io/blockly-samples/plugins/field-colour-hsv-sliders/test/

Or, applications can use this colour block with their own implementation of improved shadow blocks.

**Closed by maribethb** 2022-10-19 21:56 UTC
Labels: low priority, type: cleanup, component: library blocks
