### ISSUE TITLE
many warnings when blockly is loaded after document ready state is set to complete

### ISSUE THREAD

**Issue by oleggo** [google/blockly#4358] opened 2020-10-08 21:47 UTC
When my code uses Blockly and I am testing it with jest/jasmine, it produces warnings like this:

```   console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ} in %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}
    console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ} in %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}
    console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT} in %{BKY_LOGIC_COMPARE_TOOLTIP_LT}
    console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE} in %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}
    console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT} in %{BKY_LOGIC_COMPARE_TOOLTIP_GT}
    console.log node_modules/blockly/blockly_compressed.js:41
      WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE} in %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}
    console.log node_modules/blockly/blockly_compressed.js:41
   ...
```

I debugged it down to this line:

https://github.com/google/blockly/blob/11987dc6d6aa16138b36237e8959f2a3f91eb4e2/core/utils.js#L486

All that I need to fix it is to replace `fn()` with `setTimeout(fn)`

You check if these messages loaded once the document is loaded, but what if the document is already loaded (like in case of testing in jest)? `Blockly.Msg` table is still empty because it will be filled after blockly_compressed.js code finishes *loading*, like in this code:

>1 import En from 'blockly/msg/en';
>2 import Blockly from 'blockly';
>3 Blockly.setLocale(En);

So these messages will be set in line 3 but because `document.readyState == 'complete'` it begins to check these messages right in line 1 (for example here: https://github.com/google/blockly/blob/11987dc6d6aa16138b36237e8959f2a3f91eb4e2/core/extensions.js#L415)

**To Reproduce**

Add simple jest test with the lines 1-3 above, see the log output.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser NodeJS
 - Version 12

**Stack Traces**

Blockly.utils.checkMessageReferences(), blockly_compressed.js:41
anonymous(), extensions.js:415
getDescendants(), utils.js:561
runAfterPageLoad(), extensions.js:413
buildTooltipForDropdown(), logic.js:284
anonymous(), blocks_compressed.js:8
Object.<anonymous>(), blocks_compressed.js:12
_execModule(), index.js:867
_loadModule(), index.js:577
requireModule(), index.js:433
requireModuleOrMock(), index.js:598
anonymous(), blocks.js:6
Object.<anonymous>(), blocks.js:10
_execModule(), index.js:867
_loadModule(), index.js:577
requireModule(), index.js:433
requireModuleOrMock(), index.js:598
Object.<anonymous>(), node.js:35
_execModule(), index.js:867
_loadModule(), index.js:577
requireModule(), index.js:433
requireModuleOrMock(), index.js:598
anonymous(), index.js:6
Object.<anonymous>(), index.js:10
_execModule(), index.js:867
_loadModule(), index.js:577
requireModule(), index.js:433
requireModuleOrMock(), index.js:598
Object.<anonymous>(), setupTests.js:22

**Comment by rachel-fenichel** [comment] 2020-10-13 17:36
I assume that this is a question about [step 6](https://blocklycodelabs.dev/codelabs/getting-started/index.html?index=..%2F..index#5) of the Getting Started codelab. 

The problem is probably that you did not add the script tag to include your new block definition before you tried to use the block in the toolbox.

I'm closing the issue, but let me know if that doesn't fix it.

**Comment by rachel-fenichel** [comment] 2020-10-13 17:59
My bad--that was a response to a different bug that I posted in the wrong github tab.

**Comment by moniika** [comment] 2020-10-13 22:23
This seems to be the same issue as #4369. I'm closing this one to continue discussion there. Thanks @oleggo for filing and finding the relevant lines of code.

**Closed by moniika** 2020-10-13 22:23 UTC
Labels: triage, type: bug
