### ISSUE TITLE
Broken rendering of blocks that were serialized as collapsed

### ISSUE THREAD

**Issue by seldomU** [google/blockly#3454] opened 2019-11-19 11:16 UTC
This problem occurs when a collapsed block gets expanded, but only if that blocks was loaded in collapsed state. The image shows what happens. Fields are rendered too small for their content.

![expandedBlockdef](https://user-images.githubusercontent.com/10736677/69141603-6c4c5b80-0ac5-11ea-8e7e-884b48f52b4b.png)

To reproduce, load this block in the playground and expand it:

```xml
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="text_print" id="t+mk5:Sn8$Emu5`Zy9$0" collapsed="true" x="113" y="88">
    <value name="TEXT">
      <shadow type="text" id="lYNga3UcD+({1OyXedEJ">
        <field name="TEXT">abc</field>
      </shadow>
      <block type="text" id="Pw~h9j!XKX7aNLIB{PoO">
        <field name="TEXT">abc</field>
      </block>
    </value>
  </block>
</xml>
```

**Comment by BeksOmega** [comment] 2019-11-19 14:41
Are you on the latest release? I think this was fixed (#2811) and I couldn't reproduce it given your steps. Hopefully it hasn't come back!
--Beka

**Comment by seldomU** [comment] 2019-11-19 14:47
I'm on version 3 patch 3 and reproduced it on the [live playground](https://blockly-demo.appspot.com/static/tests/playground.html).

**Comment by RoboErikG** [comment] 2019-11-19 16:34
Note: This reproduces on Firefox but not on Chrome.

**Comment by samelhusseini** [comment] 2019-11-19 16:39
Could you provide repro steps, I'm unable to repro on either Firefox or Chrome. 
If you're showing / hiding the workspace, make sure you use ``workspace.setVisible`` as it ensures a re-render happens when the workspace gains visibility.

**Comment by samelhusseini** [comment] 2019-11-19 16:40
Yep, I'm able to repro on Firefox as well. Will investigate.

**Comment by samelhusseini** [comment] 2019-11-19 16:45
Note: this no longer repros on develop as we've changed the way we calculate size of text to a way that isn't affected by visibility, but I'm still intrigued as to why this only repro'd on Firefox.

**Comment by BamBam191** [comment] 2019-12-29 15:25
Same holds for Brave browser. It is even worse, all blocks are too small (w/o collapse expand)
![Capture](https://user-images.githubusercontent.com/46262667/71558839-c131a900-2a57-11ea-952b-c209b2542841.JPG)

**Comment by BeksOmega** [comment] 2023-01-18 00:59
Gonna go ahead and close this as fixed. If anyone can repro this again feel free to reopen!

**Closed by BeksOmega** 2023-01-18 00:59 UTC
Labels: issue: bug
