### ISSUE TITLE
Zoom in/out with CMD on Mac

### ISSUE THREAD

**Issue by weblocs** [google/blockly#4993] opened 2021-07-06 17:30 UTC
Using JS code:

Blockly.inject(element, {
      zoom: {
        wheel: true,
      },
      move: {
        scrollbars: true,
        drag: true,
        wheel: true,
      },
    });

we can zoom in/out on CTRL, but it doesn't work on CMD on Macs.

**Comment by moniika** [comment] 2021-07-07 17:19
Could you share a bit more about the browser and OS you are using?
I'm seeing the opposite when I try to reproduce: I can use CMD, but I can't use CTRL.

**Comment by moniika** [comment] 2021-07-07 19:12
Thanks @alschmiedt  for pointing out this line of code:
https://github.com/google/blockly/blob/64188ae27297b1ca23a3244cc987dfbfc6e98f34/core/workspace_svg.js#L1799

In order to repro, you must be setting the `wheel: true` option in inject.

**Comment by gonzalotudela-hub** [comment] 2021-07-08 18:07
Another data point for reference - Figma and Miro use CMD + Mouse Wheel for zooming.

It's been a while since I've used Photoshop, but I'm pretty sure it's the same.

**Comment by BeksOmega** [comment] 2021-09-02 13:41
Fixed by #5419

**Closed by BeksOmega** 2021-09-02 13:41 UTC
Labels: type: bug, help wanted
