### ISSUE TITLE
Build Blockly problem

### ISSUE THREAD

**Issue by ghwenti** [google/blockly#5214] opened 2021-07-26 14:59 UTC
**Describe the bug**

I downloaded the source code from: https://github.com/google/blockly/releases/tag/6.20210701.0
I am going to modify the source code to add some features and before doing so, I tried to build the downloaded and unmodified source code using:  npm run build:core

The following is from the log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:core'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'prebuild:core', 'build:core', 'postbuild:core' ]
5 info lifecycle blockly@6.20210701.0~prebuild:core: blockly@6.20210701.0
6 info lifecycle blockly@6.20210701.0~build:core: blockly@6.20210701.0
7 verbose lifecycle blockly@6.20210701.0~build:core: unsafe-perm in lifecycle true
8 verbose lifecycle blockly@6.20210701.0~build:core: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\WDAGUtilityAccount\Downloads\blockly-6.20210701.0\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WindowsApps;C:\Users\WDAGUtilityAccount\AppData\Roaming\npm
9 verbose lifecycle blockly@6.20210701.0~build:core: CWD: C:\Users\WDAGUtilityAccount\Downloads\blockly-6.20210701.0
10 silly lifecycle blockly@6.20210701.0~build:core: Args: [ '/d /s /c', 'gulp buildCore' ]
11 silly lifecycle blockly@6.20210701.0~build:core: Returned: code: 1  signal: null
12 info lifecycle blockly@6.20210701.0~build:core: Failed to exec build:core script
13 verbose stack Error: blockly@6.20210701.0 build:core: `gulp buildCore`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid blockly@6.20210701.0
15 verbose cwd C:\Users\WDAGUtilityAccount\Downloads\blockly-6.20210701.0
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:core"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error blockly@6.20210701.0 build:core: `gulp buildCore`
22 error Exit status 1
23 error Failed at the blockly@6.20210701.0 build:core script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**To Reproduce**
1. Installed Git (2.32.0.2)
2. Install Node.js (14.17.3 )
3. Download the source code from: https://github.com/google/blockly/releases/tag/6.20210701.0. Unzip it.
4. Inside the folder run: npm ci
5. Inside the folder run: npm run build:core

I have followed the document: https://developers.google.com/blockly/guides/modify/web/building.
However, it does not mention Git, do I need to install it in order to rebuild the source?
Any help is much appreciated. Thanks a lot!

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10 21H1
 - Browser [e.g. chrome, safari] Microsoft Edge

**Comment by BeksOmega** [comment] 2021-07-26 22:36
Hi @ghwenti thanks for reporting this =) Sadly I wasn't able to reproduce the issue :/ I think it might be because you're working on windows, but I'll have to wait until tomorrow to test that.

In the meantime, could you try running `npm install` and then `npm run build:core` to see if that fixes it? Also, is it only the `build:core` command that is having trouble? Or are other commands giving you errors as well?

**Comment by ghwenti** [comment] 2021-07-27 01:53
Dear BeksOmega, appreciate your quick reply. I tried "npm install" and "npm run build", the errors were similar as shown below:

E:\blockly-6.20210701.0>npm run build

> blockly@6.20210701.0 build E:\blockly-6.20210701.0
> gulp build

[09:49:14] Using gulpfile E:\blockly-6.20210701.0\gulpfile.js
[09:49:14] Starting 'build'...
[09:49:14] Starting 'buildLangfiles'...
[09:49:14] Starting 'buildCompressed'...
[09:49:14] Starting 'buildBlocks'...
[09:49:14] Starting 'buildUncompressed'...
[09:49:14] Starting 'buildJavascript'...
[09:49:14] Starting 'buildPython'...
[09:49:14] Starting 'buildPHP'...
[09:49:14] Starting 'buildLua'...
[09:49:14] Starting 'buildDart'...
[09:49:15] 'buildLangfiles' errored after 293 ms
[09:49:15] Error: Command failed: python ./scripts/i18n/js_to_json.py --input_file msg\messages.js --output_dir msg\json --quiet
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at buildLangfiles (E:\blockly-6.20210701.0\scripts\gulpfiles\build_tasks.js:421:3)
    at bound (domain.js:416:15)
    at runBound (domain.js:427:12)
    at asyncRunner (E:\blockly-6.20210701.0\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[09:49:15] 'build' errored after 297 ms
[09:49:15] The following tasks did not complete: <parallel>, <parallel>, buildCompressed, buildBlocks, buildUncompressed, buildJavascript, buildPython, buildPHP, buildLua, buildDart
[09:49:15] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockly@6.20210701.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockly@6.20210701.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User1\AppData\Roaming\npm-cache\_logs\2021-07-27T01_49_15_221Z-debug.log

**Comment by ghwenti** [comment] 2021-07-27 01:53
Sorry press the wrong button.

**Comment by BeksOmega** [comment] 2021-07-27 14:18
> Dear BeksOmega, appreciate your quick reply. I tried "npm install" and "npm run build", the errors were similar as shown below:

Thanks for running that test for me! The output makes me wonder, do you have python installed? You should be able to check by running `python --version` in your command line.

If it's not installed, try [installing it](https://www.python.org/downloads/) to see if that helps. And if it is installed, could you tell me what version you're using (output from `python --version`)?

Thanks again for being willing to go back and forth on this :D

**Comment by ghwenti** [comment] 2021-07-28 05:06
Dear BeksOmega, after I installed python, the errors went away. Many many thanks for your help!

**Comment by BeksOmega** [comment] 2021-07-28 13:45
Sure thing! Glad I could help :D I'm going to close this issue. If you have any further problems with building (or anything else) feel free to post a message on our [forum](https://groups.google.com/g/blockly) (we try to keep questions there for the most part hehe).

Best wishes!
--Beka

**Closed by BeksOmega** 2021-07-28 13:45 UTC
Labels: component: build process, triage, type: bug, type: question
