### ISSUE TITLE
Changing the compilation level to WHITESPACE_ONLY generates a runtime error

### ISSUE THREAD

**Issue by CoryDCode** [google/blockly#1132] opened 2017-05-24 22:43 UTC
If the compilation_level that's passed to the closure compiler is WHITESPACE_ONLY (in the gen_core function of build.py,) a FILE_NOT_FOUND error is thrown from blockly_compressed:

![screen shot 2017-05-24 at 3 42 32 pm](https://cloud.githubusercontent.com/assets/13773511/26428627/a5c96038-4097-11e7-87e4-1ae25a105dff.png)

While everything seems to function correctly, I think that this is likely a sign of something being ordered incorrectly in the build process.

**Comment by gonfunko** [comment] 2023-02-13 21:32
I modified the advanced compilation task to use this mode and confirmed the output file worked correctly. In light of that, and since build.py is no more and the build system has been significantly revamped since this was filed, I'm closing this issue.

**Closed by gonfunko** 2023-02-13 21:32 UTC
