### ISSUE TITLE
Field alignment appears broken when internal inputs are enabled

### ISSUE THREAD

**Issue by tmickel** [google/blockly#338] opened 2016-04-20 02:45 UTC
Example:
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#kk43hy

Try switching the alignment on the star. No matter the selection, the image is aligned left. Now switch to external inputs - the image is aligned properly.

**Comment by tmickel** [comment] 2016-04-27 16:49
@NeilFraser I noticed in the code that this is "TODO". Is this something you plan to implement?

**Comment by rachel-fenichel** [comment] 2018-05-21 19:27
Fixed in scratch-blocks, at least for the basic case:
https://github.com/LLK/scratch-blocks/commit/4ae2bf455042442e95fb660c31040b3945823612v

Next steps:
- Investigate whether we can just pull in the scratch-blocks fix.
- If so, pull the fix in.
- If not, mark as low priority.

**Comment by rachel-fenichel** [comment] 2018-05-23 17:53
There's one code path for an inline row, and different code paths for external value input rows and dummy input rows.  The branch is here:
```
    if (this.isCollapsed()) {
      this.renderJaggedEdge_(stepObject, row, cursor);
    } else if (row.type == Blockly.BlockSvg.INLINE) {
      this.renderInlineRow_(
          stepObject, row, cursor, connectionPos, inputRows.rightEdge);
    } else if (row.type == Blockly.INPUT_VALUE) {
      this.renderExternalValueInput_(
          stepObject, row, cursor, connectionPos, inputRows.rightEdge);
    } else if (row.type == Blockly.DUMMY_INPUT) {
      this.renderDummyInput_(
          stepObject, row, cursor, inputRows.rightEdge, inputRows.hasValue);
    } else if (row.type == Blockly.NEXT_STATEMENT) {
      this.renderStatementInput_(
          stepObject, row, cursor, connectionPos, inputRows, y);
    }
```

A dummy row (no actual input connection) on a block with inline inputs seems to still be rendered as an inline row, which means that it's missing out on the alignment code that's normally used for fields on dummy inputs.

The blocks look like this:
![image](https://user-images.githubusercontent.com/13686399/40442022-78ddd65e-5e77-11e8-970d-a724fb46e9fd.png)

The left has inline inputs; the right has external inputs.

**Comment by MNSDivya** [comment] 2020-05-06 11:23
![image](https://user-images.githubusercontent.com/56336353/81170523-781ad400-8fb8-11ea-89b2-a8217b173b0d.png)
Dummpy input seems changed to check star mark

**Comment by rachel-fenichel** [comment] 2023-04-26 20:44
Closing because I can't reproduce.

**Closed by rachel-fenichel** 2023-04-26 20:44 UTC
Labels: issue: bug, low priority, help wanted
