### ISSUE TITLE
caught Error: Unable to find connection in connectionDB.  

### ISSUE THREAD

**Issue by JiangGe-Ch** [google/blockly#7055] opened 2023-05-05 09:07 UTC
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I am trying to save the workspace as json or xml. But, when i reload the workspace from the json or xml and drag, create or delete a block, i got the error.Did I do something wrong?

Envirement:
node: v16.14.2
blockly: v9.3.3
vue: v3.2.13
Browers: Chrome 112.0.5615.139

### Reproduction steps

1. Drag a blcok from toolbox to workspace
2. Save the workspace as JSON or XML. 
3. Reload the workspace from JSON or XML.

For JSON, I did it like this:
    testReload(){
      let json=Blockly.serialization.workspaces.save(this.workspace)
      this.workspace.clear()
      Blockly.serialization.workspaces.load(json, this.workspace)
    }

And for XML, I did it like this:
    testReload(){
      let dom=Blockly.Xml.workspaceToDom(this.workspace)
      let xml=Blockly.Xml.domToText(dom)
      this.workspace.clear()
      Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(xml), this.workspace)
      Blockly.Xml.domToWorkspace(Blockly.utils.xml.textToDom(xml), this.workspace)
    }

### Stack trace

```shell
ceptions.ts:66 Uncaught Error: Unable to find connection in connectionDB.
    at Proxy.removeConnection (exceptions.ts:66:1)
    at RenderedConnection$$module$build$src$core$rendered_connection.moveTo (exceptions.ts:66:1)
    at RenderedConnection$$module$build$src$core$rendered_connection.moveBy (exceptions.ts:66:1)
    at BlockSvg$$module$build$src$core$block_svg.moveConnections (exceptions.ts:66:1)
    at BlockSvg$$module$build$src$core$block_svg.moveBy (exceptions.ts:66:1)
    at BlockSvg$$module$build$src$core$block_svg.positionNearConnection (exceptions.ts:66:1)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.showInsertionMarker (exceptions.ts:66:1)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.showPreview (exceptions.ts:66:1)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.maybeShowPreview (exceptions.ts:66:1)
    at InsertionMarkerManager$$module$build$src$core$insertion_marker_manager.update (exceptions.ts:66:1)
```

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment] 2023-05-05 19:37
Hello! Thank you for filing this issue :D

Are you able to reproduce this on the [playground](https://blockly-demo.appspot.com/static/tests/playground.html)? If so could you provide reproduction steps? If not, could you provide a minimal set of example code that reproduces this problem?

**Comment by maribethb** [comment] 2023-05-24 20:46
Hi @JiangGe-Ch,

I'm going to close this bug since we don't have enough information to reproduce it. If you provide more information with some code we can run or reproduction steps, feel free to reopen it.

As a note, these kinds of errors often happen if you're mutating a block but haven't defined serialization hooks. For example, if you add a connection to a block outside of the block definition, Blockly has no way of knowing about that added connection unless you define the serialization hooks. If this is happening for custom blocks you've written, that would be my guess. You can read more [here](https://developers.google.com/blockly/guides/create-custom-blocks/extensions#serialization_hooks).

**Closed by maribethb** 2023-05-24 20:46 UTC
Labels: issue: bug, needs more info

**Comment by zl7261** [comment] 2023-06-08 02:53
I meet this bug, in vue project , should not use ref or reactive API to cache workspace,Blockly.getMainWorkspace(),

**Comment by B1ackg0d** [comment] 2023-11-15 10:58
> @JiangGe-Ch, I meet this bug again, in vue project , should not use ref or reactive API to proxy workspace, just directly call Blockly.getMainWorkspace() itself.
Hello, may I ask you a question? If my project requires having two workspaces on one page, how should I handle this situation? Currently, I am also encountering this error. Thank you in advance for your reply.

**Comment by maribethb** [comment] 2023-11-15 17:14
Hello @B1ackg0d,

The return value of `Blockly.inject` is the workspace that has been injected. So you can save a reference to those and use them instead of calling `Blockly.getMainWorkspace()`.

In the future, you may have better luck asking these kinds of questions on our [developer forum](https://groups.google.com/g/blockly). Adding a comment on a closed issue is easily missed. If you have followup questions related to this, please do ask on the forum. Thanks!
